### ISSUE TITLE
Update Embargo enabled when embargo is not in effect

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#1050]
Peter tried to set an embargo for https://argo.stanford.edu/view/druid:yw340tg3386. The dialog worked fine, but results in a "We're sorry, but something went wrong." page.  He was trying a value of 2070, but it is reproducible with other, nearer term dates. 

We currently do not support setting embargo via Argo (see companion ticket https://github.com/sul-dlss/argo/issues/1051), so the button should not be enabled unless embargo is already in effect.

**Comment by cbeer** [comment]
Related to https://app.honeybadger.io/projects/49894/faults/36892245?

`ArgumentError: You cannot change the embargo date of an item that is not embargoed.`

**Comment by LynnMcRae** [comment]
So possibly the only issue is that the blue button should not be enabled in this case. Checking further.

**Comment by LynnMcRae** [comment]
Confirmed an issue with button being enabled, and fine for the backlog for now.

**Comment by peetucket** [comment]
How is an embargo set in the first place in Argo for an item with no embargo then?  Or is this not possible?

**Comment by peetucket** [comment]
I think its low effort to simply hide the button for non-embargoed objects (to prevent odd error messages from showing up), more substantial effort to instead allow for non-embargoed objects to be embargoed using the UI.  This is because there doesn't appear to be any dor-services methods to do this, and it would probably be best to implement there first, and then work backwards and do the UI work in argo.

Currently have a PR up to hide the button only: https://github.com/sul-dlss/argo/pull/1283
