### ISSUE TITLE
(uber ticket) Make reaccessioning easier (single object or async bulk) 

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1147]
See comments for Aug 6-7, 2019 - The goal of this ticket is to add the functionality of  re-accessioning (completely replacing the content of) single objects or lists of objects without having to additionally open and close a version for each object.

<hr />

I realize this ticket touches a number of different concerns, so will describe from a user point of view here.

Overview:
Quite often, it is necessary to reaccession an object or an entire batch of content. By reaccession, I mean "completely overwrite the existing content." Versioning for such a job can be accomplished two different ways: 1) manual (or scripted) update of versionMD to add new version stanza or 2) use of the "open for modification" blue button or bulk update.

Option 1) introduces overhead to the accessioning process. Option 2) leaves an uncompleted versionWF in the workflow table.

Desired outcome:
There are a number of different implementation options to solve this, but the desired outcome is that the versioning of reaccessioning jobs be handled properly (ie. either complete the workflow table rows during the accessioning process, or provide a mechanism in Argo to update the versionMD stanzas without kicking off the versioningWF or... [? there may be other options]).

**Comment by jcoyne** [comment]
One reason this is happening is because pre-assembly does not check to see if there is already an existing version in an accessioned state.  If there was, then pre-assembly should call `Dor::Services::Client.object(@object.pid).open_new_version(vers_md_upd_info: vers_md_upd_info)`.  This becomes important *now* because the new workflow service keeps track of which version is active.  With the old workflow service, just updating the version stanza in the versionMetadata datastream was sufficient.

**Comment by peetucket** [comment]
Possibly also an issue when a user is using Goobi (i.e not just pre-assembly) ... and they re-export an object after editing it, which then triggers a new assemblyWF without correctly versioning things.

**Comment by ndushay** [comment]
@peetucket @jcoyne I'm reading this ticket from @blalbrit as:

# we would LIKE to be able to "completely overwrite the existing content." 
# we would like to be able to do this for individual objects as well as in bulk
# we don't want to have to do some manual or script process to open versions on every object of interest in order to do this ... and we don't want to do some manual or script close version after, either.

This ticket, as I read it, is not complaining about particular errors thrown ... it's saying the way we have Argo set up right now, the above is not possible.  And that most of the time, leaving Argo functionality for this as it is now, is the right thing ... but there is also this OTHER case described here.

@blalbrit please confirm.

**Comment by ndushay** [comment]
@astridu have any idea how you would design this?

**Comment by ndushay** [comment]
Another question for @blalbrit @andrewjbtw @hannahfrost -- is this not the same as "move open/close objects to bulk actions" line in the planning spreadsheet?  It *seems* like it ...

**Comment by blalbrit** [comment]
@ndushay - yes, I think this is a dupe in most respects. Main thing is to make sure that it is possible to use the pre-assembly tool to completely overwrite an object without creating a version-mismatch error.

**Comment by ndushay** [comment]
See https://github.com/sul-dlss/pre-assembly/issues/423  re:  adding reaccession in pre-assembly

**Comment by ndushay** [comment]
I believe when this ticket is completed, we expect to see far fewer "version mismatch" errors showing up in workflows / honeybadger.  Thus, after this ticket and sul-dlss/pre-assembly#423 are done, we might want to clear those errors out of honeybadger, and ticket any NEW ones that come up.

**Comment by ndushay** [comment]
I believe this ticket will be addressed when sul-dlss/pre-assembly#525 is done.

**Comment by ndushay** [comment]
I'm closing this ticket;  please re-open if I am in error.  I think a bulk action to reaccession is a big thing ... and may deserve its own ticket?
