### ISSUE TITLE
Make "Edit Collections" dialog more than a unitasker

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1160]
Per @arcadiafalcone 

> -The Edit Collections dialog should not close after the user clicks a red x to remove a collection. Often the task is both to remove and add a collection, and the autoclose requires the user to reopen the dialog to complete the task

At the moment, the edit collection dialog is a granular single-task modal. Desired behavior would be to keep the dialog open until all tasks are completed and submitted. This might be satisfactorily handled by https://github.com/sul-dlss/argo/issues/926 instead.

**Comment by peetucket** [comment]
Notes: 

- [ ] convert link_to and form tags in `_collection_ui.html.erb` to ajax
- [ ] response in `items_controller#add_collection` and `items_controller#remove_collection` need to respond with js or some other structure that can be rendered in the modal instead of doing a redirect
- [ ] add place to show a message in `_collection_ui.html.erb` via the ajax response
- [ ] degrade back to current behavior for non ajax browser?
