### ISSUE TITLE
What is the status of the mdtookit link?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#124]
This method here: https://github.com/sul-dlss/argo/blob/develop/app/helpers/argo_helper.rb#L235-L242

Is only executed when documents have the `mdtoolkit_id_ssim` field. But when it is executed, it is done so in a poor manner that initiates a blocking request. @LynnMcRae can you comment on whether this is a feature that is used. If so, can you point to some records that should use this? Is this an intended feature?

A quick review of the argo indexes:
It seems like only one record in argo-dev index has this field
argo-b index has 383 items with this field

**Comment by LynnMcRae** [comment]
Metadata toolkit is long gone, so this code should never be executed.  We made the code cleanup a low priority functionally because we'll clean up any residual mdtoolkit references so the error would not occur. https://jirasul.stanford.edu/jira/browse/ARGO-463 addresses this but was not moved over and in the sprint because of this, but it certainly can simply go.
