### ISSUE TITLE
Create one or more virtual objects as a bulk action (formerly "virtual merge")

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1463]
Add GUI part for virtual-merge async bulk action. The bulk action will be named "Create virtual object(s)"

GUI should consist of a single "Import CSV" button. See #1511 (but ignore the other form fields in that design).

The CSV should be parsed on the Argo side and Argo should then use dor-services-client to push structured JSON to dor-services-app. Dor-services-app will return either a 204 if all virtual objects were created without error, or a 422 if there were any errors. The 422 will include JSON that provides information on which objects failed and why.

Output to the user will continue to use the same log file as other bulk actions (so argo will display object counts (total, success, reject) just like other bulk actions (e.g. reindex).) Note: it is known that the argo user will need to refresh to see progress on bulk actions.

**Comment by andrewjbtw** [comment]
An example of an existing CSV can be found attached to the ticket here https://jirasul.stanford.edu/jira/browse/LEGACY-4055

Note that the first row was "combinated" to test the fix of the virtual-merge script.

**Comment by ndushay** [comment]
Per Storytime Tues Aug 13, 2019:

We will be implementing this ticket effectively as it stands:
- ActiveJob can expect a single parent druid and array of child druids  (this is phase 1 implementation)
- output:  using the same log file and argo screens as other bulk actions is the desired outcome.

**Comment by ndushay** [comment]
see storytime 9-3-19

**Comment by andrewjbtw** [comment]
Hannah and I have discussed it and we are going with "Create virtual object" as the label. Note the singular since this is creating just one virtual object at this point.

**Comment by mjgiarlo** [comment]
@andrewjbtw :speech_balloon: 
> Hannah and I have discussed it and we are going with "Create virtual object" as the label. Note the singular since this is creating just one virtual object at this point.

Funnily enough, that's exactly what I labeled it in my branch. Great minds, or something!

**Comment by mjgiarlo** [comment]
The way that creating virtual objects is handled in dor-services-app, if any child object meets any of these conditions, an exception will be raised and the operation will halt: not open for modification; dark; or citation-only.

When that happens, that results in:

1. any child objects processed before the problem child will assert a relationship with the parent;
1. the parent's content metadata won't be saved after the initial reset (and thus will appear unaltered); and
1. the HTTP response from dor-services-app will be an exception and does not give clients information on which druids worked and which druids didn't.

That means it's currently impossible to render the bulk actions "total / success / failed" count with numbers that make sense to users.

Given that, the team discussed the following options:

1. make no changes in dor-services-app and leave users likely confused about the status of their virtual merge;
1. leave current "take first n valid children" behavior but enrich the information returned from dor-services-app such that argo can make more sense of how many succeeded and why the failed child failed;
1. switch to "handle invalid children gracefully" behavior, which combines all children that are valid (in order) and reports why each failed child failed; or
1. validate all children early before touching any objects and fail fast if any children can't be combined

@andrewjbtw recommends pursuing option `#4` above, so that's what I'll be doing. That means first I need to do some work in dor-services-app that blocks this issue. Marking as blocked.

**Comment by ndushay** [comment]
The problem is then dor-services-app needs to access each child object once for asserting it is open, not dark and not citation_only and THEN it needs to access each child again to add it.

The existing script happily edits parent object contentMetadata and child objects until it encounters an object NOT open for modification.  

I'm ok with the change, but object access twice for each affected object may impact performance.

Both @jcoyne and I noticed this very problem, and were ok living with the existing approach -- but I don't really care if we're okay with the tradeoff.

**Comment by mjgiarlo** [comment]
Closed by https://github.com/sul-dlss/argo/pull/1593
