### ISSUE TITLE
(uber ticket) virtual-merge: need to ensure object is not dark or citation only

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1464]
For virtual merge, the code uses `.allows_modification?` to determine if a child object can be added to the virtual parent object (and also to determine if a parent object can have virtual children added).

It is desired that virtual merge _NOT_ be allowed if an object is `dark` or `citation-only`, just as it is not allowed if `.allows_modification?` is `false`.

I *think* this info is currently available via dor-services;  not sure if it should be ported to dor-services-app / -client  and queried that way (ask @jcoyne)  (  https://github.com/sul-dlss/dor-services/blob/0c85ae8135e21a0c654cab470bb8dd8504208f87/lib/dor/datastreams/rights_metadata_ds.rb#L65-L66 )

I think there are 2 parts to this ticket (and they can be split into separate tickets:

1. create an appropriate way to determine if a Dor::Item is `dark` or `citation-only`  <-- not blocked
2. use the implementation of 1. to add this to virtual merge code (in argo or dor-services or dor-services-app or wherever it belongs) <-- this may be blocked by PR #1462 (for issue #1458)

**Comment by jcoyne** [comment]
Any parent or child object?

**Comment by jmartin-sul** [comment]
additional pointer for whoever picks this up:  for consistency with other code, and to take advantage of the rights-wrangling code we've already written, i'd interrogate a dor-rights-auth object.  there's already a dor-services method to obtain such an object right below the code @ndushay pointed to:
https://github.com/sul-dlss/dor-services/blob/0c85ae8135e21a0c654cab470bb8dd8504208f87/lib/dor/datastreams/rights_metadata_ds.rb#L75-L77

and some example code that shows how to use a dor-rights-auth object:
https://github.com/sul-dlss/dor-rights-auth/blob/ea541f4b2743e4c7f3ea01351919aede9fbf3cce/spec/index_elements_spec.rb
https://github.com/sul-dlss/dor-rights-auth/blob/ea541f4b2743e4c7f3ea01351919aede9fbf3cce/spec/dor_services_examples_spec.rb

so, for some random `Dor` object, you might just be able to do something like:
```ruby
obj.dra_object.index_elements['primary'] == dark
```

it's been quite a while since i've worked with the dor-rights-auth code, but i'd be very hesitant to go re-inventing its logic elsewhere, even if it is a bit knotty and painful to trace through at first glance.

**Comment by jmartin-sul** [comment]
unfortuntely, there appears to be no `dark?` convenience method on the dor-rights-auth object, but the same info does seem easily available via `index_elements[:primary]`

**Comment by jcoyne** [comment]
blocked by #1458

**Comment by ndushay** [comment]
@jcoyne definitely for child objects, and I assume for parent object too - @blalbrit @andrewjbtw ?

**Comment by ndushay** [comment]
I think there are 2 parts to this ticket (and they can be split into separate tickets:

1. create an appropriate way to determine if a Dor::Item is `dark` or `citation-only`  <-- not blocked
2. use the implementation of 1. to add this to virtual merge code (in argo or dor-services or dor-services-app or wherever it belongs) <-- this may be blocked by #1458

**Comment by ndushay** [comment]
Per Storytime Tues 2019-08-13:

"filter out dark / citation-only objects -- reject job if ANY like this" -- so basically, the job should fail if it encounters a dark or citation-only object, whether a parent or a child.

Note that we won't check an individual child until we are adding it.  BUT: since the contentMetadata on the parent object will be reset and recreated as part of a job re-run, and since duplicate relationships won't be added to child objects, this implies the child object should be corrected before the next attempt, or it should be removed from the list of children. Either way ... the job can be rerun without harm and it doesn't need a tech solution.

**Comment by jmartin-sul** [comment]
filed https://github.com/sul-dlss/dor-rights-auth/issues/37 and assigned to myself for the bit of work around determining whether something is dark.  planning to add a simple convenience method (and a corresponding couple tests) to the dor-rights-auth gem.

**Comment by jmartin-sul** [comment]
filed sul-dlss/dor-rights-auth#39 for determining whether something is citation only

**Comment by ndushay** [comment]
- [ ] sul-dlss/dor-rights_auth#40 to cut gem release
