### ISSUE TITLE
Modsulator jobs are failing in Argo

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1543]
reported in #dlss-aaas on Sep.3 after users tried to re-run jobs after fix in #1541 was deployed

**Comment by jcoyne** [comment]
@peetucket What logs?  What are the exceptions?

**Comment by peetucket** [comment]
I was just following along in #dlss-aaas and followed this example link: https://argo.stanford.edu/apos/druid:yf767bj4831/bulk_jobs

There was a downloadable progress log file there but it wasn't that useful.  That page won't even come up now.  I presume we are doing better logging somewhere (like production.log?)

**Comment by cebraj** [comment]
Not sure if this issue is related but I recall something similar happening back around May 7-9 (but in reverse order- first, users were getting system errors, and then after a fix, the objects weren't opening for versioning, and then Aaron debugged). There were a couple different, but related errors, something to do with this: https://github.com/sul-dlss/argo/pull/1395

**Comment by mjgiarlo** [comment]
FWIW, the underlying exception was in a `log.txt` file in the bulk metadata dir.

**Comment by mjgiarlo** [comment]
The patch that closed this issue has now been deployed to stage and prod.

**Comment by mjgiarlo** [comment]
This is confirmed resolved by @cebraj. @oceanofsound: if this isn't true for you as well, can you drop a comment here?

**Comment by oceanofsound** [comment]
Sure thing. Still trying to get the bulk upload page to load.

**Comment by oceanofsound** [comment]
All good, jobs are working for me again, thanks all!
