### ISSUE TITLE
Attempts to open versions are leading to the library system status page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1654]
**Describe the bug**
Attempts to open objects that should be openable are leading to a system status page.

**User Impact**
It's not possible to work with existing objects that need to be modified.

**To Reproduce**
1. Go to any object that can be opened.
2. Click on open for modification and attempt to open a new version.
3. See the library system status page

**Expected behavior**
The object can be opened.

**Comment by jcoyne** [comment]
Possibly due to https://github.com/sul-dlss/dor-services-app/commit/70a720c26f243688ddde7dcaa05e0b11a1c799af#diff-8da79eeadd6f6b14056107f06b7016e1R120

**Comment by jcoyne** [comment]
It looks like we switched to lifecycle, because that supported passing a version, but we still need to pass the `active-only=true` parameter as that unlocks additional logic: https://github.com/sul-dlss/workflow-server-rails/blob/053b31eb3dc01df64e14dfaef06d2b7f198fd519/app/controllers/workflows_controller.rb#L14

**Comment by jcoyne** [comment]
Resolved by deploying this branch: https://github.com/sul-dlss/dor-services-app/tree/fix_versioning_without_postgres (because master currently won't deploy due to a postgres dependency which has not yet been puppetized.)

**Comment by jcoyne** [comment]
we should consider doing https://github.com/sul-dlss/argo/issues/1656 to make this a better error experience.

**Comment by jcoyne** [comment]
Andrew said on slack this is fixed.
