### ISSUE TITLE
In report view, unable to select columns

### ISSUE THREAD

**Issue by caaster** [sul-dlss/argo#1670]
**Describe the bug**
In Argo, I navigate to: `https://argo.stanford.edu/report?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=ETDs&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned&f%5Breleased_to_ssim%5D%5B%5D=Searchworks`, and I select view > report view. Next, I select `columns` so I can specify the columns I want in my report. Nothing happens: no column labels appear in a dropdown menu so that I can select the ones I want.

**User Impact**
The columns are preset (at least they were in the past), so that all columns are not included when I download a report -- if I do nothing to specify which columns I want to see in the report. This limits my ability to perform robust analysis on a group of items. This is an important feature to maintain. I use this feature several times a month for various tasks.

**To Reproduce**
1. Go to 'https://argo.stanford.edu/report?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=ETDs&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned&f%5Breleased_to_ssim%5D%5B%5D=Searchworks'
2. Click on `Select View`
3. Select `Report View`
4. In bottom left-hand corner, select `Columns`
5. Nothing happens. I should see a drop down menu display with a list of all available columns that I can select from.

**Expected behavior**
Please see the above description, which explains the expected behavior.

**Screenshots**
This behavior is self explanatory.

**Additional context**
n/a

**Comment by jcoyne** [comment]
I believe this broke when we upgraded to jquery 3.
We had to upgrade to Jquery 3 because of a security vulnerability.  
The column selector is built on Jquery-ui 1.12, which was last updated over 3 years ago and doesn't work with the latest version of Jquery 3.

**Comment by caaster** [comment]
Is PSM being consulted when choices like this need to be made? Or even being notified?

**Comment by jcoyne** [comment]
@caaster Andrew was aware and tested the changes.

**Comment by jcoyne** [comment]
The UI worked in this commit (but was very ugly):
https://github.com/sul-dlss/argo/commit/adf8e86b848ede1d838e51641f1a5a92a5cf0620

There have been 88 changes to master since: https://github.com/sul-dlss/argo/compare/adf8e86b848ede1d838e51641f1a5a92a5cf0620...master

Highlights:
* switched to free-jqgrid (the old library was taken private and they required us to have an enterprise license)
* webpacker
* jquery ui now via npm (rather than a gem)

**Comment by andrewjbtw** [comment]
I was aware of the jquery changes but not aware of the impact it would have on the reporting functionality. I could only test what I knew to check.

**Comment by andrewjbtw** [comment]
For example, I would never sign off on having the link to "columns" remain in the interface if it didn't do anything anymore, which it doesn't.

**Comment by jcoyne** [comment]
@andrewjbtw don't feel bad. None of the engineering team was aware of that feature either.  This project hasn't really been worked on for 3 years and all of the original authors are on the access team or have left Stanford.

**Comment by caaster** [comment]
Going forward. A friendly reminder that there are DLSS staff who are active Argo users since the beginning of Argo, who still work here. Like me. I am always happy to help test and answer questions. I may not know the answer, but it is better to ask someone who might know rather than no one. Thank you.

**Comment by jmartin-sul** [comment]
spent most of thursday and friday trying to figure this out, but didn't have any real luck.

i tried a number of things using both free-jqGrid (the fully free/open source replacement library we switched to when upgrading the underlying jquery dependency) and jqGrid (the original library that got forked, but which is still open source, and [free for non-profit use](http://guriddo.net/?page_id=103334) [0]).  occasionally i'd get something that felt like progress, but in the end, nothing actually worked to get any sort of column chooser up.  additionally, reverting to mainline jqGrid introduced one or two minor UI regressions to the report view (a constantly present box that says `undefined` in the middle of the table, and broken column sort, though i hadn't tested that before, so maybe it was already broken).

you can see much of my flailing in this branch:  https://github.com/sul-dlss/argo/compare/fix-report-col-selection?expand=1  (i'd had some trouble getting my local dev instance of argo to serve CSS properly, and so for a while i was testing by pushing to stage, leaving much of my iteration with free-jqGrid captured in this branch; around the time i switched to trying mainline jqGrid, i got my local instance working, and so not quite so much detail about what i tried there is captured, since i didn't commit so many little changes once i no longer had to push a branch to stage for all my testing).

things i didn't try yet (because they felt like they'd definitely take longer than any flavor of current jqGrid):
* switching to a totally new library (e.g. DataTables, which jack said access uses).  as far as i could tell, this would've required reimplementing the javascript part of the report view.  it was also not clear to me from the documentation whether column selection exists out of the box with DataTables, and jack was unsure if it had that feature.  from skimming the docs and the repos for the [other libraries](https://github.com/FancyGrid/awesome-grid), many seemed unmaintained, and the ones that did seem maintained seemed to have the same uncertainties as DataTables.
* switching back to a very old version of jqGrid.  this option felt very likely to fail, and so seems like a last resort, considering that jQuery (which all of these table libraries depend on or interact with) changed its API across the major versions we upgraded between.  my recollection is that @jcoyne said the old jqGrid was incompatible with our current version of jQuery.
* ripping out jQuery or otherwise drastically reimplementing that view.  that didn't seem within my grasp for the second half of last week.



[0] _"If you want to use this product for a personal, school or non-profit project, then you can use it for free under the Creative Commons Attribution-Non-Commercial 3.0 License."  "You can use our software for free under the non-commercial license when you are:  A student, university or a public school; A non-profit organisation."_
http://guriddo.net/?page_id=103334
http://guriddo.net/?page_id=96

**Comment by jmartin-sul** [comment]
* going through the browser tabs from last week, this looks like a table implemented with free-jqGrid's current master branch, and it appears to do column selection:  http://www.ok-soft-gmbh.com/jqGrid/OK/groupingHeadersWithColumnChooser.htm
  * iirc, discovered via https://stackoverflow.com/questions/29365758/how-to-change-column-name-in-column-chooser-pop-up-in-jqgrid#29374787

was unable to use that example to successfully get our table to allow col selection.

**Comment by peetucket** [comment]
Still trying to write a code test, but I've got something working on my laptop that lets shows you all of the columns that were available and lets you select the ones for download.  It looks a bit different but uses the same buttons as before.  In the screen shot below from my laptop, the panel with column names and checkboxes is toggled below the grid when you click the "Columns" button.  Clicking the "Download" button downloads a report with just the selected columns.

A couple things to note:
* column selection does not affect the display on the webpage (I think it may have before)
* we can have a different set of default columns available for download than what is shown on the screen (e.g. only "druid,purl,title,status").  Selecting fewer columns should make the downloaded version of the report faster and it seems to make sense to default to fewer columns that is shown

![Screen Shot 2019-09-30 at 3 16 54 PM](https://user-images.githubusercontent.com/47137/65920954-8f943d80-e395-11e9-822c-942ce1a88664.png)
