### ISSUE TITLE
Unable to download a report

### ISSUE THREAD

**Issue by caaster** [sul-dlss/argo#1671]
**Describe the bug**
I navigate to `https://argo.stanford.edu/report?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=ETDs&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned&f%5Breleased_to_ssim%5D%5B%5D=Searchworks` -- and I select `Select View` and then I select `Report View`. Next, I select `Download` in the lower left-hand corner, and I wait, and wait, and wait. No report is downloaded.

**User Impact**
This is critical functionality. I pull several reports a month as I check on and perform analysis of content queues. I sometimes download reports to provide to stakeholders as well.

**To Reproduce**
1. Go to 'https://argo.stanford.edu/report?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=ETDs&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned&f%5Breleased_to_ssim%5D%5B%5D=Searchworks'
2. Click on 'Select View'
3. Click on `Report View`
4. Scroll down to and select 'Download'
5. I wait and wait and wait and no report is downloaded. This always worked in the past.

**Expected behavior**
I expect to execute the steps listed above, and after a minute, or 3, or 5 (generally, depending upon the number of items), I expect to see a .csv report in my download directory.

**Screenshots**
This is self-explanatory.

**Additional context**
n/a

**Comment by jcoyne** [comment]
I was able to download a report of 1200 items, but it took 131s.  It's possible that a bigger report would time out.

**Comment by peetucket** [comment]
For additional information, it would be helpful if we could identify the columns that are needed for downloaded reports (as opposed to viewing on screen).  The reason is that there may be some columns that are causing performance issues and if those columns are not actually needed when downloading reports, removing them may speed things up greatly.  Displaying is less of a performance issue because the entire result set is not fetched at once when showing in the grid.
^^
@dinahhandel @caaster and @andrewjbtw

**Comment by peetucket** [comment]
We can also use the most common list of columns identified as needed in reports to set as the default set that is offered for download.

**Comment by peetucket** [comment]
Note: some optimizations in #1693 should end up speeding up downloaded reports (once fully deployed to -prod).  There is also work to make this into a background job if needed (#1688)
