### ISSUE TITLE
[Hold for Vivian/Decision] versioningWF does not complete properly when reaccessioning via Goobi

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1781]
The change to fix this is described in sul-dlss/dor-services-app#702

**Describe the bug**
When reaccessioning objects using Goobi or the legacy preassembly scripts, the versioningWF remains active even though the objects have reached an accessioned state. Under normal operations, the versioningWF should be completed when a new object version is created and closed. 

Note that this is not a problem with preassembly reaccessioning, which was updated to handle versioning during the fall 2019 workcycle.

**User Impact**
As long as the versioningWF is active, an object cannot be opened again for updates. This can block metadata updates, as a common workflow is:

1. DPG reaccessions object via Goobi
2. A different staff member updates the descriptive metadata

Step 2 in the above workflow cannot be completed until the versioningWF is completed. Currently, the repository manager or other staff member with sufficient permissions must manually set the versioningWF to completed so that Step 2 can be run.

**To Reproduce**
1. Open an object in Argo
2. Export files via Goobi
3. The object will run through the correct workflows to be accessioned into SDR
4. But the versioningWF will continue to show as "active"

**Expected behavior**
Reaccessioning should result in a new accessioned version of an object with a completed versioningWF. The object should be openable again for further updates.

**Screenshots**
Example from: https://argo.stanford.edu/view/druid:cb927tp7596
![Screen Shot 2020-01-27 at 4 12 49 PM](https://user-images.githubusercontent.com/8975583/73225403-6c01b980-4121-11ea-892d-2a0482f59a06.png)

**Additional context**
Previously, when reaccessioning via Goobi, we were not opening objects before running the Goobi export. However, that method was creating numerous version mismatch errors that needed to be remediated manually because Goobi does not increment versions when sending files across to SDR. 

The solution to that problem was to open versions in Argo first and then have Goobi export files. This has eliminated the version mismatch errors but at a cost of having to remediate these versioningWF errors.

Final note: I have confirmed that this also happens when using lyberservices-scripts to reaccession, but I am the only one who does that so the impact isn't quite as widespread.

**Comment by ndushay** [comment]
Here is my analysis of the current situation:
- the Goobi software that interacts with our workflows is vendor supplied (Intranda seems to be the company, based in Germany);  we cannot directly change that software ourselves.  @peetucket believes @dinahhandel is the point of contact with Intranda.
- the Goobi software is currently expecting to be processing the first version of an object.  With this expectation, and with the state of SDR services when the goobi software was last tweaked, the goobi software, upon completing its stuff for the digitization workflows, as final goobi workflow step sends an API request to the dor-services-app (?) to kick off either `assemblyWF` or `accessioningWF` (I'm not sure)
- the `assemblyWF` and `accessioningWF` are perfectly happy to run with the assumption that the initiator of the WF did the "right thing" for versioning.
- the `accessioningWF` kicked off by goobi will discover a versioning problem when it tries to hand off the latest object to the `preservationWF` -- preservation expects a version exactly 1 greater than the latest version it has (e.g. i must be accessioning version 3 if preservation believes there are 2 versions for the object).  If the version is not updated before common-accessioning hands off to preservation, `preservationWF` will return "version mismatch" error - it will only accept a NEW version.
- to work around the problem with the "version mismatch" errors, we have changed the human workflow for re-runs in digitization labs to do a manual "open version" in Argo before finishing up the goobi workflow (?)
- this manual "opening the version" gets the re-run all the way through accessioning, but the `versioningWF` remains open, which hinders future changes to the object.

Possible solutions:
1.  Do nothing.  Same annoyance we have now continues for goobi objects.
2.  Allow objects in goobi re-run state to be manually closeable in Argo.
    - cost: dev work to address this state/permissions issue (unclear)
    - cost:  digitization labs folks have to remember to do it for every re-run object.
3. devs write some code to close goobi re-run object versions, if they have an open versionWF and accessioningWF is successfully completed for the open version.  Question:  is it possible to identify the correct set of such objects?
    - cost: devs writing this code; could be set up as a cron job (?)
    - question: can we correctly identify the objects that would need this done?
4. we ask goobi software folks to change their code to do the same API calls we do in current pre-assembly code, or effectively the same:  open new version, close new version without starting `accessioningWF`, and then start `assemblyWF `(assuming goobi starts `assemblyWF`, otherwise, this is just a regular open version and close version which will start `accessioningWF`)
    - cost: paying goobi company for their software services
    - cost: dealing with integration testing with the time diff b/t us and Germany
    - cost: what happens when we change the dor-services API endpoints?
5. devs write some code so dor services api has an endpoint that effectively takes the sequence from the previous option and wraps it in a single API call, so goobi software folks only have to substitute their single API call to get a closed version for accessioning.
    - cost: paying goobi company for their software services (but less than above)
    - cost: dealing with integration testing with the time diff b/t us and Germany
    - cost: what happens when we change the dor-services API endpoint?


As to **lyberservices-scripts**: they can be fixed to address version closure.  I will create a ticket to do that (and will do it - it's pretty simple)

**Comment by ndushay** [comment]
I created sul-dlss/lyberservices-scripts#44 for the lyberservices part of this;  renaming this ticket to refer only to the Goobi part.

**Comment by mjgiarlo** [comment]
@vivnwong Dropping a note to say that Goobi calling the WF without an explicit version number is causing a not insignificant (though not extravagant) number of honeybadger alerts: https://app.honeybadger.io/projects/58890/faults/60038817

**Comment by ndushay** [comment]
@jcoyne ^^ our GoobiWF stuff is external vendor code;  it may be far from trivial (e.g. $$) to get them to include a version when calling WF service.

**Comment by vivnwong** [comment]
Andrew/Hannah/Vivian discussed about the options, we agreed to ask Intranda for the assessment for the cost first. @andrewjbtw and @dinahhandel has the action item. If the cost is too high, this will be deal with in a proper workcycle, not a first responder work.

**Comment by dinahhandel** [comment]
@peetucket is working on scoping this work and will have an estimate to go over with @vivnwong and I soon.

**Comment by ndushay** [comment]
@peetucket @andrewjbtw - is this done now?  if so, please close issue.

**Comment by peetucket** [comment]
Yes, should be done.

**Comment by andrewjbtw** [comment]
I believe this is done via https://github.com/sul-dlss/sul-goobi/issues/258
