### ISSUE TITLE
object status indexing is not working correctly

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1795]
### Describe the bug
The status of objects is not being reported correctly. There are multiple components to this:

#### Processing status facet should not contain version numbers

The "Processing status" facet is including version numbers in its reporting, when it should be reporting only general statuses like "Registered" or "Accessioned."
<img width="404" alt="Screen Shot 2020-02-02 at 12 59 07 PM" src="https://user-images.githubusercontent.com/8975583/73672476-c9d25c00-4661-11ea-8754-7eeb41285bf7.png">

#### Item status and lifecycle information is wrong on item show pages

On individual item pages, both the status at the top of the page and the lifecycle information is often incorrect.

Example: https://argo.stanford.edu/view/druid:hn264yt9694

This item is reported as "v4 Accessioned" when it is still in v1 and still in accessioning (the accessionWF is still active).

![Screen Shot 2020-02-03 at 8 58 56 AM](https://user-images.githubusercontent.com/8975583/73673529-9db7da80-4663-11ea-8f73-faa74628f699.png)

Beyond that, the lifecycle display is very wrong. The dates for version 1 are wrong and the other versions don't exist.

![Screen Shot 2020-02-03 at 8 59 48 AM](https://user-images.githubusercontent.com/8975583/73673647-dce62b80-4663-11ea-8391-59c71cd58407.png)

#### Date searches aren't accurate

The incorrect dates for lifecycles also seem to be affecting the date-related facets. 

druid:qk936kt1687 is being reported as "v4 Accessioned" and shows up on a search for last accessioned within 7 days:

https://argo.stanford.edu/catalog?f%5Baccessioned_latest_date%5D%5B%5D=days_7&f%5Btag_ssim%5D%5B%5D=Project+%3A+Stanford+Band+%3A+Series+3+%3A+Parent+Objects&q=qk936kt1687

This is wrong for a number of reasons:

1. The version metadata shows there should only be 3 versions
2. The object is open, not accessioned
3. The object has not been accessioned for two months.

### User Impact
This affects our ability to:

1. Look up the actual processing state of objects.
2. Look up the dates when an object was processed
3. Get information on batches of objects using the search facets, which means all reporting with the data in its current state is going to be inaccurate.

From the looks of it, thousands of objects are affected, and the problem may be growing as the indexer runs.

### Additional context
The workflow information for the objects does seem to be accurate. Even when an object shows the wrong number of versions, the workflow information looks correct. It also looks like objects are enforcing "openability" and "closeability" accurately even if Argo is reporting the wrong information.

This is probably an indexing/solr problem rather than an Argo display problem, but I haven't looked at the solr data as closely.

**Comment by mjgiarlo** [comment]
See sul-dlss/dor_indexing_app#340

**Comment by mjgiarlo** [comment]
Also: https://github.com/sul-dlss/dor-workflow-client/pull/154

**Comment by mjgiarlo** [comment]
An update for @andrewjbtw @vivnwong:

There are two unrelated bugs in this issue.

One bug deals with how the processing status facet renders (should not include version number, but did). The bug was caused [in dor_indexing_app](https://github.com/sul-dlss/dor_indexing_app/commit/368c76cc9ce528e0dbf71f2165f02f1c24bd2abf#diff-addb397215cb4bcc7cb8347d7be166c8R96). It was fixed earlier today: https://github.com/sul-dlss/dor_indexing_app/pull/340/files#diff-addb397215cb4bcc7cb8347d7be166c8

The second bug was the cause of widespread and general workflow status confusion. This was caused [in dor-workflow-client](https://github.com/sul-dlss/dor-workflow-client/commit/5f7437cd225677e0834f0e4a1bffc40c3daa8afb#diff-1aa7a10ceca9eb187f28ff763ba69998R85). It was fixed earlier today: https://github.com/sul-dlss/dor-workflow-client/pull/154/files#diff-1aa7a10ceca9eb187f28ff763ba69998

Both of the above bugs were created as part of work to move away from the dor-services gem (the `Dor::StatusService` in particular), which talks directly to Fedora. This is part of SDR evolution work.

**Comment by andrewjbtw** [comment]
Fixes for both of these issue are in production and status indexing is returning to normal. Closing the ticket now, though it may be another day or two before the index is back to normal.
