### ISSUE TITLE
Download all files in an object

### ISSUE THREAD

**Issue by rosy1280** [sul-dlss/argo#183]
On an item page, a user should be presented with a way to download all the files currently listed in the contents section of an ojbect.

Here's a random druid with a content section so you can see what I mean. https://argo.stanford.edu/view/jz198xp6935

**Comment by jcoyne** [comment]
I think this looks like a good way of doing the download: https://github.com/WeTransfer/zip_tricks

but I'm not sure what the user interface should look like.  Should this only be for download from the workspace or only from preservation? @astridu can you help?

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/81346946-14ec7880-9070-11ea-8213-aaaadaad19e8.png)

Add the font awesome download icon (fa-download [&#xf019;]) plus 'Download all files' link in the gray 'Content' bar.

**Comment by jcoyne** [comment]
@astridu Should there be a way to indicate if it's downloading from preservation or workspace?  Or if where they are downloading from preservation or workspace?

**Comment by astridu** [comment]
Could they select if they want to download from preservation or workspace?

**Comment by jcoyne** [comment]
I think it would be possible if they had uploaded new files that hadn't been reaccessioned. Maybe @andrewjbtw can help understand the cases we want to support.

**Comment by andrewjbtw** [comment]
Huh, I was misunderstanding what "workspace" meant here. Somehow all these months I've read it as a category, not a location. As in "Preservation" and "Stacks" are both "Workspaces". It never occurred to me that "Workspace" is supposed to me the /dor workspace.

I think we should just take "Workspace" out entirely as an option. I've never seen anything downloadable from "Workspace" and I don't think it's a case we should support.

The two locations we enable for download are Stacks and Preservation. I think those should be separate options because there are use cases for downloading only the access files (Stacks).

**Comment by andrewjbtw** [comment]
The Stacks link will appear for files that have shelve=yes. Also, Stacks enforces the no-download rules on everyone, even Argo users. I don't think we can do anything about that in the short run.

**Comment by jcoyne** [comment]
@andrewjbtw I don't think argo has access to the stacks mount, so downloading from there would not be possible.

**Comment by andrewjbtw** [comment]
It's already possible, but it must be following the public links via http. That must explain why the access controls are enforced.

**Comment by mjgiarlo** [comment]
@jcoyne @andrewjbtw Where does that leave this ticket? Is download from preservation sufficient to satisfy this need for now? I assume the "Contents" that are being displayed are what's been preserved.

**Comment by mjgiarlo** [comment]
@jcoyne @andrewjbtw If using the zip_tricks approach above to stream a zip to users in realtime, should on-the-fly compression be used for 1) every file; 2)  select files (ones that benefit from compression); or 3) no files?

**Comment by andrewjbtw** [comment]
The contents listed in Argo is all files in the object, whether they are preserved or not. I think the list is pulling from contentMetadata.

This is the current behavior:

In the contents list, there is text next to each file that lists publish, shelve, or preserve. A file that has:

- shelve = a copy is in Stacks
- preserve = a copy is in Preservation
- shelve/preserve = there's a copy in Stacks and a copy in Preservation

When you click on the file, you're presented with a modal that provides a link or links to download the file. If the file is:

- shelve = you only see a Stacks link
- preserve = you only see a Preservation link
- shelve/preserve = you see a Stacks link and a Preservation link

If the file is access-restricted via the rights settings:

- any copy in Stacks is subject to the access restriction: if it is no-download or location-restricted, the link from Argo will not work.
- any copy in Preservation will be downloadable, regardless of rights settings (Argo permissions determine if a user can see the object)

**Comment by andrewjbtw** [comment]
Given the above behavior, downloading only from Preservation is probably the most achievable outcome. But we should watch out for object size. Some objects are over 10 GB in size. The largest are over 2 TB.

**Comment by jmartin-sul** [comment]
we could add a warning when trying to download a zip that's expected to be over a certain size, and/or set some limit beyond which self-serve download is disallowed.

**Comment by mjgiarlo** [comment]
Remaining questions to pin down:

1. Assuming we deliver a single zip file, should compression be used for 1) every file; 2) select files (ones that benefit from compression); or 3) no files?
2. What is the max total size we should allow users to download?

Tagging the PO and TLs to help answer these: @andrewjbtw @aaron-collier @jmartin-sul

**Comment by andrewjbtw** [comment]
I would skip compression since it's unlikely to provide enough gain to be worth the cost of the time it takes to compress or the complexity of figuring out what to compress if we don't try to compress all files.

For download size limit, there are backwards compatibility issues with files over 4 GB. I guess Argo users aren't likely to be on FAT or use old Zip utilities to unzip because they're probably on a work-provided computer, but even with on-campus wifi it probably takes 30 minute or more to download 4 GB. So I would go with 4 GB.

It might be worth doing a back of the envelope calculation of what percent of objects are actually under 4 GB.

**Comment by mjgiarlo** [comment]
Other issues keep jumping in front of this one for me, so I am unassigning. Cc: @jcoyne
