### ISSUE TITLE
Support longer lists of druids in checksum report bulk action

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1997]
From @jcoyne in Slack:

> do you want to make a ticket so that the ChecksumReportJob breaks that into reasonable sized chunks so that no one request will timeout? 

Currently, checksum reports timeout if a batch is large enough. It can be hard to tell just how large a batch is too large, which is frustrating to users. There are use cases for generating large checksum reports, so the bulk action should support them.

**Comment by jcoyne** [comment]
This was causing Notices to honeybadger like this:
```
2020-05-08 18:55:09 UTC ChecksumReportJob failed on call to Preservation Catalog API: (Preservation::Client::ConnectionFailedError): Unable to reach Preservation Catalog - failed with Faraday::TimeoutError: Net::ReadTimeout with #<TCPSocket:(closed)>

```

**Comment by ndushay** [comment]
Developer should look at code, see where the performance problem(s) are ... and try to figure what makes sense.

We know we have chunked well when there are no Honeybadger errors.   In the absence of other ideas, start with 500 as the max chunk size, and hope that there are no HB errors ...   And we can then reduce this number (make it a setting?) as needed.

This changes no data, so we can test against prod data (in prod - we test in prod)

Andrew knows 2 folks run into this:  Tony C and Geoff

Speed of results is not an issue.

Why do we need this report?
- because depositors want to be sure that the SDR checksums match the depositors checksums for files ... that large files didn't get corrupted on ingest?
- cocina version of the objects can be slightly off from prescat depending on state of cocina (open, etc.)
- we must check against preservation to get deterministic results on checksums
