### ISSUE TITLE
Port "Set content type" bulk update to bulk action

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2031]
**Existing update method**

This bulk update takes a list of druids and presents the user with the content type menu.

**When porting to bulk action**

The bulk action should offer the same interaction: a list of druids + the content type menu. The content and resource types chosen from the menu will then be applied to the druids on the list.

**Comment by andrewjbtw** [comment]
https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/463636134_ba_Content_Type

![bulk-content-type](https://user-images.githubusercontent.com/8975583/153558105-8ed91e4b-5fea-445c-bc47-19b4a1929ec6.png)

**Comment by lwrubel** [comment]
A few questions for @astridu and @andrewjbtw:
1. The other Bulk Actions forms have the common fields below the job-specific fields, rather than above them as in this design. Is that a requirement here--to have them below?
2. Should the dropdowns only include values that are in the suggested mapping text? Wondering if the other possible resource types and content types should be left out (e.g. media, audio, video, web, 3d). Related, there are two book content types (ltr and rtl) so I think the idea is to list both of them in the "New content type" dropdown, not just Book?

**Comment by lwrubel** [comment]
To update question number 2 above, I think based on current Argo that the idea is to keep the content type options as they are (see screenshot below) but I wanted to be sure. 

![Screen Shot 2022-02-23 at 12 14 48 PM](https://user-images.githubusercontent.com/1619369/155371534-5f376edb-48e5-4aa2-ac13-9172274cb5d9.png)

**Comment by andrewjbtw** [comment]
Taking your questions in order:

>The other Bulk Actions forms have the common fields below the job-specific fields, rather than above them as in this design. Is that a requirement here--to have the specific fields below?

Good catch. In the "bulk updates" page the boxes were in reverse order. For consistency, we should move the druid box to the bottom and the settings menus to the top.

> Should the dropdowns only include values that are in the suggested mapping text?

The dropdowns should include the values in the current menu on the bulk updates page, including separate entries for reading order. Values have been added over time without updating the help text, partly because there's a point where it's hard to suggest mappings when objects can contain more than one resource type.

We should not port over the language about editing XML.

**Comment by lwrubel** [comment]
In the design, the label "Current resource type" ends up being far away from the pull down menu. Would it be OK to move it above the dropdown and leave the instructions at the top of the form?

Before:
![Screen Shot 2022-02-25 at 3 09 09 PM](https://user-images.githubusercontent.com/1619369/155792131-67737dd1-0b8f-48f4-872a-2d12efe5e4a6.png)

After:
![Screen Shot 2022-02-25 at 3 11 49 PM](https://user-images.githubusercontent.com/1619369/155792394-8823c8eb-1aeb-4b30-a7fa-88954171bb26.png)

**Comment by andrewjbtw** [comment]
I missed your question about the design earlier. This makes sense to me. I'm not sure how we ended up with the label that far apart from the menu. I guess I just didn't notice it.
