### ISSUE TITLE
Port "Add a workflow" bulk update to bulk action

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2034]
Input: a list of druids
Button: add workflow (pops up menu)

**Comment by andrewjbtw** [comment]
https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/463636138

![bulk-add-workflow](https://user-images.githubusercontent.com/8975583/153560341-742bbdc8-7cf8-4b20-84b1-d8aff58c4be7.png)

**Comment by jcoyne** [comment]
@andrewjbtw Should this go under the "Perform Actions" section of the menu?

**Comment by andrewjbtw** [comment]
This works as expected. I only have a couple of comments for the UI:

- Under "Perform actions", this should go at the end of the list, after Purge. This action is used rarely, mostly for certain GIS and web archive needs. I should have remembered to specify this.

- I wonder if we can prune the workflow list. There are a lot of workflows on there that are either deprecated or should not be run on their own. Since the same menu appears on the show page, I can ticket that separately.
