### ISSUE TITLE
Dissertation ID doesn't show up in report view for registered ETDs

### ISSUE THREAD

**Issue by caaster** [sul-dlss/argo#2058]
**Describe the bug**
New feature released for Argo report view is supposed to include dissertation ID (derived from the properties datastream) for all ETDs. I am not seeing dissertation ID populated in report view for registered ETDs (it does appear for accessioned ETDs). Dissertation ID is important information that should be included regardless of item processing status. 

**User Impact**
A description of the impact of this bug on an end-user (or your own work).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jcoyne** [comment]
ETD in Argo looks completely different before the "[other-metadata](https://github.com/sul-dlss/hydra_etd/blob/master/app/jobs/other_metadata_job.rb)" workflow step than they do after. We do not have the preaccessioned dissertation id indexed.   If you want a report like this, that is specific to ETD objects, we should probably build it in the ETD app because in the near future we are going to move pre-accessioned ETD apps out of Fedora completely.  This change will help us migrate off of Fedora 3.

**Comment by caaster** [comment]
Thanks @jcoyne - I will close this ticket and create a new one in hydra-etd, to be prioritized for the workcycle coming up in July.
