### ISSUE TITLE
Metadata source missing from display

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#215]
The Identification section in prod contans an indication of the descriptive metadata source, e.g.,  

https://argo.stanford.edu/catalog/druid:dm447zb3969
   DRUID:   druid:dm447zb3969
   Object Type:  item
   Content Type:   file
   MD Source:   Symphony

The "MD Source" is missing in Argo dev https://argo-dev.stanford.edu/catalog/druid:dm447zb3969

**Comment by darrenleeweber** [comment]
Where is the metadata source field defined?  Where is this data stored and what transforms does it go through before it gets to the argo view?

**Comment by darrenleeweber** [comment]
There is no 'Symphony' in the Fedora Object XML, see
https://sul-dor-prod.stanford.edu/fedora/objects/druid:dm447zb3969/objectXML

**Comment by LynnMcRae** [comment]
Symphony is considered the metadata source where there is an <otherID type="catkey"> in identityMetadata. But I believe this has already been dereferenced into solr and the display gets a value from "metadata_source_ssi" to match the Metadata Source facet.

**Comment by darrenleeweber** [comment]
@LynnMcRae - can you revise your last response where it looks like a typo in `where there is an in identityMetadata`.  Seems to be missing an FoXML field identifier or something?

**Comment by LynnMcRae** [comment]
sorry, don't always remember to escape the brackets.

**Comment by darrenleeweber** [comment]
Despite reasonable efforts and much trouble shooting discussion in slack, I cannot export this druid and load it into a laptop-dev environment.  There seems to be "complex metadata object hierarchies" in this druid.  Perhaps this explains why it's not working on dev - it's not exported and loaded correctly?

**Comment by darrenleeweber** [comment]
For this druid, the identityMetadata doesn't seem to contain any information about the metadata source, i.e.
```xml
<foxml:datastream ID="identityMetadata" FEDORA_URI="info:fedora/druid:dm447zb3969/identityMetadata" STATE="A" CONTROL_GROUP="X" VERSIONABLE="false">
<foxml:datastreamVersion ID="identityMetadata.2" LABEL="Identity Metadata" CREATED="2013-03-14T12:45:56.080Z" MIMETYPE="application/xml" SIZE="381">
<foxml:xmlContent>
<identityMetadata>
  <objectId>druid:dm447zb3969</objectId>
  <objectType>item</objectType>
  <objectLabel>EEMs: Community Action Kit: Protecting Children from Exposure to Secondhand Smoke</objectLabel>
  <objectAdminClass>EEMs</objectAdminClass>
  <agreementId>druid:fn200hb6598</agreementId>
  <tag>EEM : 1.0</tag>
  <otherId name="catkey">9955838</otherId>
</identityMetadata>
</foxml:xmlContent>
</foxml:datastreamVersion>
</foxml:datastream>
```

**Comment by LynnMcRae** [comment]
Any record can be used for this ... if the object lacks a catkey then the index will contain

    "metadata_source_ssi": "DOR"

and the MD Source should display.  All objects are indexed with one or the other so I suspect argo-dev is just looking in the wrong place (a former field name).

**Comment by darrenleeweber** [comment]
Thanks.  So now let me see if I understand the situation.  When the identityMetadata/otherId[@name] is 'catkey' then the Solr index generator creates a field called `metadata_source_ssi` with a value of 'Symphony' and otherwise it has value 'DOR'.  In addition, the argo view for a druid should always display one or the other of these values (regardless of the druid type: item, collection, APO etc.).

**Comment by LynnMcRae** [comment]
Yes, and sorry for the distraction on Symphony in particular.  I understood we were caught up with the export fix in fedora, so we need to track that down separately.

**Comment by darrenleeweber** [comment]
The code appears to be using the right index field, i.e.
https://github.com/sul-dlss/argo/search?utf8=%E2%9C%93&q=metadata_source_ssi

**Comment by darrenleeweber** [comment]
Perhaps the argo-dev indexing is not complete.  I'm unclear as to whether this is a code or an index fix.  I'll check the index somehow.

**Comment by jmartin-sul** [comment]
i just grepped dor-services, and the code i found supports @LynnMcRae's above claim (as does my recollection from when we were implementing this):
https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/models/identifiable.rb#L59-L91

specifically:  https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/models/identifiable.rb#L77

so any object which is `Identifiable` should have `metadata_source_ssi` in its solr doc.

@darrenleeweber's seems like a correct summary, though i'd add (per my glance at the above code) that having an `otherId` of 'barcode' will also result in `metadata_source_ssi` being 'Symphony'.  if `otherId` is 'mdtoolkit', `metadata_source_ssi` will be 'Metadata Toolkit'.  Not sure whether there are objects that actually have that as `otherId` (in know lynn said we don't use mdtoolkit anymore, but maybe there's legacy data like that?).

FWIW, there are argo-dev items with `metadata_source_ssi` values (will post schema browser link in slack channel in a second, since it's an internal URL).  so i think this is likely a code problem.  also worth noting that "Metadata Source" appears on the facet list on argo-dev's front page (so you could use that to navigate to an item that def has the value, and you could then see from there why the value isn't being displayed in the desired place on the detail page).

**Comment by darrenleeweber** [comment]
The argo-dev index is correct, it does contain `"metadata_source_ssi": "Symphony"` in the response to https://sul-solr.stanford.edu/solr/argo_dev/select?q=id%3A%22druid%3Adm447zb3969%22&fl=metadata_source_ssi&wt=json&indent=true

**Comment by darrenleeweber** [comment]
The argo-dev logs indicate no exceptions while rendering the view.  The view code is using the wrong index field in `field_names => ["id", "objectType_ssim", "content_type_ssim", "metadata_source_ssim"]`.  Will have to track down the assignment of `field_names` to replace the "metadata_source_ssim" with "metadata_source_ssi" (unless there are more complex solr schema or other decisions involved).

**Comment by darrenleeweber** [comment]
Fix in PR https://github.com/sul-dlss/argo/pull/255
