### ISSUE TITLE
when creating a new object version, workflow timestamps for the new version sometimes overwrite timestamps for the previous version

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2192]
**Describe the bug**
The Argo item lifecycle display shows the timestamps for each milestone for each version of an object. Sometimes, when creating a new version of an object, timestamps from the new version appear to be overwritten into the timestamps of the immediately preceding version, giving an appearance that the two versions were created at the same time, or even that steps ran out of chronological order.

**User Impact**
It creates a confusing situation, especially when troubleshooting.

**To Reproduce**
I don't know of a specific way to reproduce this. Sometimes it happens when creating a new version and sometimes it does not. It seems like it's more likely to happen when the two versions are created relatively close together, such as within the same day.

**Expected behavior**
Already created versions should not change timestamps

**Screenshots**
A recent example. This collection object was accessioned twice in the same day, a few hours apart. But the timestamps are almost all the same for both versions:
https://argo.stanford.edu/view/druid:hs745tk4491
<img width="570" alt="Screen Shot 2020-07-29 at 4 15 05 PM" src="https://user-images.githubusercontent.com/8975583/88863083-bd653100-d1b6-11ea-8a50-86030273eb5b.png">

If you look at the versions in preservation, you can see that they were created hours apart:
<img width="597" alt="Screen Shot 2020-07-29 at 4 17 14 PM" src="https://user-images.githubusercontent.com/8975583/88863170-07e6ad80-d1b7-11ea-92a2-fe74a85b6a5a.png">

**Additional context**

The still-in-beta Events service, viewable with this link https://argo.stanford.edu/view/druid:hs745tk4491?beta=true , shows the correct times:

<img width="1212" alt="Screen Shot 2020-07-29 at 4 19 35 PM" src="https://user-images.githubusercontent.com/8975583/88863368-7deb1480-d1b7-11ea-9107-21418ab06964.png">

**Comment by peetucket** [comment]
Doing some looking and I suspect what is happening here is that we are reporting the `updated_at` date for the workflow step associated with the milestones, instead of the `created_at` date.  Since the `updated_at` date is automatically bumped by Rails each time you touch a row in the database, this may not be an accurate assessment for lifecycle purposes.  For example, there is a column for workflow steps that records which is the `active_version`.  If that is set to false for all previous version steps when a new version is created, this would bump the `updated_at` date for all of the rows in the old version, setting them to roughly the same time as new version (and potentially even slightly after, as in this example).  I'll do some more poking.

Example workflow step for the druid above, showing the differing dates:

```
  id: 172990901,
  druid: "druid:hs745tk4491",
  workflow: "accessionWF",
  process: "start-accession",
  status: "completed",
  error_msg: nil,
  error_txt: nil,
  attempts: 0,
  lifecycle: "submitted",
  elapsed: nil,
  version: 1,
  note: nil,
  lane_id: "default",
  created_at: Wed, 29 Jul 2020 18:17:07 UTC +00:00,
  updated_at: Wed, 29 Jul 2020 22:05:26 UTC +00:00,
  active_version: false>,
```

**Comment by peetucket** [comment]
This is where the workflow-server uses the updated_at date for milestones of created_at.  I'm not sure if this makes sense and I'd be inclined to change to use created_at instead:

https://github.com/sul-dlss/workflow-server-rails/blob/master/app/models/workflow_step.rb#L29

**Comment by peetucket** [comment]
See sul-dlss/workflow-server-rails#410 as a PR

**Comment by andrewjbtw** [comment]
Nice catch. I didn't notice those are the updated_at dates. This is a bit of a tricky one because I think all the steps are created at the same time when the accessionWF is created and then updated after each step runs. So the created_at dates might all be the same for all of the milestones. That's still more accurate than the updated_at dates though.

**Comment by peetucket** [comment]
Yes, since our robots are now pretty fast, for the first run through, `created_at` and `updated_at` should be very close together.  If you re-run an errored out step, those dates can diverge though, and using created_at will not reflect the re-run.  Not sure if this important (since it should still be obvious from the workflow view, just not the lifecycle view).

**Comment by jcoyne** [comment]
@andrewjbtw this is now resolved.
