### ISSUE TITLE
Make "Refresh MODS" a blue button

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#223]
It is currently only available as a Bulk Update but should be allowed on individual objects. It should only be present/enabled if there is a catkey (\<otherId type="catkey"> in identityMetadata). It should do to the individual record what bulk update does obviously -- fetch a new copy of MODS mapped from Symphony/MARC for the specified catkey and replace the contens of the descMetadata datastream.

**Comment by blalbrit** [comment]
per user-feedback:

I would like to be able to refresh descriptive metadata from source directly from an object record, instead of having to copy the druid, get to a search results page, click Bulk Updates, and do the refresh from there. Adding it to the blue buttons on the left-hand side would be great. This is a task that the MDU is doing with increasing frequency for objects coming in from SUL staff via the online self-deposit tool.

Arcadia Falcone

**Comment by jmartin-sul** [comment]
closed by #941
