### ISSUE TITLE
Prevent closing objects that lack a valid cocina representation

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2298]
A benefit of Cocina is that we can track the validity of an object. An object without a valid Cocina representation will hit an error in the accessionWF. Since closing a version from Argo kicks off the accessionWF, we can block the close action if the Cocina representation is not valid.

Benefits: this will leave the object in an opened state, which allows users to take all available actions to fix the issue. Once the object is closed and the accessionWF has started, some actions are blocked and it becomes harder to fix issues.

Challenge: we should show a message if the object can't close because of a Cocina model issue. The usual practice of graying out the "close" button to prevent closing is less desirable here because it does not provide any feedback on why the object can't close.

**Comment by vivnwong** [comment]
@andrewjbtw Do we have a general mechanism to show an error or warning message? Or it will need astrid's attention?

**Comment by vivnwong** [comment]
@andrewjbtw do we still need this ticket for FR? Or this is taken care in the Argo WC.

**Comment by peetucket** [comment]
Thinking about this, I believe it would be more straightforward to show a message in the UI and and disable closing in the pop-up window that appears when you click the blue "Close version" button instead of trying to disable/show a message in the item detail page itself.  This is just based on the current mechanism of how those blue buttons are enabled/disabled (which doesn't have a way to showing UI messages based on the certain conditions).  This would achieve the same outcome (prevent closing), just that you wouldn't see it on the item page until you tried to close.

**Comment by peetucket** [comment]
I've got an approach on QA working, screenshots in the PR here: https://github.com/sul-dlss/argo/pull/2672#issuecomment-819815973

See the https://github.com/sul-dlss/argo/pull/2672 for an object to test with on QA.

I also added a warning to the item show page itself since we already had all of the data loaded at the point, so it was no extra time cost.  Looks like the number of objects that are in this state is very low.
