### ISSUE TITLE
Outline tasks for implementing Argo indexing in delayed_jobs

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#231]
This feels possible, and I just wanted to outline the work as I see it:

- [ ] move `ModsulatorJob` to its own delayed_jobs queue
- [x] create a queue for indexing jobs 
    - **Question: should we also create individual queues for the indexing groups? Or just use priorities?**
- [x] Setup indexing jobs to follow the priorities outlined by @rosy1280 in https://github.com/sul-dlss/argo/issues/194#issuecomment-157513521  . Delayed jobs priority 0 is highest priority
   - 0 - Uber API
   - 1 - workflows
   - 2 - agreements
   - 3 - Hydrus Uber APO
   - 4 - All APOs (hydrus and non-hydrus)
   - 5 - collections/sets 
   - 6 - items
- [ ] Scale workers for processing?

**Question: How do we query the different priority objects?**

**Comment by drh-stanford** [comment]
The queue is where the indexer backlog comes from. That is, if there's an active workflow running, it will cause lots of reindex requests for the same druid. If the reindexing is backlogged, then we get duplicate requests for the same druid sitting in the queue. So, a heap would be a better data structure so that any reindex requests that come in don't get duplicated (you won't instead the druid if it already exists in the heap) if there's a backlog.

An example of the same druid coming in multiple times in a relatively short window:

```
[41910fb204444bf633689c538a92191d] [2015-11-19 13:51:03.006] updated index for druid:pw672rw3760
[8818292e43e3f29a3a587b54fb4ed564] [2015-11-19 13:53:34.245] updated index for druid:pw672rw3760
[31f6bd9c2e537d3adaa72ff36beb0988] [2015-11-19 13:54:06.445] updated index for druid:pw672rw3760
[23ab10c569173510d60c344185267e4e] [2015-11-19 13:54:11.385] updated index for druid:pw672rw3760
[30fb68ca4f6658ea56a5caa354c9d352] [2015-11-19 13:54:47.447] updated index for druid:pw672rw3760
[9b7781f8e33481f8153a0d1149fe6acd] [2015-11-19 13:55:17.992] updated index for druid:pw672rw3760
```

**Comment by mejackreed** [comment]
I'm not sure how to approach creating the heap structure within this context? Are the multiple index requests duplicative? Or should last win?

**Comment by LynnMcRae** [comment]
The last (or any) message should win, indexing is not cumulative and only one reindex will catch things up. 

My understanding is that the indexing task is already polling at an interval that lets duplicates accumulate per observation above about spikes in updates during workflow, and that it will pull up to 1000 messages off the queue and dedupe them for processing. I can't speak to the technical accuracy of how I've described it, but I'm pretty sure something is supposed to be there. The log above would seem to indicate that anything there is not working very well.

**Comment by tingulfsen** [comment]
Moving the existing ModsulatorJob into its own queue should be easy. I have no experience with the indexing, so I can't speak to that. However, I have found this document on Delayed Jobs best practices to be useful and informative:

http://www.sitepoint.com/delayed-jobs-best-practices/

**Comment by jmartin-sul** [comment]
a few things:
* i don't think this delayed_job batch reindexing system would replace the existing reindexing queue yet, since that queue's purpose is different (manage reindexing requests from other arbitrary applications, vs manage known chunks of bulk reindexing internally).  as such, i think it can be the caller's responsibility to not insert duplicate druids into the batch indexing mechanism.
* itql claims that queries written in it don't return result lists with duplicates.  still, if our approach ends up being that we run a query for each group of druids to be reindexed (APOs, collections, workflows, etc), we could have no duplicates within a group, but duplicates across groups seem possible.  we could either have the code that gets the query results de-dupe between lists, or we could query the jobs:  http://stackoverflow.com/questions/9589630/how-to-query-delayed-job-handler
* maybe we should also shut off the normal reindex message queuing for the solr core to which bulk indexing is being performed?  would we gain anything by leaving it on?
* i think that we want to have one queue for all the indexing jobs.  my reasoning is that jobs from different queues might be interleaved without respect to job priority.  but my hope is that jobs within the same queue will always have their priority strictly followed.  this link does seem to indicate that priority spans queues in delayed_job, but semantically, it still feels reasonable to put all the bulk reindexing in one queue:  http://edgeapi.rubyonrails.org/classes/ActiveJob/QueueAdapters.html

**Comment by mejackreed** [comment]
Just a note here:

I did look into the before hooks for ActiveJobs, and I was able to successfully use that to introspect that job. The problem here, was I wasn't able to relate the `ActiveJob` record back to the `Delayed::Job` object, and the `ActiveJob` one does not have priority information stored.

**Comment by jmartin-sul** [comment]
Besides consistency with existing Argo code and Rails in general, what benefits does ActiveJob provide vs delayed_job?  Abstraction and the ability to slot in other job queuing mechanisms if delayed_job fails to meet our needs later?

I think respecting indexing order in some shape or form is a must, and so would be a strong reason to consider using delayed_job directly (assuming delayed_job actually provides easier access to the job priority info).  Since strict priority adherence in the queuing mechanism likely would be easier all around than something like detection and manual remediation of things indexed out of order, I think that could also be an argument that the ActiveJob abstraction doesn't provide us with the level of control we need, and that if we switched off of delayed_job as a queuing mechanism, we'd likely have to re-implement something to that effect anyway (or turn it on in the new queuing mechanism's configuration), in which case ActiveJob would be providing less abstracting-details-away benefit than in other cases.

Another benefit of not using ActiveJob is that it's part of rails, and if we could keep from loading all of Rails when running delayed_job workers, we might be able to save a lot of memory and run more workers with the same computing resources (see issue #250).

So I guess I'm interested in exploring using delayed_job directly, or seeing whether we can come up with sane workarounds in ActiveJob for the limitations we've run into so far.  But its memory usage and its lack of access to priority info are significant strikes against it.

**Comment by jmartin-sul** [comment]
doesn't solve the memory usage issue with loading rails, but we could also consider activejob with a queuing mechanism underneath that met our prioritization management needs, if such a mechanism exists.

**Comment by drh-stanford** [comment]
is this issue still have work todo? i can look into the memory footprint or we can create another ticket for that...

**Comment by jmartin-sul** [comment]
probably makes sense to open up a separate ticket, since that's what we did for ordering (issue #310)
