### ISSUE TITLE
Can't fix Cocina data issues from within Argo

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2356]
**Describe the bug**
If an item lacks a valid Cocina representation, the data can no longer be fixed by editing datastreams from Argo. Any attempt to fix the data by editing a datastream will lead to an error and fail.

Additionally, it is possible to introduce invalid data when editing a datastream, thus making it possible to edit a valid object and render it invalid. Once this bad data has been added, it cannot be fixed by re-editing the datastream.

**User Impact**
Items with invalid Cocina cannot be managed. Items with valid Cocina can be rendered unmanageable if bad data is introduced.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/view/druid:bb279xs6205
2. This item lacks a title because I deleted it
3. Attempt to add a title in the descMetadata

**Expected behavior**
As long as datastreams are editable in Argo, it has to be possible to use the edit function to fix bad data. If bad data is introduced and it's possible to validate it upon submission, the validation should prevent users from submitting the bad data.

**Additional context**
This problem seems to have been introduced quite recently. Hannah reported issues this morning when attempting to add source ids to two items that lacked them.

**Comment by justinlittman** [comment]
The problem was introduced recently when we introduced authorization for updating datastreams: https://github.com/sul-dlss/argo/blob/main/app/controllers/datastreams_controller.rb#L46

Authorization requires retrieving the Cocina representation of the item. However, there are some items for which mapping from the descriptive metadata from MODS to Cocina intentionally raises an error (e.g., when there is no title).

The approach I'm going to take is stop intentionally raising an error for these data errors. Rather, these data errors will be reported to Honeybadger as other data errors.

In the future, we're going to need to introduce validation of new descriptive metadata or changes to existing metadata; however, applying validation to existing (mapped) metadata is problematic.
