### ISSUE TITLE
Bulk update is not setting citation-only rights

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2390]
**Describe the bug**
When using the Argo bulk updates interface, setting object rights to citation only is not working. The interface reports that the druids have been updated but the rights metadata is not changed.

**User Impact**
Users can only set rights to citation only one object at a time.

**To Reproduce**
1. Go to a druid (I've verified this problem is on stage)
2. Make sure the object is open
3. Go to the bulk update interface
4. Try to change rights to citation only
5. See that the rights aren't changed

**Expected behavior**
The rights should be changed to citation only

**Additional context**
The other rights settings appear to work. Only citation only is failing. Also, citation only is working on individual object pages via the blue button. Only the bulk update is failing.

**Comment by peetucket** [comment]
Confirmed on stage.  Looks to potentially be a mismatch in the values in the drop-down selector list for rights in the two pages.  Notice how it's "citation-only" in the item page (where it works) and "none" in the bulk page (where it doesn't).  I remember this cropping up in a previous bug, not sure why its fixed in one spot and not the other.

Maybe we need to use `REGISTRATION_RIGHTS_OPTIONS` in the bulk page instead of `DEFAULT_RIGHTS_OPTIONS`

see https://github.com/sul-dlss/argo/blob/main/lib/constants.rb#L7-L37 for definitions of the options
see https://github.com/sul-dlss/argo/blob/main/app/views/report/bulk.html.erb#L174 for the options set for the bulk page

On the item page where it works:

```
....
<option value="dark">Dark (Preserve Only)</option>
<option value="citation-only">Citation Only</option></select>
...
```

On the bulk edit page:

```
....
<option value="dark">Dark (Preserve Only)</option>
<option value="none">Citation Only</option></select>
...
```
