### ISSUE TITLE
Decouple apos from fedora 3

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2418]
- [x] Fetch the APO from cocina (remove call to Dor.find)
- [x] Add & Delete collections from a cocina based APO

This will likely impact both the apo_controller and the collections_controller if not others.

**Comment by jcoyne** [comment]
Also need https://github.com/sul-dlss/cocina-models/pull/212 and a mapping in DSA

**Comment by jcoyne** [comment]
>     Add & Delete collections from a cocina based APO

Can you say more about this?  Where is this happening in Argo?

**Comment by andrewjbtw** [comment]
Adding a collection to one APO and removing it from another should happen automatically when moving a collection from one APO to another. This doesn't currently happen, leading people to edit datastreams. See #2380. 

For already-existing collections, I don't think "add to APO" or "remove from APO" make sense as separate actions. Since every collection has to be under a single APO

- you can't remove it from an APO because that would conflict with the requirement to have an APO
- you can't add it to an APO because that would conflict with the requirement to have only one APO (because it already has one)

The exception is when you register and create a new collection. That new collection does need to be added to the APO it's registered under.
