### ISSUE TITLE
Provide interface for fixing version mismatch errors

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2441]
Items sometimes run into version mismatch errors during accessioning. There are a few different ways these errors can happen. In the absence of solutions that prevent mismatch errors altogether, users solve this problem by editing the versionMetadata datastream so that it contains the correct number of versions.

If the version field were editable in the Argo UI, we could stop editing the datastream.

**Comment by jcoyne** [comment]
One way this can happen is if the object is partially transferred to preservation such that it thinks that it has version 1, but it wasn't 100% successful, so the preservation workflow died.  Then if you try to repeat the workflow, it errors because preservation will be expecting v2 rather than v1 again.  In this case the fix would be to remove v1 from preservation and send it again, rather than adjust the version in DOR.

**Comment by andrewjbtw** [comment]
No longer relevant.
