### ISSUE TITLE
Remove "Access Rights Errors" facet

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2448]
this would simplify the indexer as these "errors" come from using the XML implementation of rights, and cocina has a strong schema so should prevent these errors entirely.

https://argo.stanford.edu/catalog?all=true&f%5Brights_errors_ssim%5D%5B%5D=no_discover_machine
https://argo.stanford.edu/catalog?all=true&f%5Brights_errors_ssim%5D%5B%5D=no_read_machine
https://argo.stanford.edu/catalog?all=true&f%5Brights_errors_ssim%5D%5B%5D=no_read_access
https://argo.stanford.edu/catalog?all=true&f%5Brights_errors_ssim%5D%5B%5D=no_discover_access
https://argo.stanford.edu/catalog?all=true&f%5Brights_errors_ssim%5D%5B%5D=discover_machine_unrecognized

**Comment by aaron-collier** [comment]
Requires data remediation

**Comment by jcoyne** [comment]
it looks like there are some objects (i.e. https://argo.stanford.edu/view/druid:bg908yt7861) that have:
```xml
  <access type="discover">
    <world/>
  </access>
```
when they should have
```xml
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
```

**Comment by andrewjbtw** [comment]
All of the access rights errors have been fixed. But 

- it's still possible to create new access rights errors 
- because it's possible to edit the rightsMetadata datastream
- and we don't validate what gets entered there

We have to maintain the current interface (i.e. editing XML) because there's no other interface for managing file-level access rights until we develop a new one. We can put a layer of indirection underneath the interface so that editing XML doesn't mean interacting directly with Fedora, but we can't turn the editing off.

Removing this facet won't remove the need check for valid data. In the absence of a new interface for setting file-level rights that provide validation, we could

- try to validate the XML edits at the point of input
- have some other monitoring similar to what we currently have to check for these errors, which starts to sound a lot like an "Access rights errors" facet, just not connected to Fedora.

**Comment by aaron-collier** [comment]
To ticket: Add a correctness filter (validation) in dor-services-app for rights metadata legacy api
