### ISSUE TITLE
Remediate 11 Google Books items that are not cocina compliant

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2457]
https://argo.stanford.edu/catalog?f%5Bdata_quality_ssim%5D%5B%5D=Cocina+conversion+failed&f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Google+Books

**Comment by andrewjbtw** [comment]
Blocked by https://github.com/sul-dlss/google-books/issues/653

**Comment by justinlittman** [comment]
@andrewjbtw #653 is done. Can these be purged and re-requested from Google?

**Comment by andrewjbtw** [comment]
Because of where they failed, they may have been deposited under a different druid. So we could purge and not re-request if we can verify they succeeded under different druids.

For example, these two have the same source_id and barcode:

https://argo.stanford.edu/view/druid:dk368nm0832 (failed)
https://argo.stanford.edu/view/druid:nx210kn2527 (deposited)

**Comment by andrewjbtw** [comment]
The Google Books pipeline failures seem to have two outcomes:

1. If a book doesn't make it to a certain point (accessionWF hasn't begun yet?), system will retry and might succeed
2. If a book passes that point, system will mark deposit successful and not retry, even if accessionWF errors out

The four books purged failed in mode 2, the remaining books may have failed in mode 1.
