### ISSUE TITLE
Add barcode to item registration

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2548]

**Comment by jcoyne** [comment]
Do we have a UI design for this?

**Comment by aaron-collier** [comment]
Not yet, but this isn't in ready and will be tagged.

**Comment by jcoyne** [comment]
Okay, I've added the design needed label.

**Comment by andrewjbtw** [comment]
I've learned from old documentation that in the past the "catkey" field accepted either a barcode or a catkey. If a barcode was entered, it would be used to pull the catkey too. If the catkey was entered, it would just do what it does now.

Could that be made to work again? We could relabel the form field to something more generic than "catkey" but being able to enter just the barcode and get both barcode and catkey would be preferable to adding one more column. It would also reduce the chance that someone entered a barcode that does not match the catkey they entered separately.

However, there may have been good reason to remove the barcode option, so maybe using barcode to retrieve catkey can't be done reliably. I think Google Books is retrieving catkeys based on barcodes, though.

**Comment by astridu** [comment]
Add a column after catkey for barcode.
![Uploading image.png…]()

**Comment by andrewjbtw** [comment]
Re: my comment above about pulling the catkey from the barcode, after thinking it over it seems safer to make barcode its own field on the form.

**Comment by andrewjbtw** [comment]
@astridu sorry to change my mind right away, but could we switch things so that "Barcode" is to the left of "Catkey"?

I've been thinking about the problem of existing workflows, where people paste in data to the registration form from their own spreadsheets. If we add Barcode to the right of Catkey, they'll need to insert a column into the middle of their spreadsheets to make everything line up. But if we put Barcode on the left, they'll still need to add the column to the left, but at least it will leave the existing column spacing intact for everything to the right.

Either way, I'll need to be clear about communicating this change to the form when it goes out so that people don't accidentally put their data in the wrong fields.

**Comment by astridu** [comment]
No worries. I updated the mockup.
![image](https://user-images.githubusercontent.com/42216982/112544245-01bfc580-8d74-11eb-886a-b845ad8e8cbe.png)
