### ISSUE TITLE
Integration tests fail on main branch

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2683]
```
ber spec/features/create_object_no_files_spec.rb:14

Use Argo to create an object without any files
  is expected to have text "closing version for integration testing" (FAILED - 1)

```

This causes the second version to error with 
```
sdr-ingest-transfer : problem with sdr-ingest-transfer (BackgroundJob: 218860): {:errors=>[{:title=>"Preservation error", :detail=>"Version mismatch in /dor/workspace/yr/396/gs/4656/yr396gs4656/metadata/versionMetadata.xml, expected 1, found 2"}]} 
```
For example: https://argo-stage.stanford.edu/view/druid:yr396gs4656

A further bit of context was that https://github.com/sul-dlss/infrastructure-integration-test/commit/f18c6374092d41a2b81f831e1f26cd0674dba1f5 was just added a few days ago.

**Comment by peetucket** [comment]
FYI, this test passed as of 4/6/2021 on -stage with `main` branch deployed...so it's either intermittent or with something other than what's currently on main

**Comment by jcoyne** [comment]
The test is new as of 4/14

**Comment by ndushay** [comment]
This test was added by PR #234 to address ticket #233, which was at Andrew's request.   

In the infradev meeting that can't seem to get scheduled soon, there is a discussion item about how we can use automated tests to 
- ensure fewer production breakages (requested by Andrew)
- take some of the testing burden off Andrew

If it is failing on qa, it is perhaps because qa isn't set up properly,  as it does pass on stage.  Perhaps it has to do with preservation qa boxes and/or the communications to and from them.

**Comment by jcoyne** [comment]
@ndushay this problem was reported on stage.  I didn't evaluate it on QA.

**Comment by jcoyne** [comment]
This passed for me today, so perhaps this is just a intermittent problem with preservation catalog. 🤷
