### ISSUE TITLE
Unable to change source id on collection

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2727]
It is possible to create a collection without a source id.  Then if you click "Change source id" it results in an error:

<img width="1155" alt="Screen Shot 2021-04-28 at 10 13 49 PM" src="https://user-images.githubusercontent.com/92044/116498361-2f19fa80-a86f-11eb-9d32-6eb0194f1661.png">
https://app.honeybadger.io/projects/49894/faults/78981903

**Comment by andrewjbtw** [comment]
I think only Hydrus collections get source ids and those are assigned automatically. There's no field for source id when you create a collection and there shouldn't be one because it's not required. Collections are conceptual, source ids are meant to link to the real world. 

I suppose it should be possible to change a collection source id if it's in the interface but I don't know what the use case for that would be.

**Comment by peetucket** [comment]
Based on Andrew's comment, if there isn't a use case for updating a sourceID of a collection, I think it would be straightforward to just disable this button on any collection detail page.  Does that make sense?

**Comment by andrewjbtw** [comment]
That makes sense to me. If we find someone needs to update, we can revisit when we understand what their goal is in changing it.
