### ISSUE TITLE
Prevent ChecksumReportJob from being run on registered druids

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2784]
If you run this job on a registered (non-accessioned) object you get this unhandled error:  
https://app.honeybadger.io/projects/49894/faults/65257643

We should check that the item is accessioned before asking preservation catalog about it.

**Comment by peetucket** [comment]
It appears we actually do catch the exception for a druid that isn't in Preservation yet and continue with the job, but then deliberately throw a 409 in the response if we discover missing objects.  Perhaps we just want to change this behavior, and allow the response to come back (or include the missing druid in the output CSV with a message).

Here is the call from argo to preservation-client:

https://github.com/sul-dlss/argo/blob/main/app/jobs/checksum_report_job.rb#L23

The client makes the call to preservation_catalog:

https://github.com/sul-dlss/preservation_catalog/blob/main/app/controllers/objects_controller.rb#L64-L83

You can see that the `generate_checksum_list` method already catches the exception from `MoabStorageService` (called from https://github.com/sul-dlss/preservation_catalog/blob/main/app/controllers/objects_controller.rb#L165-L169):

https://github.com/sul-dlss/preservation_catalog/blob/main/app/controllers/objects_controller.rb#L145

It then adds that druid to the `missing_druids` array.  But then at the end of the call, we throw a 409 if there is any data in there.  We could instead only throw a 409 if there is another exception instead of for missing druids too so that at least the user gets the rest of the report out and we don't go to HB.

**Comment by peetucket** [comment]
@andrewjbtw  do you think it makes sense to just allow the checksum job to return even if there are missing druids?  we could include the missing druid in the output with just a blank set of checksums to make it clear it was not found (likely due to accessioning not yet complete)

**Comment by andrewjbtw** [comment]
That sounds good to me. Will the log file also indicate that the druid wasn't found? Just in case someone wonders about the missing druid.

**Comment by peetucket** [comment]
My reading of the argo code leads me to believe it will not be in the log, but the missing druid will definitely be in the response with a message indicating it was not found.  

Something like this example from our tests for an output CSV file (the `xx123yy9999` was not found):

```
bj102hs9687,eric-smith-dissertation.pdf,aead2f6f734355c59af2d5b2689e4fb3,22dc6464e25dc9a7d600b1de6e3848bf63970595,e49957d53fb2a46e3652f4d399bd14d019600cf496b98d11ebcdf2d10a8ffd2f,1000217
bj102hs9687,eric-smith-dissertation-augmented.pdf,93802f1a639bc9215c6336ff5575ee22,32f7129a81830004f0360424525f066972865221,a67276820853ddd839ba614133f1acd7330ece13f1082315d40219bed10009de,905566
xx123yy9999,object not found or not fully accessioned
```

**Comment by andrewjbtw** [comment]
Ah, in that case it's still clear what happened. I thought it might just show up with blank cells after the druid.

**Comment by peetucket** [comment]
I deployed the branch to stage and verified this behavior with these two druids (one of which was not fully accessioned, the other which was).  The log file didn't report any errors but the output showed you what was happening.  I suggest we try this approach given it's simplicity and see if any more work is needed.

```
druid:bb131xs4563
druid:bb041bm1345
```

**Comment by andrewjbtw** [comment]
Looks good to me.
