### ISSUE TITLE
Bulk action "populate from previous search" button sometimes returns unexpected results

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2792]
**Describe the bug**

Reported from the argo-feedback mailing list:

>I've been encountering this bug with Argo lately, and I wondered if it's a known issue:
>
>I'll search a set of druids by catkey and click the white Bulk Action button to start a new bulk action.  I'll select my job type (usually either downloading descMD or opening/closing versions) and click "Populate with previous search", hoping to get the druid from the catkey I just searched.  However, it frequently populates this field with druids from whatever my "second to last" search was.  For example, this morning I looked up the Conrad Collection APO tag, and later for an unrelated task, I searched catkey 11756419 to download the descMD for those items.  When I clicked "populate with previous search" in the Bulk Action screen, it populated the field with the Conrad Collection druids.

**Additional background**

Argo has a feature that allows users to start a bulk action by clicking on the "Bulk Action" button near the top of a search results page:

![Screen Shot 2021-08-03 at 4 26 55 PM](https://user-images.githubusercontent.com/8975583/128098963-98698b34-6727-4d1f-87cd-5735ce1312db.png)

Clicking on this button takes the user to a page that lists all of their bulk actions. From that page, they can click on a link to start a new bulk action. On the new bulk action page, they then have the choice to click on a button to populate the input box with the list of druids from their previous search:

![Screen Shot 2021-08-03 at 4 26 09 PM](https://user-images.githubusercontent.com/8975583/128099055-d9c63c9d-d38e-40f8-8a68-c45d8ef4c21f.png)

Usually, this button will return the list of druids from the previous search. But under some circumstances the button returns a list of druids matching one of the user's older searches, not the most recent one. This happens even when clicking the exact sequence above to arrive at the bulk action directly from the most recent search result: search results --> bulk action button --> new bulk action --> populate with previous search

**User Impact**
If a user is given the wrong druid list, they may apply updates to the wrong set of druids. It can be difficult to tell from a list of druids that you are not seeing the correct druids.

**To Reproduce**

I've reproduced this but it's been difficult to pin down exactly what set of steps leads to it. Here is what I've done, all within a single browser tab starting with a new browser session:

1. Go to Argo
2. Run a search or click on a facet
3. Go to a new bulk action and check the druid list
4. Repeat this process
5. Eventually see that the druids being returned from the search are not the correct ones

One possibility is that the "populate from previous search" stops working once the number of searches has exceeded a certain amount, with additional searches not being recorded as the most recent one. The most recent time I reproduced this issue, I kept getting the same druid list even after running multiple additional searches.

To reduce the possibility of multiple browser tabs being the cause of the issue, I tested doing all of my Argo activity in a single browser tab and was able to reproduce the error under these conditions.

**Expected behavior**
When launching a bulk action from a list of search results, the bulk action should be able to populate the druid list from that set of search results.

It is possible to launch a bulk action independently (i.e. not from a results list) by launching it from the menu on the top red bar. I don't think we can easily determine what the "most recent" search was in this situation, so I wouldn't necessarily expect a bulk action launched independently to return the "correct" druid list. If we can have it return the most recent search (based on timestamp?), that would be great but not essential. I would expect people to run a search before using it to generate a bulk action druid list.

**Additional context**
I've been using Firefox and the user who reported this is on Chrome (both of us on MacOSes), so it seems like it's not a browser-specific issue.

Note also that the "bulk update" equivalent action to populate from a previous search seems to work correctly all the time. But I think the bulk updates may use a different method of generating the druid list.

**Comment by vivnwong** [comment]
@peetucket can you pair with @andrewjbtw for an assessment of this bug?

**Comment by peetucket** [comment]
Sure.  I started having a look this morning to see if there was anything quick to fix (there wasn't), but happy to pair with Andrew.

**Comment by peetucket** [comment]
Ok, I have done some archeology.   What I've found:

* Bulk Actions and Bulk Update use two different methods of populating pids
* When you execute a search, there are querystring parameters passed to the search result page that describe what you have searched on and that are used by Blacklight to construct the solr query.  The search is also stored in a database table called "Search".
* If you click on the "Bulk Update" button from the search results page, that button passes on the querystring parameters to the bulk update page (e.g. it looks something like this: https://argo.stanford.edu/report/bulk?f%5BobjectType_ssim%5D%5B%5D=collection&q=test&search_field=text) ... if you click on "Bulk Actions" button from the search results page, it does **not** pass on the query string parameters (e.g. it looks plain: https://argo.stanford.edu/bulk_actions)
* So here is how they work differently:
*  For "Bulk Update", when you click the "Get Druids From Search" button, it uses the params that have been passed to the page and then it makes an Ajax call out the Reports controller asking for PIDs for that search, to here: https://github.com/sul-dlss/argo/blob/main/app/controllers/report_controller.rb#L37-L48   This then uses the report class to execute a query against solr using those params: https://github.com/sul-dlss/argo/blob/main/app/models/report.rb  The controller formats the results as JSON, returns to some custom javascript on the Bulk Update page, which then fills in the box.
* For "Bulk Actions", we use the search history stored in the user session, and then go to the database to fetch the parameters.  This is appealing because we don't have to keep passing querystring parameters along.  It also means we can populate druids from the previous search even if we navigate to the Bulk Actions from the top navigation bar instead of via the button on the search results page (again, because we don't need to have querystring parameters embedded in the link, we utilize the user session to find the previous search id, then go to the database to figure out what the parameters were).  You can see this here:  https://github.com/sul-dlss/argo/blob/main/app/controllers/bulk_actions_controller.rb#L14-L17
* Note that in this code, `searches_from_history` is a Blacklight method that digs into user's history and returns the search: https://github.com/projectblacklight/blacklight/blob/c310fc8cb07635cac8e2474b1afa9fafdb6c89de/app/controllers/concerns/blacklight/controller.rb#L105-L107
* You can see in Blacklight where new searches are appended to the history: https://github.com/projectblacklight/blacklight/blob/c310fc8cb07635cac8e2474b1afa9fafdb6c89de/app/controllers/concerns/blacklight/search_context.rb#L94-L102   
* Note that there are a maximum number of searches that Blacklight will store: `blacklight_config.search_history_window`.  This defaults to 100 and we don't override in Argo: https://github.com/projectblacklight/blacklight/blob/71b5061841f25ca133ae8a288c38e0ded795d589/lib/blacklight/configuration.rb#L133
* Note also the search history in the session will go away if you close your browser or otherwise reset the session (though it is then reasonable that the user should not expect a previous search to populate after doing this).
* Also note that we rely on old searches not being cleared out of the database.  There is a facility to do this cleanup in Blacklight those it does not appear to be used in Argo, and we have search histories in the production Argo database going back one year now: https://github.com/projectblacklight/blacklight/blob/c310fc8cb07635cac8e2474b1afa9fafdb6c89de/lib/railties/blacklight.rake#L7-L12

So it is plausible that the bulk action method of using search history is running into problems when more than 100 searches are in the history.  We also do something odd in Argo, which is that we return the first item in the search history  if there is currently no search history present for the user: https://github.com/sul-dlss/argo/blob/main/app/controllers/bulk_actions_controller.rb#L16  That doesn't make sense to me.

Now, we could ask why we don't do the Bulk Action search the same way we do the Bulk Update search, and we possibly could, but that Bulk Update search code involves passing querystring parameters around and some custom Javascript which is a bit janky.

**Comment by peetucket** [comment]
@andrewjbtw just pinging to see if this is still an issue and if we should consider looking into it again

**Comment by mjgiarlo** [comment]
I wonder if our friends on the @sul-dlss/access-team might have seen anything like this before. (Thinking of SearchWorks. And maybe Exhibits?)

**Comment by peetucket** [comment]
From Justin Coyne: ... we are using cookie session store and the search history is stored by blacklight in the session (and thus a client side cookie), with cookies set per domain, so the load balancer (argo.stanford.edu) will maintain separate cookies from each individual node behind it.  This may explain why going to each node will show a separate search history, but doesn't explain the problematic behavior on the ticket.

```
14:25 $ bin/rails c
Running via Spring preloader in process 75571
Loading development environment (Rails 6.1.4.6)
[1] pry(main)> Rails.application.config.session_store
=> ActionDispatch::Session::CookieStore
```

**Comment by jcoyne** [comment]
To be clear it's not the load balancer that maintains the cookies, it's your web browser. You have a separate argo_session cookie for each domain that you connect to.
