### ISSUE TITLE
When a user is in too many workgroups, the user can't view Bulk action new page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#2794]
Andrew goes to https://argo.stanford.edu/bulk_actions/new and gets the library status page because an error occurred.
It works for other people.  Suspect due to Andrew's workgroup membership being large.

Slack thread: https://stanfordlib.slack.com/archives/C09M7P91R/p1628200332093000

Part of code that generates the big query based on workgroups: https://github.com/sul-dlss/argo/blob/93e5c01978afb6589b44d8fd6348845d15614798/app/helpers/registration_helper.rb#L11

See https://github.com/sul-dlss/argo/issues/321 for a previous related instance of this.

See HB alert: https://app.honeybadger.io/projects/49894/faults/80745410

Tried the fix in https://github.com/projectblacklight/blacklight/issues/1324 here: https://github.com/sul-dlss/argo/pull/2793 but it didn't have an effect.

**Comment by andrewjbtw** [comment]
On the theory that a recent change pushed my workgroup list over the limit, I took myself out of a few groups where I'm both a member and an administrator (so that I can re-add myself later). This didn't have an effect. But maybe it's not just workgroup membership but workgroup administrator status too?

On the impersonate page, Argo lists all the workgroups it says I'm in. Here's a snippet:

<img width="450" alt="Screen Shot 2021-08-05 at 5 46 38 PM" src="https://user-images.githubusercontent.com/8975583/128439079-2bd6d160-b9a2-4473-9923-db0ccab9bd91.png">

The list includes a lot of workgroups that end with "/administrator". In many of those cases, I'm not actually a member of the workgroup, just the administrator by virtue of being administrator of all workgroups that start with "sdr:". Someone recently created a new "sdr:" workgroup, which might have put my workgroup list over the limit. I have no control over being automatically made an admin on these workgroups. I think there are actually 5 of us who could be in this situation, since we're all members of an umbrella sdr-owners workgroup that admins all sdr: workgroups.

If the "/administrator" workgroups don't have an effect on Argo permissions, could the permissions query exclude them and only use workgroup membership? There would still be a workgroup membership limit but it would take longer to get there.
