### ISSUE TITLE
Virtual objects CSV should support removing all virtual object relationships

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2821]
**Describe the bug**
The Create Virtual Objects bulk action takes a CSV where each row usually follows the pattern

```
parent,child01,child02,...
```
The first druid is always the druid for the whole virtual object, remaining druids on the row are then linked to it as constituents.

To remove this virtual object relationship, it should be possible to submit only a single druid in a row. This is a signal that all existing virtual object relationships for that druid (and its constituents) should be removed.

Currently, when trying to remove a virtual object relationship by submitting only a single druid, the job ran into the following error:

https://app.honeybadger.io/projects/49894/faults/81745726

**User Impact**
It's not possibly to use the bulk action to remove a virtual object relationship when one has been created erroneously. XML editing is required to fully remove the relationships. 

**To Reproduce**
1. Go to Bulk Actions -> New
2. Submit a CSV with only a single druid
3. See the error in the back end. In Argo it looks like the job is running, but it will retry in sidekiq and send an error to honeybadger.

**Expected behavior**
Submitting only a single druid should remove the existing virtual object relationships for that druid.

**Additional context**
As a workaround, you can reduce the size of the virtual object by supplying only one constitutent druid. The result will be a virtual object that consists of that one druid. Then you can manually remove the rest of the virtual object relationships by editing the XML for those druids (the RELS-EXT of the constituent and the contentMetadata of the virtual object). We'll need to make sure we've implemented a non-Fedora way to unlink virtual object relationships when we do the full decoupling.

**Comment by mjgiarlo** [comment]
FR signing off for the week. Did not have enough time to push this along so dropping some notes here. I think supporting this involves changes to dor-services-app, dor-services-client, and argo:

* dor-services-app
  *  Add a new endpoint for deleting virtual objects (instead of cramming this functionality into the virt obj creation endpoint). Will require editing the openapi.yml, too.
* dor-services-client
  * Once the DSA endpoint is out there, add support for it in DSC, and cut a new minor release
* argo
  * Bump DSC and add the ability to destroy in addition to create virtual objects. I'd probably copy/paste the existing service classes and adapt them but it could be we also want a separate, dedicated bulk action (+ new job) for deletion for UX purposes? (Because the logging in particular may be messy, or confusing, with both concerns in one place.)

Moving back to needs-triage column (heads-up @vivnwong)

**Comment by andrewjbtw** [comment]
@mjgiarlo do you think this should wait on your Cocinize work at this point? I think it's ready in terms of what the goal is (being able to remove a virtual object relationship) but I can put it in the backlog if the other work is now blocking it.

**Comment by mjgiarlo** [comment]
@andrewjbtw yes, I do think it should wait on the Cocinization. Thank you for asking!

**Comment by andrewjbtw** [comment]
Ok, I moved it out of ready.

**Comment by andrewjbtw** [comment]
@mjgiarlo this ticket was blocked by Cocina-ization. Are you aware of any remaining blockers to putting this back into ready?

**Comment by mjgiarlo** [comment]
@andrewjbtw nothing comes to mind, nope.
