### ISSUE TITLE
Download CSV of structural metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2888]
See https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/444556663/comments
The link is "Download CSV" In the "Content" section

The format of this CSV file will be specified by @andrewjbtw

**Comment by jcoyne** [comment]
@vivnwong did you close this intentionally?

**Comment by vivnwong** [comment]
No, I accidentally click somewhere on the page. I must have click the close the button without knowing it.

**Comment by andrewjbtw** [comment]
The CSV should provide the following values from the structural metadata. The goal is to provide a CSV with the current data that can then be edited and uploaded with values to change.

Note that because Cocina is hierarchical, some cells will repeat. I'm not sure there's much we can do about that as long as we use a CSV, but a CSV seems like an easier to edit and understand format than JSON for this purpose.

The header should contain all the user-editable fields:
`resource_label,resource_type,sequence,filename,file_label,publish,shelve,preserve,rights_access,rights_download,mimetype,role,thumb`

Column descriptions:

- resource_label: the label for the whole resource (not to be confused with the object label)
- resource_type: the resource type (not to be confused with the content type)
- sequence: the sequence number used to group files within resources - each file with the same "sequence" number belongs in the same resource
  - Note: this value may need to be inferred from the ordering within the data, if Cocina does not store sequence numbers
- filename: the name of the file
- file_label: a human-readable label for the file
  - note: this is not part of Fedora model so not currently used or displayed on Purl
- publish: yes/no - whether to list the file on the Purl (in the public XML)
- shelve: yes/no - whether to send the file to Stacks
- preserve: yes/no - whether to send the file to preservation
- rights_access: the access right for the file
- rights_download: the download right for the file
- mimetype: the mimetype of the file
- role: the role of the file (such as "transcription" for OCR)
  - note: optional, leave blank if not present 
- thumb: yes/no - whether a particular image should be used as a thumbnail
  - note: it is not clear if this value is used anywhere, intent seems to be to allow users to choose a page in a book to be a thumbnail
