### ISSUE TITLE
Move object-level access to multi-select design

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2967]
![Screen Shot 2022-01-13 at 4.26.36 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/7ebfdddd-7bca-4614-8fbe-f4c1c92c9515)

"Download" can't offer a higher level of access than the "access field".  Can't have download: world and access: stanford.

**Comment by andrewjbtw** [comment]
It should be possible to reach all possible object-level Cocina rights settings with the following two-menu design:

| view | download |
| -- | --
| world | world
| stanford | stanford
| cdl | none
| location: ars | location: ars
| location: art | location: art
| location: hoover | location: hoover
| location: m&m | location: m&m
| location: music | location: music
| location: spec | location: spec
| citation-only |  
| dark |  

Moving to this design would enable users to enter all possible object-level rights without editing XML. In the current one-menu design, certain rights can only be set via XML editing. Examples of these cases include:

- adding no-download settings to location-based rights
- combinations like "stanford, world (no-download)", where Stanford users can download but everyone else can only view

This rights menu should take the place of the current rights menu in all places where it appears:

- item show pages
- bulk rights update
- APO default object rights

Note that this menu should only apply to object-level rights. File-level rights have different requirements because certain settings do not apply to the file level, such as "citation".

**Comment by andrewjbtw** [comment]
To see how these combinations map to the full cocina access values, see the [SDR rights spreadsheet](https://docs.google.com/spreadsheets/d/1BesuZ3iqouFMaur79A61Uq4ewsHQc4I0w1fRBQoYugk/edit#gid=998877965). I've added two columns to the beginning of the spreadsheet to show the Argo menu values for each valid rights setting.

We do need to prevent people from selecting invalid combinations. For example, you cannot make the download less restricted than the view. For example:
```
download: world
view: stanford
```
should be prohibited. I think the model will enforce this in the validation but the UI either needs to prevent invalid selections from being made by adjusting the menu choices interactively or it needs to show a message when an attempt to make an invalid combination is saved.

**Comment by andrewjbtw** [comment]
I've filed individual tickets for each of the places where the access rights menu appears.

**Comment by andrewjbtw** [comment]
Update: we're trialing a three-selection menu owing to the difficult of enforcing only the valid combinations with the two-menu design.

**Comment by andrewjbtw** [comment]
One way I can think of to incorporate CDL without adding something like a checkbox or other option would be to put it into the view menu, if it can be tied to the one valid Cocina we currently have for CDL, which is 

- view: stanford
- download: none
- controlledDigitalLending: TRUE

If that's possible, then the download menu should only show "none" if CDL is selected.

**Comment by andrewjbtw** [comment]
If we can't control the menus like that, Astrid and I will add a design for a message to show when someone tries to save an invalid combination.

**Comment by jcoyne** [comment]
@andrewjbtw https://github.com/sul-dlss/argo/pull/3217 is ready for testing whenever you have the time.
