### ISSUE TITLE
(new Argo interface): show "none" on the license menu

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3020]
The new Argo interface shows a license menu for all items and collections. This menu should include the "none" option, which means an item isn't assigned a license at all. Currently, that option is not listed on the menu:

<img width="683" alt="Screen Shot 2022-01-27 at 11 03 51 PM" src="https://user-images.githubusercontent.com/8975583/151502965-7f3160c8-49db-4007-9a4e-29a3ac93cd66.png">

Without the "none" option, it isn't possible to remove a license from an item.

**Comment by mjgiarlo** [comment]
Briefly looked into this between rounds of testing other PRs and decided to concentrate on testing current work. Adding `[['-- No license --', ''] +` to the `ItemsHelper` is easy enough, but this work *may* require cocina-models work. See here: https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L918-L951 Cocina yelled at me when trying to nullify an existing license because the OpenAPI spec does not appear to allow nullable licenses for either collections or DROs (it does for APO default access tho). Whoever picks up this ticket may want to look into that further.

**Comment by andrewjbtw** [comment]
What's the status of this issue? I'm not sure a fix has been deployed previously for testing and I don't see "none" in the show page menus, just the APO edit menu.

**Comment by mjgiarlo** [comment]
@andrewjbtw There's a draft PR not yet merged.
