### ISSUE TITLE
APO "default object rights" should use the same "access rights" value that items display

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3121]
On the APO show page, the access rights value should display the same value that an item would display, given those access rights. Currently, the value showing in the APO seems to be the Cocina "access" value.

<img width="435" alt="Screen Shot 2022-02-16 at 1 07 10 PM" src="https://user-images.githubusercontent.com/8975583/154357542-0ee21392-cdbf-4c6c-b7f7-8b4ee7dd7f40.png">

For consistency, the value on the APO page and the value on the item show page should follow the same display rules. The goal of showing this value (previously only visible in the XML or the Edit form) is to show people exactly what items that apply these defaults will look like. 

Later in this workcycle we will be updating the rights menu to handle the more complex Cocina rights model. At that point, I'd like to make sure we update the APO page and the item page at the same time.

**Comment by andrewjbtw** [comment]
APO example from the screenshot here: https://argo-stage.stanford.edu/view/druid:sc012gz0974

I think this should be showing "location: spec" based on the rightsMetadata/Cocina

**Comment by peetucket** [comment]
So I started working on this, and I don't think this is actually that straightforward (unless I am missing something).

The issue is that (as you noted), the "default rights" value that is displayed for APOs in Argo is pulled straight from the cocina value model, but the "rights" value that is displayed for Items is pulled from solr, where it is computed in dor-indexing-app (so you can end up with something like "location - spec").  The APO doesn't have this derived value in Solr for default object rights.

Item rights view showing it pulled from Solr for items: 

https://github.com/sul-dlss/argo/blob/main/app/components/show/access_rights_component.rb#L11
https://github.com/sul-dlss/argo/blob/main/app/components/show/access_rights_component.html.erb

And default objects rights for APOs:

https://github.com/sul-dlss/argo/blob/main/app/components/show/apo/default_object_rights_component.rb#L7-L15
https://github.com/sul-dlss/argo/blob/main/app/components/show/apo/default_object_rights_component.html.erb#L7

The solr field being indexed to that is used for item display (and referenced above in the component):
https://github.com/sul-dlss/argo/blob/main/app/models/solr_document.rb#L32
https://github.com/sul-dlss/argo/blob/main/app/models/solr_document.rb#L68

And the indexing code that derives this for items and places into solr:

https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/rights_metadata_indexer.rb#L18
https://github.com/sul-dlss/dor_indexing_app/blob/main/app/services/rights_description_builder.rb

**Comment by peetucket** [comment]
So perhaps we need to derive this same thing for APOs, index into solr and show in the saw way?

**Comment by andrewjbtw** [comment]
I think we need to either do that or take the default object rights display out of the APO show page (so it doesn't hold up the release) until we're ready to show the rights in a new Cocina-based way. I didn't realize this wasn't already set up to follow the item rights indexing.

I have an idea for a new way of displaying complex rights that uses two fields: "View" and "Download". But it's not ready to go and I haven't ticketed it yet.

**Comment by jcoyne** [comment]
Let's take the default rights out of the display for now, so that we can avoid holding this up.

**Comment by andrewjbtw** [comment]
Works for me.

**Comment by peetucket** [comment]
Ok, will do. I'm taking a quick stab on the indexer, but I suspect it's not going to be a quick merge even if the work isnt' too hard.  

Note that if we index into the same `rights_descriptions_ssim` field for APOs (what I am taking a stab it), it will show up in the existing "Overview" section on the APO page.

![Screen Shot 2022-02-16 at 4.05.23 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/f043673c-2558-400f-bb1e-8b2d442e2b24)

**Comment by andrewjbtw** [comment]
The APO itself has access rights that should display - but are always set to dark.

**Comment by andrewjbtw** [comment]
But apparently are blank? I didn't even notice that until now. I'm not concerned about the rights on the APO itself for the release since no one should be changing them anyway. We could consider not allowing edits on that field for APOs.

**Comment by peetucket** [comment]
Yeah, it's blank cause nothing is indexed into that solr field for APOs.  We can index "dark" for all APOs in that existing field to get it to show correctly, and then index the default object rights into a new solr field for correct display for APOs.

**Comment by jcoyne** [comment]
@peetucket I don't think we should reuse that Solr field for "default access", that is for "access to this object"

**Comment by peetucket** [comment]
Yup, sounds like `rights_descriptions_ssim` can be "Dark" for all APOs, and `default_rights_descriptions_ssim` can be a new field that has derived default object rights for display for just APOs.
