### ISSUE TITLE
Impersonate UI issues

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#337]
General problems ... odd page layout (should it be a modal?) jammed to the left margin, inadequate input space, the label "Current Groups" should be "Sample person and group references" (I think it's just a sample so folks know the syntax) ...

![screen shot 2015-12-10 at 9 49 15 am](https://cloud.githubusercontent.com/assets/1824732/11723445/570d5bf0-9f23-11e5-8631-7a310567b079.png)

Display of information afterward could be improved (though not critical for the audience involved)

![screen shot 2015-12-10 at 9 54 49 am](https://cloud.githubusercontent.com/assets/1824732/11723616/2e0a04d2-9f24-11e5-8aed-75d1dfe8f8a4.png)

![screen shot 2015-12-10 at 9 54 18 am](https://cloud.githubusercontent.com/assets/1824732/11723621/32a511da-9f24-11e5-8403-31f28f539616.png)

**Comment by jmartin-sul** [comment]
totally agreed that the input space is inadequate.  would be nice if it were a text area that accepted any whitespace as the delimiter, so you could enter a few groups on a line, or a longer list broken into separate lines.

i like the current behavior of listing the actual groups for the logged in user.  nice to see what argo thinks that is, at a glance.  or maybe that should be a separate info page, since it's useful to a more general audience than the small set of people who can impersonate (i.e. super users).  i can also see how it'd be useful to have a standard example list for all users.

**Comment by LynnMcRae** [comment]
ah, the "Current groups" are my current groups! It looked like it might have been a list of the standard set.  Maybe call it "Your current groups" since I mistook it?

**Comment by jmartin-sul** [comment]
"Your current groups" does seem like clearer/better wording.
