### ISSUE TITLE
Order columns in descriptive spreadsheet download similar to replayable spreadsheet

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3399]
The headers in the descriptive metadata spreadsheet download should appear in the following order:
druid
sourceId
title
contributor
form
event
language
note
identifier
access
subject
relatedResource
adminMetadata
geographic
marcEncodedData
valueAt

This order is similar to the replayable spreadsheet and thus will be more familiar to users.

**Comment by lwrubel** [comment]
@arcadiafalcone I wanted to confirm I understand the desired order, since in many cases, there is nested data and more than one of a top-level field. For example, in a descriptive metadata spreadsheet I downloaded from stage, here are the fields starting with `title`:

```
title1:note1:type
title1:note1:value
title1:status
title1:structuredValue1:type
title1:structuredValue1:value
title1:structuredValue2:type
title1:structuredValue2:value
title1:structuredValue3:type
title1:structuredValue3:value
title1:value
title2:displayLabel
title2:structuredValue1:type
title2:structuredValue1:value
title2:structuredValue2:structuredValue1:type
title2:structuredValue2:structuredValue1:value
title2:structuredValue2:structuredValue2:type
title2:structuredValue2:structuredValue2:value
title2:structuredValue2:type
title2:structuredValue2:uri
title2:structuredValue2:value
title2:type
title2:value
title3:type
title3:value
```

Would the idea be to put all of the titles together (as above), then contributors, then forms, etc?

**Comment by arcadiafalcone** [comment]
@lwrubel Yes, exactly.

**Comment by lwrubel** [comment]
@arcadiafalcone where should the purl appear in the order?

**Comment by arcadiafalcone** [comment]
Please put it after access.
