### ISSUE TITLE
Spreadsheet upload: Error message for contributor.name.parallelValue.structuredValue.value

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3470]
`Line 5: #/components/schemas/Contributor does not allow null values for druid:nb406th1306 (2022-04-12 22:47:00 UTC)`
[spreadsheet_upload_test.xlsx](https://github.com/sul-dlss/argo/files/8476998/spreadsheet_upload_test.xlsx)

**Comment by justinlittman** [comment]
@arcadiafalcone Can you provide more info on this ticket?

**Comment by aaron-collier** [comment]
From what I can tell, initially, this is caused for these particular items because the upload spread sheet has:
```
contributor3.name1.parallelValue1.structuredValue1.value
contributor3.name1.parallelValue1.structuredValue1.type
contributor3.name1.parallelValue1.structuredValue2.value
contributor3.name1.parallelValue1.structuredValue2.type
contributor3.name1.parallelValue2.structuredValue1.value
contributor3.name1.parallelValue2.structuredValue1.type
contributor3.name1.parallelValue2.structuredValue2.value
contributor3.name1.parallelValue2.structuredValue2.type
```

But if I update the spreadsheet to use:

```
contributor1.name1.parallelValue1.structuredValue1.value
contributor1.name1.parallelValue1.structuredValue1.type
contributor1.name1.parallelValue1.structuredValue2.value
contributor1.name1.parallelValue1.structuredValue2.type
contributor1.name1.parallelValue2.structuredValue1.value
contributor1.name1.parallelValue2.structuredValue1.type
contributor1.name1.parallelValue2.structuredValue2.value
contributor1.name1.parallelValue2.structuredValue2.type
```

The update runs successfully. So it seems that we cannot (currently) update with contributor>1 if contributor1 is blank.

@arcadiafalcone / @andrewjbtw thoughts on the desired outcome here? I haven't gone too deep into the code, but I suspect it may be challenging to have the code move >1 into 1 if it's missing.

**Comment by arcadiafalcone** [comment]
This is a problem because contributor1 might have a different path between name and value. So if there are both contributor1.name1.value and contributor2.name1.structuredValue1.value, and one row has only a value contributor and another row has only a structuredValue contributor, they can't be entered in the same column.
