### ISSUE TITLE
For descriptive file upload, display validation errors

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3475]
1. For an item, download the descriptive spreadsheet: Manage description > Download cocina spreadsheet.
2. Open the spreadsheet and change the value for any field that includes "type" (e.g., `contributor1:name1:structuredValue1:type`) to an invalid value (e.g., "foo").
3. Save the spreadsheet.
4. Upload the descriptive spreadsheet: Manage description > Upload cocina spreadsheet.

Expected:
* Cocina::Models::ValidationError message is displayed to user.
* No HB alert

Actual result:
![image](https://user-images.githubusercontent.com/588335/163252275-e5dd1fe4-3785-455f-86e1-b788ca9d3228.png)

https://app.honeybadger.io/projects/49894/faults/84964293

**Comment by andrewjbtw** [comment]
It might be premature not to show an HB alert since not everyone will get in touch with us when they seen an error and without the HB alert we won't know it happened.

**Comment by justinlittman** [comment]
@andrewjbtw We don't typically use HB alerts to notify us of user errors. This would add additional noise to HB whose primary purpose is to monitor for production issues.

**Comment by andrewjbtw** [comment]
If that's the goal, I don't think a review of what's currently reported and where will show much consistency in meeting that goal.

And if a validation problem turns out to be because a term is missing from a Cocina vocabulary, not because of user error, how would we find that out? I know for a fact that some people will report an issue immediately and some will wait, try again, wait, come back again, and maybe finally report if they really can't get their work done.
