### ISSUE TITLE
Redesign item registration form

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3514]
See Astrid's wireframe below. The motivation for the registration form redesign - beyond the fact that it desperately needs one - is to accommodate the new and more dynamic content type and access rights menus:

- The content type menu needs to expand to show reading order when that is relevant to the content type (book or image)
- The access rights menu needs to give access to view/download/location/CDL options

These two menus are separated out in the diagram as a way to make space to expand them. Depending on how we're able to implement this, we might need additional/modified labeling to indicate which menus belong together.

<img width="713" alt="registration-form" src="https://user-images.githubusercontent.com/8975583/163633983-b240f2fd-2624-4509-ad7f-c7bad3ee8176.png">

**If changes break an infrastructure integration tests, please provide fix for tests.**

**Comment by jcoyne** [comment]
How does the display change when you push each of the buttons or change the selected fields?
What values should be in each of the select boxes. 
What sort of validations should be done on each field? When should the validation take place? How do we display invalid values?

**Comment by justinlittman** [comment]
Notes from 4/18:
* Unless otherwise specified, current behavior should be replicated.
* "Rights" should be "View".
* "Downloadable by" should be "Download".
* Controlled digital lending should be added.
* Reading order should only be enabled when an appropriate content type is selected.
* Reading order should have the same values as Set Content type menu.
* Tracking sheets button should be disabled until after registration.
