### ISSUE TITLE
Replayable spreadsheet uploads (i.e. the bulk MODS upload) should not open objects or update Cocina if data would be unchanged

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3551]
**Describe the bug**
It looks like the Cocina-ized implementation of the replayable spreadsheet upload (the older, MODS-based spreadsheet) is trying to update the Cocina for every druid on a spreadsheet regardless of whether the update is actually resulting in a change to the metadata. Druids that would be left unchanged should be skipped during replayable spreadsheet MODS updates.

**Example**
The output of the replayable spreadsheet should show "Skipped" if the input matches the current data:

<img width="795" alt="Screen Shot 2022-04-20 at 3 49 08 PM" src="https://user-images.githubusercontent.com/8975583/164337409-d6e5a98a-0037-42da-b42d-626b74232a12.png">

But what seems to be happening is that every druid is always being updated, regardless of whether any change is made. 

To test, I used two druids: one is a Cocina first object and the other was created in Fedora first.
https://argo-stage.stanford.edu/catalog?f%5Btag_ssim%5D%5B%5D=Project+%3A+replayable+spreadsheet+test

I updated both druids more than once with the same spreadsheet: [replayable-2022-04-19.xlsx](https://github.com/sul-dlss/argo/files/8525996/replayable-2022-04-19.xlsx)

Every time I upload that spreadsheet, I get a "Saved" message. I should see "Skipped" for all jobs after the first one.
<img width="778" alt="Screen Shot 2022-04-20 at 4 13 12 PM" src="https://user-images.githubusercontent.com/8975583/164339803-ec832e26-b543-4c0f-97a9-91d0b9caf88e.png">

If you look at the descMetadata datastreams in Fedora (on sul-dor-test) you can see that they aren't being updated, which is expected. But the Events history shows that the system is trying to update the Cocina.

**User Impact**
This leads to unnecessary versioning and updating. Reporting "Saved" instead of "Skipped" is also confusing when users expect to see "Skipped."

**To Reproduce**
1. Take the two druids I linked above
2. Go to the APO page for those druids
3. Go to "Upload MODS"
4. Upload the spreadsheet I linked above
5. See the system try to update them

**Expected behavior**
When the spreadsheet matches the current data, the druid should be skipped. If the druid isn't "Opened" it should be left alone and not opened by the job.

**Comment by justinlittman** [comment]
Here is my understanding of the code:
1. From spreadsheet, Modsulator is called to convert a spreadsheet to Mods XML. (Let's call it Modsulator XML.)
2. The existing Mods is retrieved from Dor-Services-App (which is mapped from cocina). (Let's call it DSA XML.)
3. Modsulator XML is compared to DSA XML using the Equivalent library to see if it is different.
4. If equivalent, it is skipped; if different, it is updated.

The Equivalent library handles typical XML differences, e.g., whitespace. However, I suspect that there are XML differences between Modsulator XML and DSA XML even if they are logically equivalent because they are generated by completely different code.

I'm not sure how to handle this. Can Modsulator be changed to generate Cocina? Can we deprecate Modsulator?

**Comment by justinlittman** [comment]
Per discussion on 4/21:
* MODS / Cocina descriptive roundtrip mapping will be moved from DSA to Cocina models: https://github.com/sul-dlss/cocina-models/issues/426
* ApplyModsMetadata will be changed so that it: (1) converts MODS to Cocina descriptive; (2) compares existing Cocina descriptive against new Cocina descriptive; (3) if different, creates a new version and submits new cocina for update. (This is different from existing, where MODS is compared and MODS is submitted for update.)

**Comment by justinlittman** [comment]
This is done.
