### ISSUE TITLE
Add option to SW release to designate the druid a "related resource" rather than a "version of resource" 

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3568]
Drafting this now to capture a user request. We'll need to look at design and consider if there's a non-MARC use case.

Some recent work on digitization and linked data projects has surfaced use cases for releasing SDR items to SearchWorks where the second indicator in the 856 field is set to "2". This identifies the item as a related resource, rather than the resource itself. See [the MARC 856 documentation for details](https://www.loc.gov/marc/bibliographic/bd856.html).

The SW release process is currently set up to treat every druid as a version of the cataloged item itself, which means the second indicator on the 856 field is always set to "1" for "version of resource". Enabling users to set this indicator themselves would require:

- Updating the "Manage release" form to add the ability to select "version of resource" or "related resource"
- Updating the code that generates the 856

**Motivation and use cases**
The distinction between "version of resource" and "related resource" comes down to whether the druid represents the cataloged item itself or if it is only related to it in some way. 

- If the item is a sound recording and the druid is a digitized version of that recording, then it makes sense to call it a "version" of the item. In this case, SW indicates that the item is "online" and it appears in the online facet.
- But if the item is a sound recording and the druid contains only images of the album cover or liner notes, it's misleading to say the druid is a version of the recording. In that case, setting the 856 second indicator to "2" means that SW will not include it in the online facet. There will be a link from the SW record but it won't imply that the recording is available.

This came up recently because there's a project underway that is posting thousands of images of phonograph records but not posting recordings of those records. We're currently handling the indicator by modifying the records in Symphony after releasing from SDR. It would be better to support this by modifying the release process to handle it.

**Items without MARC records**

It's not clear to me whether anything needs to be done for items without SW records. The SW release form doesn't distinguish between items with or without catkeys, but this request only affects items with catkeys. We may need more in the interface to distinguish between the two descriptive metadata types.

**Comment by arcadiafalcone** [comment]
This also applies to inventories and finding aids deposited into the SDR, which often appear as an unmanaged purl in the collection record.

**Comment by ndushay** [comment]
@andrewjbtw and @arcadiafalcone up to you to get even a very rough design of how to fit this into Argo UI.  (You can say which screen, which pull downs, which fields to see)

**Comment by arcadiafalcone** [comment]
I think this should be part of the CatalogRecordId in cocina-models rather than the releaseWF, as it describes the relationship of the DRO to the resource described by the catalog record and is not simply an attribute of the release action.

In the modal launched by clicking the pencil icon next to the ILS ID, a column should be added between the ILS ID and the trash icon with the label "856 2nd indicator" (OK to split into two lines if necessary). Underneath the label should be a drop-down menu with the numbers 0-4 as options. Either as a tooltip next to the label or within the modal itself, the following help text should be presented to the user:
```
The 856 second indicator describes the relationship of the SDR object to the catalog record:
0 - The catalog record describes the same digital object
1 - The catalog record describes the physical item that has been digitized
2 - The catalog record describes another resource related to the SDR object
3 - The catalog record describes the digital object of which the SDR object is a part
4 - The catalog record describes the physical item of which the SDR object is a digitized part
```

Ideally this functionality would be added to the edit catalog record IDs bulk action as well, but currently the bulk action doesn't take the refresh status either, only the catalog record IDs.

@andrewjbtw How does this look to you?

**Comment by arcadiafalcone** [comment]
I think this should be part of the CatalogRecordId in cocina-models rather than the releaseWF, as it describes the relationship of the DRO to the resource described by the catalog record and is not simply an attribute of the release action.

In the modal launched by clicking the pencil icon next to the ILS ID, a column should be added between the ILS ID and the trash icon with the label "856 2nd indicator" (OK to split into two lines if necessary). Underneath the label should be a drop-down menu with the numbers 0-4 as options. Either as a tooltip next to the label or within the modal itself, the following help text should be presented to the user:
```
The 856 second indicator describes the relationship of the SDR object to the catalog record:
0 - The catalog record describes the same digital object
1 - The catalog record describes the physical item that has been digitized
2 - The catalog record describes another resource related to the SDR object
3 - The catalog record describes the digital object of which the SDR object is a part
4 - The catalog record describes the physical item of which the SDR object is a digitized part
```

Ideally this functionality would be added to the edit catalog record IDs bulk action as well, but currently the bulk action doesn't take the refresh status either, only the catalog record IDs.

@andrewjbtw How does this look to you?

**Comment by andrewjbtw** [comment]
I think this is a great idea. Having the value go with the catkey would help prevent accidental changes via re-releases as well.

Since this is substantially different than the original ticket, plus it's an Argo UI change too, could you re-post this as an Argo ticket? No doubt it will spawn other tickets, probably in DSA and cocina-models, when we get to it.

We can then close this ticket in favor of the new one.

**Comment by arcadiafalcone** [comment]
Replaced with https://github.com/sul-dlss/argo/issues/4006.
