### ISSUE TITLE
Display MODS title(s) in the body of the MODS view modal

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3615]
This came up when looking at items with parallel titles. The MODS view modal that pops up when you click on the MODS button in Argo is splitting up where it shows title information when there are multiple titles. The first title is going into the header of the modal and other titles are displaying below.

<img width="1367" alt="Screen Shot 2022-04-29 at 12 50 08 PM" src="https://user-images.githubusercontent.com/8975583/166060656-c2db3e3b-e55a-469f-b68a-6daa92339c06.png">

Example above taken from: https://argo.stanford.edu/view/gn988hy1229

In that example, the whole title is the combination of the title above the modal header and the title under the "Title". That's pretty confusing.

To cut down confusion, let's change the MODS modal to:

1. Always put the title in the body of the modal, under the heading "Title"
2. Put a generic header at the top of the modal, like "View descriptive metadata" (since it won't always be generated from MODS i in the future)

The latter change will also meet the requirements of #635

**Comment by jcoyne** [comment]
@andrewjbtw this is displaying what is coming from the `@mods_display.body` method (https://github.com/sul-dlss/mods_display/blob/4b7ec624989c420c973ded9feab92a71cc26c9b2/lib/mods_display/html.rb#L50-L52).  I believe that we are using this method so that we display exactly how it displays in Purl.   So we could deviate from this, but then we also aren't using the same display code as Purl is.

**Comment by jcoyne** [comment]
It looks like Purl is using `mods_display_html` https://github.com/sul-dlss/purl/blame/023b4fcfe16c630ba37431912516c274913bc3da/app/models/purl_resource.rb#L93
