### ISSUE TITLE
Processing status occasionally is not indexed correctly

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3817]
**Describe the bug**
Occasionally - probably daily - a number of items do not get their processing status updated correctly in Argo when accessioning is completed. Specifically, items show a status of "in accessioning" even though all workflow steps are complete. 

Usually when this happens the `end-accession` step shows up in Argo on the workflow grid or in the facets as "started". Occasionally, the `reset-workspace` step (one step before `end-accession` is listed as "started". The workflow display modal on the show page and the workflow server itself shows that these steps are completed.

Reindexing the item manually changes the status to "Accessioned" and shows all steps as complete.

**User Impact**
Users don't seen an accurate status and may think their items are still being accessioned when they're actually done. The "in accessioning" status also blocks further versioning and may throw off reporting if users are filtering by processing status when creating reports.

**To Reproduce**
This doesn't happen for every item and I haven't found a way to intentionally reproduce it. But I'm leaving some Google Books items in this state as examples: https://argo.stanford.edu/catalog?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=Google+Books&f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Aend-accession%3Astarted

Note that these will eventually get fixed via reindexing, but other druids may appear in that search over time.

**Expected behavior**
Workflow/processing status should be updated in Argo when each workflow step is complete.

**Screenshots**

What it looks like on the show page when Argo's processing status field doesn't match the actual workflow statuses.
<img width="943" alt="Screen Shot 2022-08-03 at 11 55 52 AM" src="https://user-images.githubusercontent.com/8975583/182687566-fdeaa783-4e4f-45e2-879e-e3c6d6afb016.png">

**Additional context**
This seems to happen most often when large batches of content are accessioned in a relatively short period of time. We saw this happen during the Catalhoyuk remediation and it happens on a regular basis with Google Books. But it's possible that this is a coincidence since those are the two projects that have seen the most updates recently, so they could be overrepresented.

**Comment by ndushay** [comment]
Is it possible that Argo has a stale Solr cache for the facets?

**Comment by peetucket** [comment]
Picked an example item which is currently showing the wrong status.  If I use the indexer to manually generate a new solr doc (same as what happens with a re-index) and it correctly reads the status.   The status comes from the workflow service.

```
identifier = 'druid:bh636wk0601'
cocina_with_metadata = Dor::Services::Client.object(identifier).find;
solr_doc = DocumentBuilder.for(model: cocina_with_metadata).to_solr;
solr_doc['status_ssi']
 => "v1 Accessioned"
```

**Comment by peetucket** [comment]
Here is how the indexer computes the status, it asks the workflow service:

```
@status_service ||= WorkflowClientFactory.build.status(druid: identifier, version: '1');
@status_service.display
 => "v1 Accessioned"
```

**Comment by ndushay** [comment]
Right, but Andrew is saying:  the SHOW page has correct info, but the FACETS do *not* have correct status.

**Comment by peetucket** [comment]
Likely because the show page modal directly goes to the workflow service to get the status of all the steps, and does not get them from solr.  The facets and the status display are from solr.  The solr doc is clearly stale and that is the problem.  The questions are
- why didn't the indexer get a message to re-index after the last step of the workflow was completed
- or if it did, perhaps there is a timing issue, where the workflow service returned the wrong answer briefly (but this seems unlikely)

**Comment by ndushay** [comment]
Let's blame it on rabbitMQ and connectivity?

**Comment by peetucket** [comment]
Theory is that many commits to solr are not being executed in the correct order, resulting in older data being indexed last.  Making an attempt to fix in workflow-server-rails by forcing a delay in sending a message to re-index on only the last step of the accessionWF.

**Comment by ndushay** [comment]
JCoyne believes the problem is caused by the workflow-service sending multiple messages in quick succession to RabbitMQ to reindex the same object.  Because Solr is a Solr cluster, there is probaby a concurrency sort of problem where the Solr update messages can be sent to different Solr servers, and the messages may ultimately be processed out of order.  

The approach we're taking is to delay one second before indexing the `end-accession` step of the accessionWF, so objects will correctly indicate when they are finished accessioning.
