### ISSUE TITLE
Updating catalog record id using the pencil icon does NOT include the "previous [folio|symphony]" in the cocina

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#3985]
**Describe the bug**
1.  Find an object with a ckey  https://argo-stage.stanford.edu/view/druid:ct013cq3840
2.  Open a new version
3. click on the pencil by the ckey in the "Details" section
![image](https://user-images.githubusercontent.com/96775/224436352-9be26167-cba6-40a0-9310-c83077de2f7d.png)
4. change the ckey by editing the textbox
![image](https://user-images.githubusercontent.com/96775/224436426-54b1677e-2c3e-436f-8fff-1c2fa097c305.png)
5. click on cocina model button.
6.  observe that previous symphony catalogLink is not present in cocina:
![image](https://user-images.githubusercontent.com/96775/224436705-63ddaf00-23b9-473c-bfb3-4f0c46057089.png)

The same is also true for editing folio HRIDs.

**Comment by ndushay** [comment]
The details display uses 
CatalogRecordIdComponent, which has a reference to edit_item_catalog_record_id_path which is for controller
catalog_record_ids#edit which in turn uses
CatalogRecordIdForm ...


The most recent change was in the PR to move catalogRecordId functionality around:  https://github.com/sul-dlss/argo/commit/5722c3bbcd78d83fba9f8e220945b8c4066a90d6#diff-51f17ec099a4d3ae6a7fee95686626c951c8fa1db84144bae618c0cddb5c8340

But this may have nothing to do with that PR.

**Comment by andrewjbtw** [comment]
I did some additional testing because I was getting "previous catkey" in the Cocina when I was testing recently. It looks like the previous catkey behavior is different in these two situations:

- removing a catkey
- replacing one catkey with another

This sequence will get you a previous catkey in the Cocina:

- Open the edit catkey modal
- Remove any existing catkey
- Close the modal

This sequence will not get you a previous catkey in the Cocina

- Open the edit catkey modal
- Replace the existing catkey with a different catkey
- Close the modal

**Comment by justinlittman** [comment]
This is also true of Folio (as currently deployed in QA).

**Comment by peetucket** [comment]
Are we sure we want to change this behavior?  My recollection from when we originally did this work was that if the user was replacing one catkey with another, the action would be to (1) remove the one being changed, then (2) add the new one.  This would result in the removed catkey being stored in the "previous catkey" slot and the new one being added as expected.  

If you were just editing an existing catkey, this would be for fixing an error, which wouldn't require preserving the "previous catkey" history.  It may have been by design (though definitely not clear, and in need of some user instruction in that box).

**Comment by andrewjbtw** [comment]
I'm not sure how this modal looked in the blue button era but in the current interface I think it's much likely for someone to edit in place in the text box than to remove the line and then add a new one. The only way we could assure someone didn't edit in place would be to lock that value.

But I also don't know how we could ever distinguish between fixing a mistake and changing a catkey. Someone could mistakenly add a catkey and then remove it altogether, and that is already being recorded as a previous catkey right now.

**Comment by andrewjbtw** [comment]
I'm curious what you think about this, @arcadiafalcone?

**Comment by arcadiafalcone** [comment]
The behavior I expect is that any entered catkey would become a previous catkey if it was changed or removed (unless the same catkey was already in the set of previous catkeys).

**Comment by lwrubel** [comment]
@justinlittman deploying for testing by @arcadiafalcone and @andrewjbtw
