### ISSUE TITLE
Facet "More" dialog has a double header

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#403]
Two red bars, differently rendered, both with an operable close X
![screen shot 2016-01-04 at 10 48 58 am](https://cloud.githubusercontent.com/assets/1824732/12097537/0da8c686-b2d1-11e5-9d3c-33046b86cc48.png)
A bug perhaps, but not one that gets in the way.

**Comment by mejackreed** [comment]
@LynnMcRae I would like to fix this. I need a clear understanding of what we are doing for modals globally. It feels like we have hijacked modal interactions in a couple of places.. Could you describe how modals _should_ work. We don't seem to have any tests for this... that I can find.
A few things I've uncovered:

 - Is there concept of resizable modal?
 - Is there a concept of "no close" modal... clicking or escaping away doesn't close it. In what context does this happen?
 - Is there a reason that a modal's title should be changed?

**Comment by jmartin-sul** [comment]
off-hand, here are the answers to jack's questions above, including convoluted historical background...
* i can't remember whether we allow resizing.  i think we do for default modals, which are used in most places, but maybe not "no close" modals?  i remember resizing being squirrely in some situations, so i disabled it since i didn't really have time to debug it.
* there is a modal which can only be closed by the `x` or `cancel` buttons (but not escape or click away).  we use this in places where modals contain editable content (e.g. for editing datastream xml, though there might be other editable things that still use the regular modal).  @LynnMcRae wanted this behavior so that it'd be harder to accidentally have work in progress disappear or get lost due to a mistaken click or key stroke (and IIRC, it turns out it's just a one of the bootstrap modal behavior settings).  also, these modals save state unless they're closed via the `cancel` button (not the `x`, which just hides it).  that was implemented initially because jessie and chris thought that disabling close on `esc` would be difficult, and suggested using code similar to some searchworks code jessie was writing for hiding modals to save state instead of recreating them every time they were opened (i didn't discover the setting for disabling `esc`/`x`/clickaway until after the persistent version was implemented).
* there are cases where we want a different title on the modal than the default, though i can't remember off-hand where we use that.

i'll look at the code and the commit history later this afternoon and come up with better answers.  also happy to pair on this stuff if that'd help, since some of that modal behavior is stuff that i implemented.

**Comment by mejackreed** [comment]
Thanks for the great context. Will work around that for now and try to clean up some of this.

A few additional questions:
 - Is the persistent modal something we want kept in (after closes state is saved)?
 - Is the resizable modal something we want kept in?
 - Is the moveable modal something we want kept in?

Thanks!

**Comment by LynnMcRae** [comment]
I put the modals into two categories (restating much of what John summarized)

1. informational, read-only
     • resizable, movable (that is, it would be nice to keep/enable these)
     • dismissed by ESC, click outside the dialog, or by explicit "X" control in header
2. Input/form
     • maybe just a minimum size to preserve form layout, but resizable to let text boxes grow 
     • movable too since you might want to see something under the modal
     • dismissed only by explicit Cancel or Submit (or equivalent)

We know we have a, um, situation with the datastream modal, which changes from informational to edit with a link.  If a modal can't change its stripe, can it be replaced on screen with a different modal? Some other approach?

Re persistent modal.  If this exists to save state for an accidentally dismissed form, it would be nice to avoid the situation in the first place as described above. Otherwise sure, it's nice if you did some edits, accidentally closed the modal with a stray click or un-intended ESC, and found your edits there when you re-opened the modal immediately. I don't really know the scope of the persistence.

Where do we change the modal title now?  I can see the double-header that originated this ticket to be a case, since a generic "more >>" is less desirable than knowing what facet you more-d

**Comment by mejackreed** [comment]
We have several different patterns right now on how the modals are implemented. I'm in the process of migrating us to a single pattern which I hope can accommodate these situations and alleviate the title, styling, and close issues without losing the work already put into this.

**Comment by LynnMcRae** [comment]
I imagine this will be resolved by your modal unification work, but just to enumerate some more of the inconsistencies and other issues.

Most modals have a sharp cornered red header resting on top of the round-cornered modal which looks odd to me. Some have left-justified titles, some are centered (preferred/default?)
![screen shot 2016-01-04 at 2 42 20 pm](https://cloud.githubusercontent.com/assets/1824732/12102912/307b2150-b2f3-11e5-8550-38c985a0cc2e.png)

We used to have a more integrated style, represented by the second half of the double-header that is the subject of this ticket.
![screen shot 2016-01-04 at 2 45 50 pm](https://cloud.githubusercontent.com/assets/1824732/12102936/6473e424-b2f3-11e5-828f-749b5f4c5ac8.png)

Note SW does something similar, minus the red background
![screen shot 2016-01-04 at 2 47 51 pm](https://cloud.githubusercontent.com/assets/1824732/12102951/8010d9a8-b2f3-11e5-9cae-4f8b8522dca4.png)

Finally, the blue-button form/dialogs are just a mess. Action controls are found in the form, sometimes multiple ones,  as well at the bottom of forms. The internal dialog problems won't be fixed by modal unification alone, though I hope they won't get in the way.  I'll work on separate tickets for individual dialogs.
![screen shot 2016-01-04 at 2 42 46 pm](https://cloud.githubusercontent.com/assets/1824732/12103072/3d904b44-b2f4-11e5-9b49-07ef21f00a4b.png)

![screen shot 2016-01-04 at 3 00 07 pm](https://cloud.githubusercontent.com/assets/1824732/12103095/6bcdb1ea-b2f4-11e5-8641-9571522cbc45.png)

![screen shot 2016-01-04 at 3 00 46 pm](https://cloud.githubusercontent.com/assets/1824732/12103109/8c51d2f2-b2f4-11e5-9bfa-162c7faca0e8.png)

![screen shot 2016-01-04 at 3 01 00 pm](https://cloud.githubusercontent.com/assets/1824732/12103116/97dd09de-b2f4-11e5-8dd9-6255f719de20.png)

This most recent mdal may be the closest to the controls we want, except for the redundant and ambiguous close-X in the header.
![screen shot 2016-01-04 at 3 06 36 pm](https://cloud.githubusercontent.com/assets/1824732/12103165/ece81824-b2f4-11e5-97aa-d0b7c0385aff.png)

**Comment by LynnMcRae** [comment]
Open version also has good controls, albeit in a different style
![screen shot 2016-01-04 at 3 12 53 pm](https://cloud.githubusercontent.com/assets/1824732/12103314/233c3b48-b2f6-11e5-9c06-674488a7579d.png)
