### ISSUE TITLE
Document reset process for preservation service (preservation_catalog, preservation_robots)

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4052]
# pres cat

In the preservation_catalog README (or wiki?), create a new top-level section (page if wiki?) called `Reset Process (for QA/Stage)`, and in that section document the following:

- [x] Verify what needs resetting (deleting) is the following:
  * Database: `pres` (Postgres) on `preservation-catalog-db-{qa,stage}-a.stanford.edu`
    *  `db/seeds.rb` seeds ZipEndpoint and MoabStorageRoot instances from configuration
  * Files: `/services-disk-stage/store-100/`, `/services-disk-stage/store1/`, `/services-disk-stage/store2/`, `/sdr-transfers/`, `/services-disk-stage/sdr-transfers/` (QA-only), `/services-disk-qa/` (QA-only)
  * Redis: `preservation-catalog-{qa,stage}-03.stanford.edu`
  * Cloud storage ❓ 
- [x] Determine what needs re-seeding (re-creating) in the app
- [x] Determine what needs re-seeding in SDR (e.g., APOs, collections, agreements, & canonical objects)
- [x] Determine how to reset and re-seed ☝🏻 (e.g., DB drop/create/migrate, specific DB table drops, `rm -rf`, export/import steps)

# pres bots

In the preservation_robots README (or wiki?), create a new top-level section (page if wiki?) called `Reset Process (for QA/Stage)`, and in that section document the following:

- [x] Verify what needs resetting (deleting) is the following:
  * Files: `/dor/export/`, `/services-disk-stage/store-100/`, `/services-disk-stage/store1/`, `/services-disk-stage/store2/`
  * Redis: `redis://sul-robots-redis-{qa,stage}.stanford.edu:6379/`
- [x] Determine what needs re-seeding (re-creating) in the app
- [x] Determine what needs re-seeding in SDR (e.g., APOs, collections, agreements, & canonical objects)
- [x] Determine how to reset and re-seed ☝🏻 (e.g., DB drop/create/migrate, specific DB table drops, `rm -rf`, export/import steps)

**Comment by jmartin-sul** [comment]
# step by step Procedure for clearing out the preservation service completely on stage and QA / how (_WIP_)

- [ ] quiet Sidekiq workers for preservation_catalog and preservation_robots in both QA and stage
- [ ] for both apps in both envs, let them finish WIP, or dump queue contents manually
- [ ] preservation_robots: temporarily alter shared_configs for the QA and stage environments to have a copy of the `config/sidekiq.yml` file from the pres bots repo, but with `concurrency` set to 0.  _QUESTION_ is it also necessary/wise to set `profile::sidekiq_systemd::sidekiq_count` to 0 for the QA and stage pres bots VMs in puppet?  This will be undone once DSA's cocina store has been reset successfully in both stage and QA.
  - _NOTE_: this implies the preservation reset is more easily done before the DSA reset for both envs.
- [ ] preservation_catalog: stop the web services
- _NOTE_: stopping pres bots workers and pres cat web services will effectively halt accessioning for the environment
- [ ] stage and QA: delete content on storage roots (all storage roots cumulatively listed in shared_configs for prescat/presbots in both stage and QA; see shared_configs)
  - [ ] _TODO: flesh out with specific commands on specific storage roots, respecting the expected storage "trunk" structure_
- [ ] work with ops to delete content on cloud endpoints for both stage and QA
- [ ] preservation_catalog: Rails db reset
- [ ] _TODO: flesh out with suggestions or draft shared_configs PRs_ pres cat and pres bots, stage and QA: shared_configs: make sure stage and QA no longer share storage mounts (i.e. point each environment to its own distinct set of storage roots)
- [ ] preservation_catalog: Run the `rails db:seed` command once shared_configs is fixed up.  This will bootstrap e.g. cloud endpoint and storage root records.
- [ ] undo the zeroing of preservation_robots workers in both QA and stage, restart workers in both envs.
- [ ] let preserved content on storage roots and in cloud be rebuilt by reaccessionioning 
  - Database and storage roots will get their new content as stuff flows through accessioning (from pre-assembly, H2, etc)

# high-level overview / why

preservation_catalog and preservtion_robots deal with data that originates from accessioning activity in other parts of SDR, as well as some preservation specific configuration data that is environment specific (mostly on prem and cloud storage locations).

* Resetting preservation_robots
  * pres bots doesn't have a data store besides Redis, which it uses for managing sidekiq jobs.
  * It reads bags from `'/dor/export/'` (configured by `Settings.transfer_object.from_dir`), and writes Moabs (that it builds from the bags using the moab-versioning gem) to the preservation storage roots for the environment (configured by `Settings.moab.storage_roots`).
  * things to reset for this app
    * pres bots' Redis should be empty once there are no pending or in progress Sidekiq jobs left.  So if WIP is wound down after quieting workers, or dumped proactively when it's time to reset (also after quieting workers), that should do for the Redis part.
      * _note_: probably want to stop accessioning in general in coordination with this.  and may want to coordinate the DSA reset.  won't make sense to try to preserve a post-v1 on a druid where the prior versions have disappeared, at the very least.  could just reset pres first, and leave pres bots down till DSA is reset?
    * Clearing bags from `/dor/export` would be the preservation robots file system portion of the preservation reset for the environment.
* pres bots writes the content to the storage roots (pres cat has read-only access to the storage roots); but pres cat maintains the catalog, audits the content for presence and fixity, replicates it to cloud archives, and provides the easiest way to query info about preservation status across the catalog.  Thus, wiping this content must be done from a pres bots VM, but is really part of resetting the preservation service as a whole, and isn't really specific to either application.
* part of this work is dis-entangling the currently conflated storage roots for stage and QA preservation, so they no longer share any storage roots.  this will require updating shared_configs for pres cat QA and stage, as well as pres bots QA and stage.  pres cat and pres bots need to be in sync in each env.
* Resetting preservation_catalog
  * pres cat's specific (non-SDR) data is what it needs to handle local preservation content (Moabs, each version of which is a version of an SDR object addressed by a DRUID).  I.e., info about storage roots (directories where DRUID trees of Moabs live), info about S3 cloud buckets (to which Moab versions are zipped and replicated), and info about the minimum frequency at which audits should be run on the various copies of preservation content.  Some of this info (e.g. storage root and cloud bucket) is stored in the database for easier querying around the health of preserved content across the catalog, some of it is just in shared_configs settings.
  * pres cat also has a Redis instance for managing its own internal jobs (which deal with replication of on prem content to cloud archives and auditing of all content on prem and in the cloud).
  * same thing for pres cat as pres bots about letting WIP wind down after quieting workers, or quieting workers and manually dumping queue content
  * Once the on prem storage roots and the cloud archives are wiped of content for the environment, run `RAILS_ENV=production bundle exec rake db:seed` (stage and QA both see themselves as prod) to bootstrap the info about storage roots and cloud endpoints and such that pres cat needs to function.

**Comment by justinlittman** [comment]
I think that we can assume that SDR will be quiet during the reset and so not necessary to forcibly make sure that no robots are active.

**Comment by jmartin-sul** [comment]
> I think that we can assume that SDR will be quiet during the reset and so not necessary to forcibly make sure that no robots are active.

ah ok, i wasn't sure how coordinated/synchronized we were planning to be about resetting all the things all at once

**Comment by jmartin-sul** [comment]
after lunch:

I'll clean up the instructions in the above comment so that they're generalized to re-setting a single environment in a situation where we don't have to disentangle storage roots, since that'll likely be the more common scenario after this upcoming reset.  Then per standup discussion, I'll put up a README PR with those simplified instructions (since we decided to keep putting these instructions in the README).

**Comment by jmartin-sul** [comment]
README PR with generalized instructions for future resets (which assume no storage roots to disentangle between envs): https://github.com/sul-dlss/preservation_catalog/pull/2261

left the comment on this issue focused on this impending reset, with storage root disentanglement.

**Comment by jmartin-sul** [comment]
@mjgiarlo since this reset is likely to be slightly different from the one documented in the README PR that you just merged, would you mind giving [the checklist in the comment above](https://github.com/sul-dlss/argo/issues/4052#issuecomment-1690550978) a once-over, since you can't officially review an issue?

**Comment by mjgiarlo** [comment]
@jmartin-sul Will do. I'm also tagging in @justinlittman to review it as well since he now has more of this loaded in his brain than I do.

**Comment by jmartin-sul** [comment]
> @jmartin-sul Will do. I'm also tagging in @justinlittman to review it as well since he now has more of this loaded in his brain than I do.

thanks!

**Comment by jmartin-sul** [comment]
@julianmorley says we devs have the power to delete content from QA S3 buckets, so we'll file a ticket for that and do that cleanup later...

**Comment by jmartin-sul** [comment]
# step by step Procedure for clearing out the preservation service completely on stage, and finishing disentangling shared storage between QA and stage

_NOTE: These instructions assume that SDR will be quiet during the reset, and that all other SDR apps will also be reset. Since related services (like DSA) and activity (like `accessionWF` and `preservationIngestWF`) won't be making requests to preservation services, and since e.g. the Cocina data store will be reset, it's not necessary to specifically make sure that no robots are active here, and it's not necessary to worry about syncing content from other apps with preservation._

what (we think) remains for for the stage reset, and for finishing of cleanup of old QA and stage content

- [ ] Quiet Sidekiq workers for preservation_catalog in stage (preservation_robots should already be quiet).
- [ ] preservation_catalog: stop the web services
- [ ] Work with ops to delete archived content on cloud endpoints for stage.  If Suri is not reset, then druids won't be re-used, and this can be done async from the rest of this process.  _But_, if the reset is completed and accessioning starts up again before the old cloud archives are purged, you should dump a list of the old druids before the preservation_catalog DB reset, and give those to ops, so that only old content is purged.  You can query for the full druid list (and e.g. redirect or copy and save the output to a file) with the following query from pres cat: `druids = PreservedObject.pluck(:druid)` (this will return tens of thousands of druids).
  - `File.open('/opt/app/pres/druids_pre_reset_stage.txt', 'w') { |f| druids.each {|druid| f.write("#{druid}\n")}}`
- [ ] From a preservation_robots VM in stage, if not done already for another app's reset: Delete all content under preservation_robots' `Settings.transfer_object.from_dir` path, i.e. `rm -rf /dor/export/*`
- [ ] **_one-off for this ticket's reset:_** pres cat, pres bots, and techMD: shared_configs: make sure stage and QA no longer share storage mounts (i.e. point each environment to its own distinct set of fresh as-yet-unused storage roots).  The following remaining PRs should be approved and merged, then pushed to pres cat VMs, before the pres cat DB is re-set and re-seeded, which will get it switched over to the new storage roots post-reset:
  - [ ] https://github.com/sul-dlss/shared_configs/pull/2041
  - [ ] https://github.com/sul-dlss/shared_configs/pull/2042
  - [ ] https://github.com/sul-dlss/shared_configs/pull/2043
- [ ] preservation_catalog: for the env being reset, `cap shared_configs:update` (to push the latest shared_configs, since storage root locations will have been updated).
- [ ] preservation_catalog: from one VM, [reset the DB per the relevant DeveloperPlaybook entry](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/db_reset.md).  Stopping Sneakers should be unnecessary, but everything else applies, including running the `rails db:seed` command, which should pick up the current storage root and cloud endpoint configs.
- [ ] re-deploy preservation_catalog, preservation_robots, and techMD.  This will bring the pres cat web services back online, bring the Sidekiq workers for all services back online.  if sidekiq doesn't bring the workers back, you may have to manually restart using the `service` command with the `-all` (?) flag.

## post-reset cleanup

## local storage root cleanup

delete all content under the `deposit` dirs and the `sdr2objects` dirs in each of the **_old_** storage roots (`sdr2objects` is the configured "storage trunk", `deposit` is where the bags that are used to build Moabs are placed). Storage root paths are listed in versions of shared_configs **_from before the QA reset was done on 2023-09-27_** for prescat/presbots/techmd in both stage and QA.  So, e.g., `rm -rf /services-disk-stage/store2/deposit/*`, `rm -rf /services-disk-stage/store2/sdr2objects/*`, etc if the storage roots are `/services-disk-stage/store2/` etc.  Deletions must be done from a preservation_robots machine for the env, as techMD and pres cat mount pres storage roots as read-only.
  - [ ] **_one-off for this ticket's resets:_** delete the old storage roots after we've switched to fresh storage roots for the QA and stage environments, distinct to each env.  You should be able to `rm -rf` the following dirs from pres robots stage: `/services-disk-stage/store-100`, `/services-disk-stage/store1`, `/services-disk-stage/store2`, `/services-disk-stage/new-store-fixtures-sr1`.
    - The new storage roots are at paths `/services-disk-[qa|stage]/storage-root-[1|2]`, and should be left alone.
    - See also the pres cat ticket about disentangling storage roots: sul-dlss/preservation_catalog#1986
Once the various SDR services are started back up, preserved content on storage roots and in the cloud will be rebuilt by regular accessioning.

## cloud cleanup

use the druid lists dumped during the stage and QA resets, and the cloud archive endpoint confgs in shared_configs and vault, to remove replicated content for druids from the reset instances of QA and stage.  fine to use either the ruby S3 client from a QA or stage rails console, or the AWS CLI with the `vault` command and non-secret values from shared_configs in env vars, whatever's easiest.

## context for why those are the steps

_see earlier comment with reset procedure for QA and stage that ended up only being used on QA_

**Comment by jmartin-sul** [comment]
apologies for any issue spam the last day or two, was finishing off one last bit of cleanup that had slipped after the reset, see https://github.com/sul-dlss/preservation_catalog/issues/2397
