### ISSUE TITLE
descriptive metadata spreadsheet: ignore contributor role data if contributor name not provided

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4071]
When importing a descriptive metadata spreadsheet, if any of the cells include data for 

`event*.contributor*.role*.code` 

and 

`event*.contributor*.role*.value` 

but do not include a name for the corresponding contributor in 

`event*.contributor*.role*.name.value`

then do not import the `event*.contributor*.role*.code` and `event*.contributor*.role*.value` metadata into the Cocina. 

The presence of contributor role metadata without a contributor name in the Cocina leads to errors when trying to publish the druid. Fixing such errors is a complex remediation task.

Related HB error: https://app.honeybadger.io/projects/50568/faults/89158658

**Example spreadsheet data that will cause a problem**

In the example below, the data from the second row will result in errors at the publish step.

event1.contributor1.name1.value | event1.contributor1.role1.code | event1.contributor1.role1.value
-- | -- | --
Schmidt, Heinrich | dfd | Defendant
  | dfd | Defendant

**Comment by ndushay** [comment]
did you mean for this to be scoped to events, or is it for ALL contributors occurring anywhere?

**Comment by ndushay** [comment]
also, is it possible that data is in the exported csv because we do not have a validation checking, or is it getting in the CSV because of the data they are importing?   Knowing this would help us target the right piece of code (e.g.  not creating any cocina with only role and no name in a contributor at any level if it can come from places besides an uploaded csv)

**Comment by arcadiafalcone** [comment]
I agree - all contributors.
