### ISSUE TITLE
SDR stage objects to re-seed in a freshly created QA/stage environment

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4115]
This ticket lists SDR stage objects that should be carried over to a freshly-created stage/QA environment. 

Note that these are not objects that are essential to the functioning of a stage/QA environment (like an "Ur-APO"). These are objects that would take a fair amount of effort to re-create each time in a new environment.

I'm going to categorize these by originating pipeline/app. We may decide to ticket separately for the items that need to be created in a specific app like was-registrar-app/H2/ETD.

**SDR/Argo**

- The ["Canonical objects" APO](https://argo-stage.stanford.edu/view/druid:gd252zt8140)
- The ["Canonical objects" collection](https://argo-stage.stanford.edu/catalog?f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Agd252zt8140&f%5BobjectType_ssim%5D%5B%5D=collection)
- All of the items within that collection

These objects correspond to the prod objects on the ["SDR canonical objects" spreadsheet](https://docs.google.com/spreadsheets/d/1GvK5NSpcPSfF9Xd_hNlzCI18NrgHAbwAKSO1xUM0fnE/edit#gid=0). They're used to test specific public-facing functionality when making changes to viewer behavior or for debugging if the viewer doesn't seem to be functioning as expected.

Ideally, we would be able to keep the same druids each time we re-create these items because that would preserve the links in the canonical objects spreadsheet.

**H2**

No particular objects should be carried over. I checked with Amy, who reports that it's useful to have existing data in the H2 environment when checking on admin features (like reports) but that there are no items in particular that she relies on for testing.

**Geo**

No geo items need to be carried over.

**ETD**

None

**Web archiving**
None

**Comment by justinlittman** [comment]
GIS?

**Comment by andrewjbtw** [comment]
Every geo object in stage is from an integration test with the exception of four objects that I registered but never accessioned.

**Comment by justinlittman** [comment]
For integration tests, the following are needed:
1. APO for GIS: https://argo-qa.stanford.edu/view/druid:pz622dy7635 and https://argo-stage.stanford.edu/view/druid:sq797nc3050
2. Integration Test Collection - GIS: https://argo-qa.stanford.edu/view/druid:sb700rz4450 and https://argo-stage.stanford.edu/view/druid:jn518bx4248
3. integration-testing APO: https://argo-qa.stanford.edu/view/druid:qc410yz8746 and https://argo-stage.stanford.edu/view/druid:qc410yz8746
4. integration-testing collection: https://argo-qa.stanford.edu/view/druid:bc778pm9866 and https://argo-stage.stanford.edu/view/druid:bc778pm9866
5. ETDs APO: https://argo-qa.stanford.edu/view/druid:bx911tp9024 and https://argo-stage.stanford.edu/view/druid:bx911tp9024
6. Goobi Testing APO: https://argo-stage.stanford.edu/view/druid:hv879dp7661 (stage only, since no Goobi QA)
7. Web Archive Seed Object APO: https://argo-qa.stanford.edu/view/druid:xt299pt7593 and https://argo-stage.stanford.edu/view/druid:xt299pt7593
8. Test Pywb Web Archive collection: https://argo-qa.stanford.edu/view/druid:ns083tz4433 and https://argo-stage.stanford.edu/view/druid:rs265gb6576

**Comment by ndushay** [comment]
I'm pretty sure there's an ETD collection needed, too.

**Comment by andrewjbtw** [comment]
There's no ETD collection, just items: https://argo.stanford.edu/catalog?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=ETDs
