### ISSUE TITLE
"Download all files" hits 404 errors when downloading from "Opened" items

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4141]
**Describe the bug**
The "Download all files" function in Argo gives users a zip containing all the files in preservation for an object. This function appears to always fail when an object is in an "Opened" state. There's an HB error that shows a 404 for the download:
https://app.honeybadger.io/projects/49894/faults/68070005

It looks like the problem has to do with versioning and version numbering. When an object is opened, it's version number has been incremented by one from the last accessioned version. This means that:

- Argo says the object is at version n+1
- Preservation only has versions up to n

I think what's happening is that the download all files function is requesting the version number that Argo has, so:

1. Argo says: send all files from version n+1
2. Preservation says: I only have files from version n
3. 404 error

Once the object is closed, the download will work without any changes to the files in the Moab.

**User Impact**
Users can't download preserved files from objects that are opened and it's not clear why it's not working.

**To Reproduce**
1. Go to this test object https://argo-stage.stanford.edu/view/druid:bb020zq0872
5. Try to download all files
6. See that it doesn't work. The browser will look like the download hangs and HB will show a 404 for an Argo action

**Expected behavior**
When an object is opened, download all files for the most recent accessioned version, which must exist because the "Opened" status is only possible if an object has at least one accessioned version.

**Additional context**
A "draft" state that does not immediately increment the version number in Cocina instead of "opened" state might help here but that's some ways off.

**Comment by peetucket** [comment]
Andrew, I believe your theory is correct, and the fix is to download the last accessioned version instead of the current version listed in cocina.  

One side-effect: currently we always render the "Download all files" link (even for things that haven't yet been accessioned).  At the moment, this gives you an empty zip.  However, with my intended fix (which requires reaching out to preservation to find the last accessioned version), this will generate an exception (since there is no version in preservation at all).  Since the current logic in that method always goes to preservation to find all of the files, I propose we simply do not render the "Download all files" link unless the object has been accessioned at least once (i.e. there is a complete version 1).  Does this make sense?

**Comment by andrewjbtw** [comment]
Retrospectively commenting (since I think this change is already out) that it makes sense not to render the link if an object hasn't been accessioned.
