### ISSUE TITLE
Review font usage (size/color/weight/etc.) on argo homepage and item show pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4151]
Review font usage (size/color/weight/etc.) on argo homepage and item show page for consistency and compliance with [Stanford branding guidelines](https://decanter.stanford.edu/page/brand-design-elements-typography/).

See the relevant [Slack discussion](https://stanfordlib.slack.com/archives/C09M7P91R/p1694034595390819) for background. This came up because adding the Stanford footer resulted in a subtle change in font usage throughout Argo.

Differences can be viewed by deploying Argo with the footer to QA and comparing with Stage or Prod.

**Comment by astridu** [comment]
Font size should be 16px to be accessible, which I think is 1 rem?

**Comment by mjgiarlo** [comment]
@astridu reviewed the Argo UI (as displayed in the QA instance), and added:

> Looks like 'Limit your search' and 'Welcome to Argo' are larger than that so they are fine. Everything else should be at least 16px. And looks like table headers are all large enough. So it's mostly the body text. It looks really close if it isn't already that size.

I double-checked and found the following:
* For the required Stanford footer
  * Most of the fonts in the footer are 1rem
  * Some are 0.9rem like the Stanford terms of use link
  * The copyright statement is 0.8rem
* Body of homepage & item show page
  * The "logged in as" text in the header is 0.8rem too
  * Otherwise, we take the Bootstrap default, which is 1rem
* There are a few, isolated spots in the code where we explicitly ask for a smaller font

@astridu says close enough and good to go for now.
