### ISSUE TITLE
Bulk update as its own thing rather than a view?

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#417]
Do we need to treat bulk update as if it was a peer search result view to other displays?  Having it accessible under the View drop down and calling it "Bulk update view" is not intuitive and has already tripped me up a couple of times.  At a minimum, can it be presented as its own button?

[Sort by druid v]  [10 per page v]  [Select view v]  [ Bulk update]

(an aside, I'd like this also so that it can become a dropdown to other Bulk actions unrelated to the results display, such as the downloading of descMetadata)

An on the Bulk action page, this top heavy screen could be simplified by eliminating the Select View button taking up a whole slice of the screen, and we could simply have "Back to Search" next to "Start Over".  
![screen shot 2016-01-06 at 11 44 34 am](https://cloud.githubusercontent.com/assets/1824732/12152731/f910f662-b46a-11e5-9922-2a3c67e2de2a.png)

This would make it comparable to the Spreadsheet upload screen:
![screen shot 2016-01-06 at 11 47 46 am](https://cloud.githubusercontent.com/assets/1824732/12152811/5a0171ea-b46b-11e5-9402-30988b415aab.png)

**Comment by mejackreed** [comment]
Rather than another stop gap for this, can we address this holistically when we move to the new bulk actions framework?

When you say "tripped me up".. what do you mean? What happened and what did you mean to do?

WRT the page, you want to lose the breadcrumbs which gives the context of the search of druids that you are bulk updating?

**Comment by LynnMcRae** [comment]
I was going to look at Tommy's changes, didn't see the button I was "expecting" and had started a ticket about it even when Tommy came in and we remembered where it had gone together. I just would never expect doing bulk updates to be under Select View.

We wouldn't lose the breadcrumb ... that's where Back to Search and Start Over live as well.  We'd lose the [Select View] button/slice as the means to exit from Bulk Update.

**Comment by LynnMcRae** [comment]
I was proposing the separate location for Bulk Updates as a step to the new bulk actions framework, because it would be easy to change that to a dropdown named [Bulk actions] that offered, say, Bulk updates, Bulk MODS upload, and Bulk MODS download. The list could then change according to how the old/new capabilities migrate.

**Comment by mejackreed** [comment]
Gotcha!

The "Back to Search" and "Start Over" are in the "show" context of an object, while the bulk actions is an "index" view of a search result. "Back to search" in this context is a little bit different because a "search" could actually be any of the results types views. Using default Blacklight partials doesn't put that link there.

Seems like adding the button outside of the view dropdown gets us part of the way there (hopefully to reduce confusion of how to "do" bulk actions). But wouldn't reduce that whitespace in that spot.
