### ISSUE TITLE
/dor/reindex no longer works as a REST endpoint

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#434]
it used to be that you could do something like `/dor/reindex/druid:hv992ry2431` to reindex an object via REST call (and indeed, this is what fedora ultimately does when it sends a message indicating that an object was updated, though karaf acts as a queueing intermediary).

however, a regression was introduced as part of PR #432, and an error occurs unless the URL is hit from a link in the app:
`No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].`
http://localhost:3000/dor/reindex/druid:hv992ry2431
https://argo-prod-b.stanford.edu/dor/reindex/druid:hv992ry2431
https://sul-squash.stanford.edu/projects/argo/environments/production/bugs/61
https://github.com/sul-dlss/argo/blob/develop/app/controllers/dor_controller.rb#L45-L53

@mejackreed points out that we can get the referrer info via `request.referrer` (or `request.referer`, if you're into preserving RFC typos).  if it's acceptable to differentiate behavior based on that, i'd propose that we use the new behavior whenever `request.referrer` indicates that the request was a result of clicking on a reindex link in the app.  otherwise, default to the old behavior.

**Comment by drh-stanford** [comment]
should we revert PR #432?

**Comment by drh-stanford** [comment]
I've created PR #435 if we want to revert #432...

**Comment by atz** [comment]
Reindex should not redirect at all, imho, since consumers of the endpoint (including Argo) **should** be using a POST for proper RESTfulness.  

Consider, for example, hitting the reindex endpoint with AJAX posts from UI buttons, a totally reasonable client behavior.  It should get be able to get a 200, 500 or whatever (in JSON).  Redirection suggests that the response code of the target page gives the agent the status of the reindex request.  It does not.

**Comment by mejackreed** [comment]
I think I've found a solution that should handle both cases nicely. Thanks @cbeer for the idea. PR will be pending soon.
