### ISSUE TITLE
Display better view of workflow context variables

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#4456]
The argo workflow view currently shows any available workflow context as a hash at the bottom of the workflow display. Improve the display (tabular?)

![Image](https://github.com/sul-dlss/argo/assets/47137/e33b3ae8-b16b-4ea9-a38e-62c4cbc6567e)

**Comment by justinlittman** [comment]
I think it is really going to cause user confusion to have context displayed for workflows that it doesn't apply to. (I was already confused.)

**Comment by peetucket** [comment]
The issue is that workflow context currently goes with the version (not the workflow), so it has no idea which workflow it is relevant for.  This is useful in case that context is needed across the whole accessioning process (i.e. across multiple workflows).

**Comment by jmartin-sul** [comment]
As a first pass, we think displaying the hash contents as a table could work (or whatever the person who picks it up thinks is best).  Might be nice to have field values that are list display as comma separated lists instead of as a ruby array presented via `#to_s` (because then you'd see extraneous square braces and such).

Ask PO/design whether the solution looks presentable enough as part of PR review.
