### ISSUE TITLE
Create a search result from a list of druids

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#451]
Feature request from https://jirasul.stanford.edu/jira/browse/ARGO-201 ... the ability to paste a list of druids into Argo and interact with with as if it was a search result, perhaps by actually making a search result from it :)   You would then be able to report on custom populations, and we might simplify bulk actions by removing its separate "copy a list of druids to act on" feature.

**Comment by andrewjbtw** [comment]
This would enable users to track batches of objects that do not have a single facet value common to all of them. Situations where this comes up:

1. Tracking progress after a batch of items are sent through preassembly
 - Note that users will have a druid list ready because they needed it for the preassembly manifest
2. Applying remediations to a known set of druids
 - Likely use case here is a set of items that have gone through content QC

**Comment by jcoyne** [comment]
How big of a list would this have to support? How would the user provide such a list?

**Comment by andrewjbtw** [comment]
This was discussed at the workcycle planning meeting. It seems that the biggest barrier is that the druids would need to be part of the URL, so the size of the result list would be limited by the length allowed for the URL.

Determining if there's another way to implement this seems too large for the current (Q2 2020) workcycle. I think improvements to bulk tagging are another way to achieve the same outcome, as long as users are able to add the same tag to an arbitrary set of druids in bulk. See #2007 for more on that approach.

**Comment by andrewjbtw** [comment]
Given previous design discussions, it doesn't seem feasible to cover this in a one step process where:

- user submits a list of druids
- search result contains that specific list of druids

What is possible now via the bulk tags feature is:

- user associates a set of druids with a new tag
- user facets on that tag to get a search result

That has the side effect of adding another tag to the system, but has the advantage of creating a persistent grouping for purposes of creating the search result. There are many situations where an arbitrary search result could be lost and would need to be recreated. Ideally, if the tag were created solely to create a grouping in order to take care of a specific task, then the tag would be removed later.

Taking all that into consideration, I'm going to close this issue. The approach mentioned above, of stringing together a group of druids in the query URL, isn't very scalable, while tags can be used for essentially any size search result.
