### ISSUE TITLE
Allow metadata upload when dor_object is in a "registered" state

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#456]
modsulator currently does not support spreadsheet upload when an object is in a "registered" state. Tommy pointed to the piece of code where in_accession is defined - and it seems that there are numerical state definitions that are included for the broad category of "in accessioning".

@LynnMcRae - this is in keeping with your understanding of the desired functionality, correct?

**Comment by tingulfsen** [comment]
I believe this should be a quick and easy fix, we just need to decide whether or not allowing metadata upload for registered objects is the right thing to do.

**Comment by LynnMcRae** [comment]
It's a no brainer .... it's when uploadable spreadsheets will be used most often, when the object and its metadata are first being created.  We should allow updates for anything not active in accessioning.  Registered and Open do not have to be have a new version open because they are already creating initial (registered) or subsequent (open) versions.  Something in Accessioned state is the only case where a new version needs to be opened if data is created or replaced.
