### ISSUE TITLE
 clean up Argo indexing to use the centralized dor-services indexing code

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#515]
From #96 leftovers. The places where Argo still does reindexing (e.g., ItemsController) should be migrated to use the dor-services indexing code. https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/services/indexing_service.rb (or maybe REST API calls to the new dor-indexing-app?)

**Comment by jmartin-sul** [comment]
i'd be in favor of using the dor-services code directly, since it already packages things pretty neatly, and would save the network traffic of calling out to dor_indexing_app.

actually... did manually triggered bulk reindexing of a list of objects get refactored with the bulk actions framework?  or does that still have the browser calling /dor/reindex for each object?  @tingulfsen & @mejackreed?  if that hasn't changed yet, maybe it could use the new bulk actions code, or the `BulkReindexer` code.  or, that might be something that could reasonably be sent to dor_indexing_app, though hopefully in a more efficient way than one request per object.  it'd be easy for it to implement a `reindex_list` method, since dor-services already has working code for that.

and actually, i was talking with tommy the other day, and we agreed it'd be good for the implementing parties to give intros to the rest of the team for BulkReindexing and the new bulk actions framework.  just so everyone knows what's available for doing that sort of stuff, and how the code works now with some core functionality that's been refactored.  since jack was involved in both, i'm guessing there's not tons of overlap between the two, but maybe with everyone there, we'll see things that can be further consolidated/de-duplicated.  and an intro would be good even if not (i know i don't have a good idea of how bulk actions works, and i've seen a bit of confusion over the division of responsibility between dor_indexing_app, bulk reindexing in argo, and one off reindexing in argo).

**Comment by mejackreed** [comment]
We haven't moved any legacy bulk actions over. Happy to discuss how that could be done, but doubtful we will move things over in the next week? Especially without @LynnMcRae input first.

**Comment by mejackreed** [comment]
Also, why does Argo need to do the indexing? Is the HTTP overhead that much? The jobs happen in the background, and I would be happy to offload everything to a single service.

**Comment by drh-stanford** [comment]
In a few cases, Argo makes changes to the DOR object that needs a synchronous index update so that when it redirects to the catalog show page, the new information shows up. For example, the Add Workflow and Update Embargo need that synchronization. I'm ok with having the Argo reindexing calls go out to a REST API for dor-indexing-app, as long as we can ensure the commit happens in those cases (maybe a parameter `commit=true` or something at the endpoint?). The overhead would be the need to reload the object from Fedora and the HTTP roundtrip.

**Comment by mejackreed** [comment]
I'm all for leaving the synchronous updates in, I guess where I'm less inclined to want to maintain code is leaving a reindex route open. Don't want to leave that open so that we don't allow external consumers to use Argo to reindex. I know @jmartin-sul might feel differently though :smile_cat:

**Comment by jmartin-sul** [comment]
ah, yeah, i wasn't suggesting doing any of this before release.  i was more just thinking about what we might do down the road.

and while i like having the reindex route for my own personal use when developing, or when investigating issues in dev/stage/prod, i totally agree that we don't want other applications using that URL to do reindexing.  i'm definitely in favor of disallowing that, as i think that was usually to blame when argo fell over under indexing load (and i'd hope the existence of dor_indexing_app will largely take care of that, since that's what sulmq will point to, and the message queue is what mediated most requests like that).  and i also wouldn't jump through any hoops to keep a functional /dor/reindex route for my own use in argo, since dor_indexing_app can serve that purpose now (and it's not that hard to jump on the console and do it either, esp now that the reindex logic is packaged in dor-services).

i think there could be some discussion about how to handle bulk reindexing of a list of objects triggered by a user from the argo bulk update UI.  i'd be fine having those requests go out to dor_indexing_app, though we might at least send one list instead of requests for each druid (would need to create a dor_indexing_app method that exposes the dor-services method for reindexing lists, which should be simple).  or, we could use BulkReindexer, or maybe bulk actions.

but again, all for later :smiley:

**Comment by mejackreed** [comment]
piece of :cake: ... fwiw it might be easier to write the job to do single calls with druid logging responses for each druid. Part of the bulk actions provides for a way to retrieve a log of what takes place on what druid and its success or failure. /shrug will just leave this here for whoever (whomever?) picks it up

**Comment by mejackreed** [comment]
Sorry another follow on, by using bulk actions with single calls, it will also allow a bulk reindexer to view a status as items are reindexed eg 33 completed of 23,000, 14 failed. A tradeoff for the http overhead.

**Comment by jmartin-sul** [comment]
cool, that would be really nice.  definitely interested in looking into this more once the current sprint is out of the way.
