### ISSUE TITLE
Style info being passed in error messages (bulk update page)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#518]
<img width="715" alt="screenshot 2016-02-12 17 36 27" src="https://cloud.githubusercontent.com/assets/796990/13024775/498a6ec8-d1af-11e5-830b-c9019a57bb05.png">

**Comment by mejackreed** [comment]
What action were you doing here? A 500 error was happening and the default html for that page was being sent through.

**Comment by atz** [comment]
Still current?

**Comment by blalbrit** [comment]
Still current. Any 'bulk update' action that throws an error causes this behavior.

**Comment by jmartin-sul** [comment]
indeed.  i ran into this last night when i tried to use old-style bulk reindex to do the workflow objects that'd previously failed (many of them failed again).

**Comment by mejackreed** [comment]
Yep we just don't respond to different formats any differently here. So all of the `js` requests are getting the HTML error page back. Is it worth investing effort into this or porting the action to the new framework.

**Comment by blalbrit** [comment]
@mejackreed Could we substitute the HTML error page with a simple message?

**Comment by mejackreed** [comment]
That is possible, but I feel like it's covering up larger issues here at play. When you get those styles, what you are seeing is that the app encountered an unexpected error.

So just sending an unexpected error message instead isn't going to holistically fix the issue.

**Comment by LynnMcRae** [comment]
I think that was Ben's point ... for the short term, as long as the only thing we get is the same "Sorry something went wrong" followed by distracting markup, we might as well show a one word status just as we do for success (rather than try to "fix" the html return). The word "Error" would suffice and provide the same level of information.  That can easily change to showing more information once it becomes available.

**Comment by mejackreed** [comment]
Well that would then mean doing that for all of the error pages for the application. the problem here is that Argo is experiencing unknown issues that need to be fixed. If these things pop up, we should allocate resources to fix them.

**Comment by mejackreed** [comment]
I propose we have a meeting to discuss this issue and the other error page issues in person. I want to make sure that I can explain my reasoning to help better Argo. Happy to do this informally next week.

**Comment by LynnMcRae** [comment]
yes please.  I'm not suggesting a change to the substance, content or formatting of error return information (despite needs there) or showing something different elsewhere, only that in this context we could report the FACT of the error if we have nothing else to offer, like listing "500 Error" vs "200 OK" instead of trying to show information that is a page rather than a meaningful message.  Sure, we should fix all errors, but when they happen, and they will, we want what we show the user to be something better than the above.  (and it is in the nice-to-have category, so not trying to make too much of it)

**Comment by blalbrit** [comment]
Continues to be a problem over a year later, and provides a bad (and unhelpful) user experience. @LynnMcRae - I'm removing the "nice to have" label from this, which was sprint specific. This is a bug.

**Comment by peetucket** [comment]
fixed by #1284 -- just shows simple errors coming back from html response now
