### ISSUE TITLE
Prepare version fails in individual & bulk modes on -stage & -dev

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#519]
Not sure if this is temporary issue with network or problem with Argo, will test again tomorrow and close ticket if it's ephemeral.

<img width="1142" alt="screenshot 2016-02-12 17 53 26" src="https://cloud.githubusercontent.com/assets/796990/13024914/a3473c6e-d1b1-11e5-8dae-c4f5ebac4897.png">

**Comment by mejackreed** [comment]
Seems like this is related to squash-stage bugs 21, 22, & 23

**Comment by LynnMcRae** [comment]
Didn't we decide that links to the squash information would be provided on the error page itself?

**Comment by mejackreed** [comment]
I'm not sure I remember that. It would be possible to put a link to the project on squash on the 500 page, but not the individual bug itself. I can see how this would be helpful for you @LynnMcRae and @blalbrit but is there a chance this could cause confusion with other users?

Also per @cbeer squash has a queuing system that always doesn't immediately register a bug.

**Comment by LynnMcRae** [comment]
It was part of the discussions around #333

**Comment by LynnMcRae** [comment]
I also thought we resolved the issue about confusion for users .... it's an internal app and the need for real-time diagnostics (which shouldn't happen in the app in general) is greater than other considerations and not in conflict with how we treat public apps. Even the top message from a stack trace -- e.g., nil class or timeout -- allows us to fingerprint and recognize recurring problems.

**Comment by blalbrit** [comment]
Issue is present in -dev as well, but with more info in the error page:

![screenshot 2016-02-16 11 12 18](https://cloud.githubusercontent.com/assets/796990/13087727/33ab2a7e-d49e-11e5-96e6-6070d0767ddb.png)

**Comment by mejackreed** [comment]
I hear you @LynnMcRae it is just different from how Rails exception handling is done in an application. Trying to reduce argo pattern complexity. Adding a generic link to Squash is trivial in the 500 page. Just if it is really only you and @blalbrit who are using it, is the link needed (and does it confuse someone else dpg?)?

**Comment by LynnMcRae** [comment]
so dev shows all that useful information above ... that's the information we seek ... why does it show here, and why hide that everywhere else?

**Comment by LynnMcRae** [comment]
we did understand a squash link would get us this information however, but confidence you are looking at the entry relating to your session and your error would be important.

**Comment by mejackreed** [comment]
Because we don't run our production/stage applications in debug mode, this is the Rails debug screen that we only run in dev.

I would argue that we shouldn't do something non-standard for argo to show more debugging information to users in production. Users that need to know more about debugging an application error should have the resources/ability to find that information. 

I know that Argo is an internal app, but we shouldn't break best practices or introduce security concerns for that reason.

**Comment by mejackreed** [comment]
@blalbrit seems like sdr services cannot find that object.

**Comment by LynnMcRae** [comment]
yeah, I can buy not running the app in debug mode, but the underlying issue remains .. Ben would have had a fighting change at knowing what was going on if "Resource Not Found" had been conveyed to him when the error occurred instead of filing a ticket and getting developers involved. That's all we're after.  Let's try the squash link at least.

**Comment by mejackreed** [comment]
@LynnMcRae can you make a ticket for that separate work?

**Comment by drh-stanford** [comment]
Re: the original problem. Argo cannot connect to SDR here:  https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/utils/sdr_client.rb#L8. I looked at the SDR_URL config on stage and it looks ok to me. I'm assuming that the problems with SDR and certs on Slack is the culprit here.

**Comment by mejackreed** [comment]
Closing as it was a connection issue
