### ISSUE TITLE
Proposal: Remove Indexer Backlog Status

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#579]
I'm not sure this feature works... or when did it last work?

I'm not sure this is an argo problem but where we fetch the backlog status indicator from.

**Comment by blalbrit** [comment]
@mejackreed - I believe this has been non-functional for quite some time (over a year?). At some point, it was permanently coded to 0, thereby obscuring any actual backlog that might be causing service problems. We should design system notifications for a future sprint that live on one page, communicate a clear issue (indexing slowdown, for instance, if 10K objects are in the queue) that users can understand.

**Comment by mejackreed** [comment]
So we updated the code in Argo to handle correctly whatever the response is from where we get it. But I really think that thing is broken. Coming from sulstats

**Comment by blalbrit** [comment]
Agreed. Unless there is a counterproposal from @LynnMcRae , I +1 your suggestion to remove for now. We can generate an analysis & design ticket for the backlog for a future sprint for work on system notifications that might be relevant to users.

**Comment by darrenleeweber** [comment]
Yea, what does this thing do?  It's called on every request in

**Comment by blalbrit** [comment]
It *used* to provide a numeric value showing the number of objects in the indexing messaging queue. It was a good indicator - if Argo was slow to show changes - that there was a systemic reason for that rather than user-error.

**Comment by LynnMcRae** [comment]
I thought the hyphen meant there was no response, and that's pretty much all I see.  If it's not working, I don't mind the hyphen since it's not a false zero, but neither would I mind it disappearing for now. There's still a need to know about indexing delays, and it was nice to have it on every page, going red at some threshold. But we could have it updated another way, or make it on-demand information if necessary.

**Comment by jmartin-sul** [comment]
i'm :+1: on removing this.  

my $0.02:  we should figure out if sulstats can give us what we're looking for, and if it can't, we should figure out where to get this info.  and whatever we're checking for the backlog, it seems reasonable to have a specific status page, rather than show it on every page (or at least cache it and don't ask for a current value on every page, even if it is an async request).

**Comment by darrenleeweber** [comment]
FYI, the sdr-preservation-core systems run a cron job nightly to update sulstats with summary stats about data in the SDR.

**Comment by drh-stanford** [comment]
i can verify that it's supposed to show the number of messages in the reindexing queue, and that it fetches that information from sulstats. ideally the number is near zero all the time, but if there is congestion, it'll show up there. i'm not privy to the plumbing between sulstats and sulmq, but it may just be a configuration issue as to why it doesn't work.

but if we don't need it, we should drop it because it's fetched on every page.
