### ISSUE TITLE
Use cancancan for managing authorization

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/argo#586]
With #585, it seems like we're rolling our own authorization framework. Many other DLSS projects are successfully using cancancan (including several examples with `dor-rights-auth`-based rights), and it seems a shame to have divergent implementations. I'm concerned, too, that our solution is perhaps less robust or reusable than other community solutions.

Before we get too far with using our home-grown solution, maybe this is a good time to evaluate the various costs. In #585, @darrenleeweber suggested that we had previously concluded cancancan was inappropriate, and I'm curious how and why we came to that decision.

The solution in #585 strikes me as remarkably amenable to converting to cancan-style ability checking, e.g. just taking `can_admin?` and turning it into something like:

```ruby
# can? :admin, object

can :admin, Dor::item if user.is_admin
can :admin, Dor::Item do |item|
  apo = dor_object.admin_policy_object
  true if apo && dor_object.can_manage_item(roles(apo.pid))
 end

can :admin, Dor::AdminPolicyObject do |item|
  dor_object.can_manage_item(roles(dor_object.pid))
 end
```

(compare to https://github.com/sul-dlss/argo/blob/enhance-user-permissions/app/models/user.rb)

I'm surprised, especially given our other successful implementations, that Argo's needs may be so divergent. For something as important as authorization, it might behoove us to try harder to find convergent solutions.

Here are some examples of various cancan implementations in our group:
https://github.com/sul-dlss/hydrus/blob/master/app/models/ability.rb
https://github.com/sul-dlss/digital_stacks_rails/blob/master/app/models/ability.rb
https://github.com/sul-dlss/spotlight/blob/master/app/models/spotlight/ability.rb

**Comment by darrenleeweber** [comment]
One advantage of my solution is that it can take adapt to different access permissions requested for a DOR object, like 'item', 'content', 'metadata' etc. that all depend on methods in Dor::Governable.  My solution is somewhat flexible with changes to Dor::Governable.  That's about all I can say about this at this time.  Given deadlines involved right, I can't consider this seriously until later and I don't know how difficult it would be to change.  It's already difficult to apply the current methods to Argo, but I have explored code that can do it and work as expected.

**Comment by LynnMcRae** [comment]
The original ticket was about adding a permission (APO access) to established roles, nothing else. Any work that refactored the roles/permission stack underneath should have been a separate ticket and put in the backlog for full team analysis and future consideration. But that is water under the bridge.  I agree with Chris that Argo/DOR should have a new authorization model based on where we're going and in common with community work, but that is way out of scope for now (SDR3 in my mind).  The only thing we need now is to know Darren's work provides the same roles/permission outcomes as before (or better, since viewer roles is in there) so we can get the APO access need fullfilled in time for this Argo release -- for the RC2 deployment on Friday even.  Please please please.

**Comment by darrenleeweber** [comment]
If this were to be used and it could adapt to changes in Dor::Governable, it would have to be slightly different, in that an APO object must first check it's governing APO when it's available, e.g.
```ruby
can :admin, Dor::AdminPolicyObject do |item|
  apo = dor_object.admin_policy_object
  return true if apo && dor_object.can_manage_item(roles(apo.pid))
  dor_object.can_manage_item(roles(dor_object.pid))
end
```
