### ISSUE TITLE
Ruby version that we will run in prod?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#62]
Currently we test on travis on Ruby versions:

 - 2.1.1
 - 2.0.0
 - 1.9.3

Is there a reason to still test with 1.9.3 and 2.0.0? Since we are deploying on new vm's shouldn't we also address what Ruby version we use?

Are there any hidden unknown reasons (dor-services?) not to use 2.2.3 (current stable)?

I propose we use CI build for only the version we are deploying. No need to maintain backwards compatibility here. Also this will speed up travis (66% time reduction) which we will need as we contribute more.

**Comment by jmartin-sul** [comment]
AFAIK, we're currently running all the deployed instances on ruby 1.9.3, since that's the only version that's been used so far (in the sense of being used by people, since the unit tests aren't as comprehensive as we'd like).

i'm all for upgrading to 2.x (there's a jira ticket for it, we'd hoped to get it done back around when 1.x became de-supported in feb, before the BL upgrade ended up dragging out so far).  i think we just need some thought as to how we determine whether argo runs on 2.x.  i think "passes unit tests" is less than i'd be comfortable with there, but i think "just start running all instances on 2.x as soon as possible" would actually be fine by me.  that'd require some help from erin on the deployment/VM side, i think.

so yeah, this is just a thing that we hadn't gotten around to yet.  i think joe was actually pushing for the "just do it" approach a while back, and i was more reticent then for some reason.

**Comment by mejackreed** [comment]
:+1: for doing it early... pinging @eefahy

**Comment by atz** [comment]
We should go ahead and try it on dev or stage.

**Comment by drh-stanford** [comment]
We're using 2.2.2 now
