### ISSUE TITLE
Fedora UI and FoXML links on Item View page shouldn't show up for all users

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#643]
Those links require certain permissions - need to restrict when they appear for role 'x' - @LynnMcRae do you have a spec for which?

**Comment by jmartin-sul** [comment]
the link to the solr doc (which was added in argo 3) is limited to dor admins:
https://github.com/sul-dlss/argo/blob/021a90037f29bb4298fcad321d02acde120e3f05/app/helpers/argo_helper.rb#L160

i believe the others have always been available to everyone, but are rendered similarly, and so it'd be easy to perm check them in the same way.

**Comment by cbeer** [comment]
I'll strongly suggest we handle authorization holistically (say, with #596), instead of applying quick fixes.

**Comment by jmartin-sul** [comment]
i'd agree with that suggestion.

**Comment by LynnMcRae** [comment]
@jmartin-sul  said "the link to the solr doc (which was added in argo 3) is limited to dor admins", which was true mainly because there was separate access requirements to query the solr cores.  But it turns out blacklight delivers the solr doc to any user by a .json suffix, e.g., 

https://argo.stanford.edu/catalog/druid:cn700mr2092.json

I can't think of any reason we need to restrict this if there isn't a technical reason.  See #645

**Comment by LynnMcRae** [comment]
As for the Fedora UI and FoXML links ... I think this was discussed in Slack I think, but for the record.  Argo doesn't actually know if the user has login access to the Fedora apps. These are convenience links for SDR Admins who are likely to have that access (more or less by definition).  Since they would (or should) lead to errors if followed by other users, it would be better not to show the links to non sdr-admin folk.

**Comment by jmartin-sul** [comment]
i'd also agree with @LynnMcRae on those last couple comments.

just merged the fix suggested in #645 (PR #649).

so, it seems like we should limit the fedora UI and foxml links to sdr admins, and we should do it through the more thorough auth overhaul mentioned by @cbeer (instead of a check in the style of the old solr link).
