### ISSUE TITLE
Unable to access preservation files

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#666]
When you ask to download a file from the "Contents" area at the bottom of the page, whether from stacks or preservation, there is a Net:SSH error shown in the pop-up (covered by #660). Links to stacks work, but preservation links fail with a 500 (after a period of time).

e.g. try getting the TIF from https://argo.stanford.edu/catalog/druid:bb041kf2037
![screen shot 2016-03-09 at 2 20 23 pm](https://cloud.githubusercontent.com/assets/796990/13653054/551f6900-e604-11e5-9719-5c1924fd930e.png)

**Comment by blalbrit** [comment]
similar to #660 - thanks for the heads-up @peetucket

**Comment by drh-stanford** [comment]
```
Errno::ETIMEDOUT in app/controllers/items_controller.rb:286

Connection timed out - connect([NUMBER]) for "sdr-services.stanford.edu" port [NUMBER]
```

See https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/89 for details.

**Comment by LynnMcRae** [comment]
@eefahy is looking at the SSH authentication error to the DOR workspace

**Comment by eefahy** [comment]
actually @jmartin-sul is taking this one. Looks like we are trying to get to `/dor/workspace` via `lyberservices-prod` however, the app should be able to access the files locally.

**Comment by mejackreed** [comment]
Seems to be able to recreate locally using rn653dy9317. I think it may be an issue with the `list_files` call from within dor-services.

**Comment by LynnMcRae** [comment]
Question: Does Argo use the DOR services call for the delivery of the file as well, or does that use the local file mount?

**Comment by atz** [comment]
Reportedly `list_files` uses SSH to `lyberservices-prod` even when the same `/dor/workspace` mount is available locally.  If the mount is local, we should avoid remote calls, right?

**Comment by ndushay** [comment]
@tingulfsen believes this will be addressed with #707;  we need to deploy that code to argo -stage or -dev to verify if the fix works.

**Comment by LynnMcRae** [comment]
this is an authorization issue with Argo making a specific SDR service call to fetch a file. It is unrelated to #707. John is working on this issue.

**Comment by ndushay** [comment]
these PRs, in this order, will fix it
- sul-dlss/dor-services-app/pull/25
- sul-dlss/dor-services/pull/211   - needs to happen after sul-dlss/dor-services-app/pull/25
- sul-dlss/argo/pull/713  needs to happen after sul-dlss/dor-services/pull/211 and new release of dor-services gem and update to the PR

**Comment by jmartin-sul** [comment]
we'll also need to tag and deploy the updated dor-services-app once its PR is merged to master.

**Comment by ndushay** [comment]
yup - I already started release notes for  dor-services-app and dor-services gem.

**Comment by jmartin-sul** [comment]
just to clarify, since this thread is a bit long, and all the technical details are in PRs split across three different code bases...

the issue here was that argo called `Dor::Contentable#get_preserved_file`, which attempted to retrieve the preserved file content directly from SDR (passing login info via basic auth to get access).  since the argo 3 boxes were not given permission to talk to SDR directly, this broke with the new release.

the solution was to proxy via dor-services-app, which was already proxying other calls to SDR, since it's allowed to talk to SDR directly.  an endpoint for retrieving preserved content from SDR was added to dor-services-app (sul-dlss/dor-services-app#25), dor-services was updated to get preserved content using a new `Sdr::Client` method (sul-dlss/dor-services#211), and argo was updated to use the new dor-services version (PR #713).

anyway, this is deployed to prod, and the example from the description appears to be working, so closing this.
