### ISSUE TITLE
Possible improvements on duplicate Solr fields for diff Solr analysis / behaviors

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#688]
When I see code like this:

```
    def to_solr(solr_doc = {}, *args)
      super solr_doc, *args
      mods_sources = {
        'sw_genre_ssim'               => :sw_genre,
        'sw_genre_tesim'              => :sw_genre,
```

 (from https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/describable.rb#L211-L217 )
- copyfield can be handled with copyField in the Solr schema.xml file;   maybe there was a decision made to avoid this?
- tokenized versions of field are generally intended for searching;  you need to store them if you want to expose hit highlighting.  We haven't figured out a performant way to do that in SW yet.
- you don't need to store facet fields to get the facet behavior.

**Comment by jmartin-sul** [comment]
i don't think we made a conscious decision to avoid copyField.  i think that's just the way that happened to get implemented.  although... maybe we don't want to add a `_tesim` for every `_ssim`, and it is sort of nice to have it called out right there in the code.  would copyField be more performant?

IIRC, we went with all stored fields so that any field used for faceting could also have its value easily displayed on the detail page for a given object.  if that's not actually necessary, we could ditch some stored fields, but i thought i'd run into trouble trying to display e.g. an `_sim` field.

**Comment by ndushay** [comment]
copyField:  i'm not sure if it would be more performant;  I would guess yes, but i'm not sure it matters.  Just a possibility.    It is also possible to do copyField for individual fields, rather than wildcards.

You would need a stored field to be able to display something on the detail page;  not sure if you also display tokenized stuff there ...

**Comment by jcoyne** [comment]
Closing as we no longer index the tokenized version of that field (sw_genre_tesim). See https://github.com/sul-dlss/dor_indexing_app/blob/d9f34cbe2f885464e1632bc5783f82b7a2680d30/app/indexers/descriptive_metadata_indexer.rb#L12-L30
