### ISSUE TITLE
Register/edit APO - fix the generated defaultObjectRIghts XML

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#71]
In the defaultObjectRights datastream we are getting empty elements, like 

```
    <human type="creativeCommons"/> 
    <machine type="creativeCommons"/> 
```
and empty containers, like 

```
  <copyright> 
    <human/> 
  </copyright> 
```
Either don't generate empty tags or do the XML cleanup thing we do.

**Comment by drh-stanford** [comment]
I think this is related to the `dor-services` XML template here https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/datastreams/default_object_rights_ds.rb#L38

**Comment by drh-stanford** [comment]
#70 is related to this for the `use` license data part.

**Comment by drh-stanford** [comment]
@tingulfsen do you think I can easily repurpose the MODSulator code to clean up other XML schemas, like `defaultObjectRights`? I want to do something similar to your `normalize_document` here:

  https://github.com/sul-dlss/modsulator/blob/master/lib/modsulator/normalizer.rb#L198

It looks like some of the code is general purpose and other bits are MODS-specific. But it is a gem that I could include in Argo (or rather `dor-services`) and use selectively, right? Do you see any problems with that approach?

**Comment by LynnMcRae** [comment]
@tingulfsen If I recall correctly, there are only a couple of MODS-specific bits where we make an exception to an "empty tag" (no pcdata, no sub-elements) which we would normally throw away) for cases like <mods:typeOfResource collection="yes">. This might mean it is safe to run against our other XMLs. Can you say which parts of https://consul.stanford.edu/display/chimera/MODS+validation+and+normalization you implemented? I know canonical ordering is not one of them. We talked at the beginning about identifying and universal XML cleanup bits for reuse.  Are they together in the code? I will rework the consul page to make the distinction as well.

**Comment by tingulfsen** [comment]
@LynnMcRae I believe 1-9 are all implemented, except for item 4 on that consul page, where we agreed that the ordering in the XML template should be followed with no attempt at reordering. All of this XML cleanup code is located in the Normalizer within the MODSulator gem.

**Comment by tingulfsen** [comment]
@drh-stanford I'm totally fine with you taking that approach. I suppose you could argue that the Normalizer code could be broken out since parts of it are quite general XML processing. But the class is already so small that it feels odd to split it up into a separate gem just for those general methods, in my opinion.

**Comment by LynnMcRae** [comment]
@tingulfsen, can you confirm or elaborate on the details? Here are the normalizer parts per consul page:

1. Consistent header and schema declaration
    - I thought it was skipped as not needed since we provide the correct header in the template. Else it could be an issue if it's enforcing MODS specific header

2. Schema validation
   - safe if we're just invoking generic "schema, validate yourself"

3. Consistent namespace declaration and use
   - uhhhh, would this make it less generic? does you code actually convert explicit mods: namespace to implicit? Would not have been enneedededed for replayable spreadsheet.

4. Canonical top-level tag ordering
   - skipped

5. Consistent formatting
   - could have been skipped for replayable spreadsheets since we provide a well-formatted template. We'd want it for generic normalizing. Just xmllint or some ruby equivalent?

6. Clean up empty XML tags and containers
   - #6 and #7 are the heart of it
   - wo MODS exceptions
           <typeOfResource collection="yes"/>
           <typeOfResource manuscript="yes"/>

7. Delete empty and irrelevant tag attributes
   - one MODS special regarding an orphan end-date

8. Clean up leading/trailing spaces
   - One MODS exception, generally safe?

9 - Preserve/encode linefeeds in <tableOfContents>, <abstract>, <note>
   - We can expect/insist the incoming spreadsheet data to be encoded, we not needed for replayable spreadsheet (but potentially useful for general MODS remediation)

**Comment by tingulfsen** [comment]
Regarding 1-3, take a look at one of the example XML output files that are used for testing:

https://github.com/sul-dlss/modsulator/blob/master/spec/fixtures/Fitch_Chavez.xml

This shows what the combined output looks like, with several MODS XML entries stringed together (our own <xmlDocs> XML). Also see the template used to generate individual MODS entries:

https://github.com/sul-dlss/modsulator/blob/master/lib/modsulator/modsulator_template.xml

It does actually enforce a specific schema, because it needs to validate the final <xmlDoc> XML. This enables the user to easily check that the generated XML is valid.

Regarding consistent formatting in point 5, you're right that we are aiming for consistent output just by using a standard well-formatted template. There is no code that we currently apply that aim to do anything about indentation. However, I would argue that some of this consistency comes from applying the Normalizer before returning the XML records:

https://github.com/sul-dlss/modsulator/blob/master/lib/modsulator/normalizer.rb#L198-L205

Yes, we are cleaning up the generated XML per point 6 and point 7, enforcing two <typeOfResource> exceptions in point 6 and the <dateIssued> exceptions from point 7. 

Regarding point number 8, I am actually not so sure that it is correctly implemented. I believe we'll actually remove whitespace from every single tag, rather than look at tags grouped together. So I think in your example, the <nonSort> element will have it's single trailing space removed. 

Is <nonSort> the only exceptional element? If so, that makes life a LOT easier to fix this.

I made an attempt at preserving the special characters mentioned in 9, but found it to be a bit of a pain to get everything working perfectly. I'd say it mostly works. If you have any specific test  data for this case it would be much appreciated.

**Comment by LynnMcRae** [comment]
Seeing our own clean input doesn't tell me what the code would do in other circumstances.  So ...

1. Consistent header and schema declaration
   - The spec suggests checking details or replacing whatever XML header with the standard MODS one for consistency. Either way this makes it non-generic. I'm guessing you did NOT implement this. If so, what exactly does it do?

2. Schema validation
   - so a generic self-validation? Nothing MODS specific? Would work with any declared schema that reveals the schema location?

3. Consistent namespace declaration and use
 - you look for xmls:mods and explicit namespace use and convert it? Again, not needed for replayable spreadsheets, so I am guessing you did NOT implement this. 

4. Canonical top-level tag ordering -- skipped for sure

5. Consistent formatting
   - None of the other cleanup addresses simple formatting ... consistent indent, pointless blank lines or tags just strung together.  We get a lot of really really sloppily prepared XML (including our own generated XML that Darren is trying to clean up!).  Can we add this please? I hope somehting as super trivial as xmllint is at your disposal.

6. and 7. -- whoohoo!

8. Clean up leading/trailing spaces
   - The one <titleSort> case is rare and typically comes from converted MARC. Not sure what you mean my groupings; it's just this one exception which I am tempted to ignore.  It should also properly read "Clean up leading/trailing whitespace"

9 - Preserve/encode linefeeds in \<tableOfContents>, \<abstract>, \<note>
   - I'll see if I can do some examples ...we want to give guidance to the replayable spreadsheet user meaning that process is likely covered with a subset of what's described, but the spec concerned other ways sources of XML that might have html markup or other oddities. However, in Darren's case with a Use and Reproduction statement in the APO, we've definitely seem users just copy/paste wrapped text from someplace and we should be removing linefeeds rather that preserving them.  That should take place upstream however and not be the concern of the normalizer.

**Comment by tingulfsen** [comment]
1. The MODSulator just uses the <mods> declaration in the XML template to generate XML. If XML is input, it makes no changes at all to any namespaces.

2. Validation is currently only provided for the built-in <xmlDocs> schema.

3. There's no actual lookup of namespaces. The code assumes that its input corresponds to its built-in schema (i.e. what is produced from spreadsheets).

5. Yeah, I think we can use REXML, a built-in Ruby library, for this.

I'm pretty sure we can come to agreement on all this stuff on Monday.

**Comment by drh-stanford** [comment]
@tingulfsen Please see PR code here: https://github.com/sul-dlss/dor-services/blob/argo-issue-70/lib/dor/datastreams/default_object_rights_ds.rb#L98 ... it implements a few items to clean up `defaultObjectRights` and then calls the `Normalizer`. That code has some MODS-specific cleanup items, so it's missing cleanup of the `rightsMetadata` elements, mainly the `<human>` text nodes.

One problem I see is that we don't have a `rightsMetadata` schema `.xsd` file that I know of, so the validation is not possible right now.

The other problem is that the opinionated metadata datastream code generates the empty template and it's not very forgiving (i.e., throws exception) if you delete elements from the template and try to update the value for the template later. See here for some delete and then add code... I had hoped this wasn't neccesary but I haven't found a better way re: `OmDatastream` : https://github.com/sul-dlss/dor-services/blob/argo-issue-70/lib/dor/datastreams/default_object_rights_ds.rb#L86

**Comment by drh-stanford** [comment]
met with @tingulfsen and will update the normalization code to the revised modsulater when its ready

**Comment by drh-stanford** [comment]
there are repercussions of cleaning out the XML nodes on the "Edit APO" functionality. Once you've deleted the nodes `OmDatastream` doesn't like adding them back as mentioned above.

**Comment by atz** [comment]
I looked into it early this year, concluding that `rightsMetadata` *should* but cannot do XSD sanely, because it relies on ordering, which makes the complexity of expression in XSD factorial.  I did ad hoc validation in the `dor-rights-auth` gem as part of extracting terms for indexing.

For future design, attaching semantic value to order of elements in XML should be strongly discouraged precisely because it blocks strict validation and application of customary tools.  That does not mean your *view* cannot present elements in a given order, just that different interpretations should not be possible when sibling elements are swapped.

**Comment by LynnMcRae** [comment]
where is ordering critical? You mean apart from instance ordering?  There was a bug where embargoReleaseDate had to be placed just so (https://jirasul.stanford.edu/jira/browse/HYDRUS-302, resolved via https://github.com/sul-dlss/sul-embed/issues/302), but that was old PURL code making assumptions, now replaced with embed. There's a nominal document layout for consistency, but that's just what the APO related forms do. Nowhere do we specify semantic order across tags and I don't know of any code interpreting rights metadata with that weakness.

**Comment by drh-stanford** [comment]
@LynnMcRae are there other bugs in the "Edit APO" functionality in our backlog? I'm running into several in my testing that are seemingly (I hope :) unrelated to my fix.

**Comment by drh-stanford** [comment]
here's an example -- with putting a copyright symbol in the copyright statement.

![screen shot 2015-11-25 at 10 14 00 am](https://cloud.githubusercontent.com/assets/1861171/11405548/4433798c-935d-11e5-8783-da284f638b40.png)
