### ISSUE TITLE
APOs indexed incorrectly after an online update - roles disappear

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#725]
We've had reports two of people losing role-based privileges suddenly, and in both cases it was fixed by reindexing the APO.

I have found that an online update of the APO does a reindex in a way that indexes the object as a Dor::Item instead of a Dor::AdminPolicyObject.  It get indexed correctly via the Blue Button.

Privileges are lost when the object is indexed as an Item because the roleMetadata datastream is only indexed for AdminPolicy object types.

After online update (a test APO in prod):
![screen shot 2016-04-08 at 10 19 50 am](https://cloud.githubusercontent.com/assets/1824732/14391958/d09895e4-fd73-11e5-95e6-c04eafdd2dca.png)

After manual reindex:
![screen shot 2016-04-08 at 10 21 29 am](https://cloud.githubusercontent.com/assets/1824732/14391966/d9032f50-fd73-11e5-8844-2c105bad2a17.png)

**Comment by LynnMcRae** [comment]
Test APO link for convenience -- https://argo.stanford.edu/view/druid:bt419zy3596

**Comment by jmartin-sul** [comment]
i've been doing some investigation with @LynnMcRae and so far what we've found is:
* dor-indexing-app, which is supposed to handle asynchronous indexing requests from fedora, is running a slightly outdated version of dor-services (5.6.0, instead of the latest, 5.8.0, which is what argo is running).  however...
* it doesn't appear to be an issue with the version of dor-services:  if the object is manually reindexed by visiting the dor-indexing-app URL for it (e.g. at /dor/reindex/druid:bt419zy3596), the object is indexed correctly.
* when lynn updated bt419zy3596 and allowed the automatic asynchronous reindexing to deal with it, no entry appeared in the logs for the druid on either dor-indexing-app-prod -a or -b, which would seem to indicate that dor-indexing-app isn't actually dealing with the asynchronous reindexing request (or, there are dor-indexing-app instances of which i'm unwaware).  updates were done yesterday afternoon (4/11) around 4:30 pm and 4:50 pm, and this morning (4/12) around 11 am (those times aren't exact, but should be within 10 or 20 min of the described events).

**Comment by jmartin-sul** [comment]
a suspicion that lynn had:
> active fedora can do its own synchronous indexing if you let it, do I remember that correctly?  Something we have to turn off everywhere since we control indexing apart from active fedora? if this is true, might it be on somewhere, or am I barking up a non-existent tree?

because there was lag of up to a few minutes yesterday, i'd tend to think that synchronous indexing isn't involved in this issue.  but the theory does hold some water for me in light of the functional difference between whatever's doing the bad indexing, and the indexing that happens when using `/dor/reindex` (in either argo or dor-indexing-app).

**Comment by jmartin-sul** [comment]
see the PR for explanation of what was actually going wrong, and this comment for plausible explanation of the lag:  https://github.com/sul-dlss/argo/pull/727#issuecomment-209169829
