### ISSUE TITLE
Add check for null in the controller for bulk upload

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#734]
![screenshot 2016-04-25 10 17 12](https://cloud.githubusercontent.com/assets/796990/14792423/f6f362d8-0ace-11e6-8f07-923b26917d5a.png)

https://argo.stanford.edu/catalog/druid:yf767bj4831/bulk_jobs_index

**Comment by blalbrit** [comment]
Other APOs appear to be unaffected.

**Comment by tingulfsen** [comment]
It's this issue:

https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/92

We could potentially make a fairly easy check for null and make this problem go away. @LynnMcRae told us to hold off until the planning meeting on Thursday, so I won't work on this before then, unless told otherwise.

**Comment by LynnMcRae** [comment]
Tommy, we do need a little more analysis for a decision.  What is the null in question?  If any APO without a history of APOs will fail, it's a bit more serious, since there's no way to do that very first upload. But then, we'd never been able to try the facility in the first place. Is there something we can do in the APO to get around this?

**Comment by tingulfsen** [comment]
There was a jobs directory that contained no log file. This caused Squash issue 92 - attempt to read from null. I don't know why there was no log file, but in any case we should throw in a check for null in the controller.

**Comment by blalbrit** [comment]
Thanks Tommy - changed title of ticket, considering this a backlog issue for now.

**Comment by jmartin-sul** [comment]
the call that's failing seems to be:
`sorted_info = bulk_info.sort_by { |b| b['argo.bulk_metadata.bulk_log_job_start'] }`

it's a string sort on a formatted date field for displaying a list of bulk job statuses, right?  i'm not familiar with that code, but that's what seemed to be happening, as far as i could tell.

since it appears that field can sometimes be nil, which would fail a string sort, we could just force the comparison value to be a string, e.g.:
`sorted_info = bulk_info.sort_by { |b| b['argo.bulk_metadata.bulk_log_job_start'].to_s }`

that should prevent the error reported by squash where a nil to string comparison is attempted (for reference, `['a', nil].sort` will produce the error seen here, `ArgumentError: comparison of String with nil failed`; whereas `[nil, 'a'].map(&:to_s).sort` produces `["", "a"]`, with the nil being coerced to empty string).

one problem i ran into:  i can't reproduce the issue by hitting the URLs for which it occurred on stage (e.g. https://argo-stage.stanford.edu/catalog/druid:bc682xk5613/bulk_jobs_index from https://sul-squash-prod.stanford.edu/projects/argo/environments/staging/bugs/31/occurrences/11).  is there something where this is consistently reproducible on stage so we can test the fix?  a unit test might be a good idea too?

**Comment by tingulfsen** [comment]
The error happens when a bulk upload job somehow fails to create a log file, for unknown reasons. I don't know how to reproduce it, other than manually removing the file from its directory.

**Comment by LynnMcRae** [comment]
good to close...the cause of a missing log file is another ticket
