### ISSUE TITLE
Make bulk reindexing a background job in bulk framework

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#743]
"In a future sprint it'd be awesome if we could work on how long it takes to reindex a list of druids within Argo. I'm breaking up the druid lists into batches of about 200 which it can usually handle, but sometimes times out of. I'm doing this via Argo for approx 27k items so it's a lot of granular work.
Thanks for considering!
Laura"

**Comment by jmartin-sul** [comment]
in @lauraw15's case, it sounds like she's already doing this bulk reindexing using a script to hit a /dor/reindex endpoint.  for anyone comfortable enough with scripting on the command line to do that, there's a bulk indexing tool that's faster and more reliable than the /dor/reindex endpoint (esp compared to invoking it via the old argo bulk web UI):
https://github.com/sul-dlss/argo/blob/master/INDEXING.md

that doc is pretty verbose, because it was written with an eye toward things like full reindexing, and is also intended to explain what code is shared between the new bulk reindexer and the /dor/reindex endpoints.  but i'm also totally happy to do a tutorial/walkthrough for the more basic case of just dropping in a long list of druids to reindex.

that mechanism did the full reindex of (at the time) ~900k objects in about 3 days, IIRC.  which would be a throughput of just over 10k druids per hour (and it should require little to no babysitting at this point, though checking status on the indexing work is a bit of a pain, since you have to query it from the command line).

**Comment by blalbrit** [comment]
thanks @jmartin-sul - we'll definitely go that route for the accessioning team, but will want to have a background bulk process for stakeholders outside of that circle (staff in other departments, for instance).

**Comment by jmartin-sul** [comment]
yeah, definitely not a great tool for a wide audience (besides the total lack of GUI, it'd be easy for people to clog the system or step on one another if there are more than one or two people using this at a time).
