### ISSUE TITLE
Add facet for "Accessioned Earliest" with flexible date ranges

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#783]
For reporting purposes, being able to facet to the number of newly accessioned objects for a given time range (day, week, month, quarter, year, random dates) is very important.

New facet would hopefully leverage the accessioned_earliest_dttsi field and a date-picker.

**Comment by LynnMcRae** [comment]
Sure you want the earliest (v1) accessioning date rather than most recent accessioning date?  For new collections this would almost certainly be v1 objects, but a when-last-accessioned facet might have broader use. Not sure I'm thinking this through well ... we may have a separate use case for when registered (conveniently a single event), when first accessioned, and latest version date.

**Comment by blalbrit** [comment]
Yes, I'm sure I want the earliest date of accessioning as a way of tracking new content coming into the repository.

**Comment by blalbrit** [comment]
Note - the search is already accessible through Argo at https://argo.stanford.edu/catalog?utf8=%E2%9C%93&all=true&f%5Baccessioned_earliest_dttsi%5D%5B%5D=%5B2017-01-01T08%3A00%3A00.000Z+TO+2017-12-31T07%3A59%3A59.000Z%5D&commit=submit (or whatever dates). Needs UI wrapped around it?

**Comment by blalbrit** [comment]
Done - thanks @peetucket
