### ISSUE TITLE
rspec-rails gem should not be needed in development environment

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#790]
background:  in deploying argo, rake was unhappy because argo_testing.rake expected rspec.  The fix applied was to include rspec-rails in the  test and development gem groups.

See https://github.com/sul-dlss/argo/pull/789

A better fix would be to improve on https://github.com/sul-dlss/argo/pull/788  by also wrapping the task indicated by cbeer's comment.

**Comment by jmartin-sul** [comment]
i think i disagree that the better fix would be to wrap the task creation in a rescue block.  trapping avoidable exceptions like that instead of not generating them in the first place feels a bit wrong to me (though not terrible).  and in this case, since it's common to run argo's test suite under the development env (on developer laptops), it doesn't seem semantically wrong to include the rspec gem in the development gem group.  and rightfully (considering the current argo development workflow), the rspec rake task is created for both the test and dev rails environments.

to me, the cleanest approach would be to say that unit tests are always run under the test environment.  then, even on a developer laptop, rspec would not be needed as a gem in the dev gem group, or as a rake task in the dev env, and could strictly be a test env/group thing.  but that would also require cleaning up documentation and having developers adjust their workflow.  and i don't see any actual harm in deploying rspec to dev VMs (esp considering that we're not deploying it to staging or prod).  though i agree it's not optimal.  (also totally possible that there's a downside that i haven't considered.)

which is all to say, i vote for not actually giving this issue more attention.  doesn't seem to cause any harm, supports the current workflow, keeps down the proliferation of inline exception trapping.  if i were spending dev effort on argo, i think we'd be better off spending it on something like refactoring the htaccess generation into a method that can be tested, instead of having all that logic inline in a rake file.  or investigating delayed job priorities and worker assignments.  those things seem both more fun and more useful to work on (IMHO).

**Comment by ndushay** [comment]
Is it not the case that when tests are run, they are run in the test rails environment?  That's the rspec default, isn't it?

**Comment by ndushay** [comment]
plus - when i have rspec in test groups in other projects, I can run tests locally ,just fine.  By default, bundle install will install all groups, which is what i do on my laptop.   I never have trouble running tests on my laptop.

**Comment by mejackreed** [comment]
Prefer to leave it in development group if possible. I like the flexibility to run specs as env `DEVELOPMENT`

**Comment by ndushay** [comment]
I'm okay with that, but can you tell me more?  When would you do that and what do you gain?

**Comment by mejackreed** [comment]
That's part of my normal Argo workflow as the env sets which Solr and Fedora instance are being used. I would like to have the ability to run application specs against a different environment. For example:

```sh
RAILS_ENV=development bundle exec rspec spec/features/awesome_feature_spec.rb
```

Rather than needed to `rake ci` or make sure that my Solr and Fedora in dev and test are always synced up. Personal preference, but not necessary.
