### ISSUE TITLE
[argo/production] NoMethodError: undefined method `new_object?' for #<Dor::Item:0x...>

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#864]
## Backtrace

    line 346 of [PROJECT_ROOT]/app/controllers/items_controller.rb: open_version

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/31631820)

**Comment by cbeer** [comment]
Should be `new_record?` with the new active_fedora version.

**Comment by jmartin-sul** [comment]
this seems like one we should try to fix in our own code, since it appears to be a call we're making directly (unlike some of the other AF upgrade issues that've cropped up, which are/were arguably the result of old bad data, which may have been remedied).
https://app.honeybadger.io/projects/49894/faults/31631820#notice-trace
https://github.com/sul-dlss/dor-services/blob/f621c4f30726034399e07343cba7bdd883bbabf5/lib/dor/models/versionable.rb#L28
