### ISSUE TITLE
[argo/production] ModelNotAsserted error during reindex

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#865]
https://app.honeybadger.io/projects/49894/faults/31633294 trying to reindex https://argo.stanford.edu/dor/reindex/druid:yw429ys3733

This may be because it's trying to get a title from the collection the item is in and the collection object does not declare an afModel. Not desirable but it didn't break things before.

**Comment by LynnMcRae** [comment]
Some good news on reindexing ... nearly all bulk requests seem to go through fine. This may be isolated to data conditions with collection objects that need to be referenced when indexing only some items.

**Comment by LynnMcRae** [comment]
I found another patch, but still from a limited set of collections.  I have added afmodel:Dor_Collection to Ross Papers, MARL and MJF and will do a more systematic scan of collections that lack models. Members index fine after this update.

**Comment by LynnMcRae** [comment]
Removing production outage label since we can remediate data, but not closing the ticket because in general we should be able to index the data as is if present, regardless of model anomalies.

**Comment by jmartin-sul** [comment]
seems this will happen whenever indexing an item that belongs to a collection which is missing `afmodel` in `RELS-EXT`.  but, according to the current prod and stage indexes, there are no items left without an `afmodel`:
https://argo.stanford.edu/catalog?f[empties][]=no_has_model
https://argo-stage.stanford.edu/catalog?f[empties][]=no_has_model

also, this is actually coming from an implicit find via the `#collections` method on a `Dor::Item`, and so we can't easily turn the failing `Dor::Collection.find` into a `Dor.find`, since our code isn't making the `.find` call directly (i guess we could override `.find` in `Dor::Collection`).

anyway, hopefully this particular issue isn't actually a problem anymore, since it seems like maybe we don't have this particular sort of bad data anymore?

i would agree that we should be able to index things as they are, but considering the extra work of overriding all the `.find` methods for all of our object types, and considering that this is arguably bad data anyway, i'd be more in favor of fixing the datastreams (which it appears has already happened).

here's where the error comes from:  a `collections` call in `Releaseable#get_release_tags_for_item_and_all_governing_sets`, which is invoked from `Releaseable#to_solr`:
https://app.honeybadger.io/projects/49894/faults/31633294#notice-trace
https://github.com/sul-dlss/dor-services/blob/f621c4f30726034399e07343cba7bdd883bbabf5/lib/dor/models/releaseable.rb#L81
