### ISSUE TITLE
[argo/production] NoMethodError: undefined method `get_release_tags_for_item_and_all_governing_sets' for #<Dor::Set:0x...>

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#866]
## Backtrace

    line 26 of [PROJECT_ROOT]/app/controllers/dor_controller.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/31542167)

**Comment by jmartin-sul** [comment]
@LynnMcRae:

initial investigation makes me think that the issue is that the item being indexed belongs to a set which thinks it's a `Dor_Item`, according to its `afmodel`:
* the item being indexed:  https://argo.stanford.edu/catalog/druid:ks502fr6079
* the set with the seemingly bad `afmodel` (`identityMetadata` says it's a set):  https://argo.stanford.edu/catalog/druid:qr143yj9113

the failing call is coming from `Releaseable#get_release_tags_for_item_and_all_governing_sets`:
```ruby
      collections.each do |collection|
        next if collection.id == id  # recursive, so parents of parents are found, but we need to avoid an infinite loop if the collection references itself (i.e. bad data)
        return_tags = combine_two_release_tag_hashes(return_tags, Dor.find(collection.id).get_release_tags_for_item_and_all_governing_sets)
end
```
https://app.honeybadger.io/projects/49894/faults/31542167#notice-trace
https://github.com/sul-dlss/dor-services/blob/f621c4f30726034399e07343cba7bdd883bbabf5/lib/dor/models/releaseable.rb#L83

what about trying to turn the aforementioned `set` into a collection according to both `RELS-EXT` and `identityMetadata`?
