### ISSUE TITLE
Reconcile bulk "Add Collection" and "Set Collection" with item "Edit Collection"

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#926]
These are confusing options that behave differently for one object vs many. Would like to simply provide the proper collection info and have the system add it if missing else replace the collection reference(s) that's already there, or offer add/replace choice uniformly across both facilities.

**Comment by blalbrit** [comment]
Hello Infrastructure Team,
 
I’m trying to swap the collection for the attached list of druids to jt898xc8096 (i.e., remove the existing collection and replace with this). I thought that I could accomplish this through Bulk update > Set collection, but when I click go it says “Collection not set, already has collection(s)” for all items.
 
My expectation was that if I wanted to set the collection for items that didn’t already have one, I would just use “Add collection”. I read the helper text for “Set collection” (“This will only add the selected collection if the object doesn't already have one.”) as, “If items don’t already have a collection, this update will operate the same as ‘Add collection’ would; otherwise, it will replace the existing collection.”
 
In any case, whether or not “Set collection” does it, it would be great to have a bulk update that provided the latter functionality.
 
Ben: could you help me update the druid list? I’m hoping you have a ready-made script for this kind of simple update. The “Accessioned” objects are all already open for versioning.
 
Thanks!
 
~Nicholas

**Comment by blalbrit** [comment]
Thanks for this detailed feedback message, Nicholas!

Nicholas and I tested a few objects this morning. The item-level page allowed me to the "Edit Collections" blue button, where I removed the unwanted collection. I was then able to add the desired collection. However, the collection is large, and it would not be efficient to update hundreds of objects using this item-level workflow.

My hope is that we might be able to change the "set collection" blue button in bulk update so that it does what the "set APO" bulk update action does - overrides an existing collection with the new/desired collection object.

Nicholas and I wanted to bring this to the team's attention for consideration.

Many thanks!

Laura

**Comment by blalbrit** [comment]
Desired outcome: migrate Collection management tools to Bulk Actions and out of Bulk Update. Options should be to either add a collection to objects that don't have one, or replace the existing collection of objects that do have one.

I'm open to suggestions about the actual interaction: should it be a single action that either adds or replaces, regardless of current collection affiliation, or should it be two separate actions: add *or* replace? I would probably lean towards the former, with a caveat to user that if an object already has a collection associated with it, that collection will be replaced.

**Comment by blalbrit** [comment]
Per @arcadia 👍 
It’s more common to need to move a group of objects from one collection to another than to add a collection without removing the existing one.

**Comment by peetucket** [comment]
@blalbrit curious as to reason to move it from bulk update to bulk actions?  is there some logic about which items belong where or is one just more robust/faster than the other?

**Comment by blalbrit** [comment]
@peetucket - the strategy is to eventually move everything to "bulk actions" so that the jobs could be run asynchronously instead of requiring a user to keep their browser open (in the increasing number of cases where they're running batches of remediations that are large enough to incur browser timeouts... or just wanting to be able to start a job and let it run even if their laptop is closed).

**Comment by peetucket** [comment]
For the purposes of this ticket, I'm proposing to leave the functionality in its current location (bulk update) and:

1. Change the functionality of the "set collection" button to become "add collection if no collection set" or "replace existing collection if currently set".  
2. Get rid of the "add collection" button in the bulk update area to avoid confusion.
3. Update the caveat/instructions for the user to indicate what will happen.

A separate ticket could then address the movement of this logic (and other bulk update logic) to the async bulk actions area (which could end up being more work that simply altering this functionality as it exists now).

**Comment by peetucket** [comment]
Bonus: one *less* blue button! 🎆

**Comment by peetucket** [comment]
Follow up ticket: #1219

**Comment by peetucket** [comment]
This is now done too and will also go out with today's deploy (note: left in bulk update area) - follow up ticket captures desire to move to bulk actions.

**Comment by blalbrit** [comment]
In production, this does not seem to be functioning as expected. From a list of druids, in bulk update, it is possible to prepare the objects. But setting collection then returns an "object not found" error.

In the following test, I am using two objects that belong to a collection:
![screenshot 2018-12-17 13 36 15](https://user-images.githubusercontent.com/796990/50117109-e19e1500-0200-11e9-8695-8a23186b166c.png)

Preparing the objects for a new version works fine. Setting collection to "None" using the dialog box:
![screenshot 2018-12-17 13 36 24](https://user-images.githubusercontent.com/796990/50117135-faa6c600-0200-11e9-86a4-bcb7cc83e60d.png)

Then produces the following errors:
![screenshot 2018-12-17 13 36 33](https://user-images.githubusercontent.com/796990/50117167-0befd280-0201-11e9-89de-1637913abe7b.png)

This does not seem to be throwing any errors in Honeybadger that I can point to.

**Comment by peetucket** [comment]
are you trying to clear all collection associations by setting it to "none"?  is that how it worked before?

**Comment by blalbrit** [comment]
That would be what I would expect as a user. Those buttons never really worked as expected before.

However, despite the error in the Bulk Update screen, the code is executing the correct behavior and has removed the collection from the objects:
![screenshot 2018-12-17 13 41 52](https://user-images.githubusercontent.com/796990/50117374-ae0fba80-0201-11e9-8d79-a4b4e52d8ce7.png)

So this seems to just be a confusing reporting error, rather than it not doing the underlying task.
