### ISSUE TITLE
Deploy to argo-stage

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#93]

**Comment by darrenleeweber** [comment]
`argo-stage` doesn't exist yet, so `argo-test` might be the target for this issue.

**Comment by darrenleeweber** [comment]
There may be no capistrano target for this yet.

**Comment by darrenleeweber** [comment]
The vm target is `argo-stage-b` and the cap target is `stage-b` (don't ask me why it's `b`).

**Comment by jmartin-sul** [comment]
my original understanding (from @eefahy ) was that there would be a load balanced argo-stage, but that the initial argo-stage deployments would only go to the argo-stage-b VM, similarly to what was done with argo-prod-b.  can't remember if there was other rationale for that besides instance similarity, or if i was possibly misunderstanding or conflating setup instructions, since nothing's using argo-stage-at at the moment (AFAIK).

indeed, argo-stage does not seem to exist, but i can ssh into argo-stage-b as lyberadmin if i've got valid kerb credentials:
`ssh lyberadmin@argo-stage-b`

**Comment by darrenleeweber** [comment]
Bump as ready for further deploy testing, if @eefahy is done with config setup etc.?

**Comment by jmartin-sul** [comment]
workin on it.  met w/ @eefahy earlier this afternoon, she's making some .htaccess changes in puppet, i'm pulling the htaccess generation rake task from argo (or at least keeping it from running by default on deployment).  once that's done, we'll try another deployment and regroup if there are more errors, or start testing indexing if the deployment's successful.

hopefully once this is ironed out, updating argo-dev's puppet stuff* to use the new config style will be easier and involve less iteration.

*"puppet stuff" is a technical term

**Comment by jmartin-sul** [comment]
updates:
* left htaccess stuff in afterall.  needed it to keep things working as-is, so that argo can get all the workgroup info it needs from webauth to do permissions checks.  https://github.com/sul-dlss/argo/issues/138 addresses cleaning this mechanism up.
* there's currently a permission error in stage deployment that's keeping argo from opening its .key file.  this is the only current known code deployment hangup, but we shall see if another pops up after that's resolved, or if that's the last one.
* for argo to actually do permissions checking properly, it needs to be authorized to get specific workgroup info from LDAP, and that authorization might take a couple of days, according to erin.  the code could be deployed and run without that, but the web UI will not be useful until that authorization is granted.

**Comment by jmartin-sul** [comment]
closing this since argo's webcode has been successfully deployed to stage.  for the web UI to be practically usable, the proper LDAP authorization will have to be granted to the VM, but that request for authorization is in progress.
