### ISSUE TITLE
Provide better user-facing error message on metadata-refresh problems

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#936]
This is a specific case within a cluster of desired enhancements to provide better user-facing error reporting from our underlying services.

If there is an error in the catkey identifier in identityMetadata for an object, and a user tries to use the "Refresh MODS" button on the bulk update page, the only error message is a generic 500. See https://app.honeybadger.io/projects/49894/faults/32565848 for example.

Preferred behavior would be "catkey not found" or something similar in the error message output.

In this specific example, there was a leading "a" and the underlying service looks like this in the two cases (first incorrect, second correct):
http://lyberservices-prod.stanford.edu/catalog/mods?catkey=a3877801
http://lyberservices-prod.stanford.edu/catalog/mods?catkey=3877801

**Comment by cbeer** [comment]
I don't think we are currently getting sufficient information from the catalog service to provide any additional guidance. We have more opportunity to improve things once we can transition to the dor-services-app-provided one, although that is blocked by a variety of MARC -> MODS mapping problems (tracked by @LynnMcRae)

Also, I believe it is local practice to prefix our MARC 001 fields with 'a'. Does that suggest we should support both forms?

**Comment by blalbrit** [comment]
I would defer to @LynnMcRae on support of both forms - agree that the internal identifier practice is to prefix with 'a'.

👍 to better support when we can provide it. There is a whole suite of requests for better reporting and this is just one more story to fit in when that work is eventually done.

**Comment by LynnMcRae** [comment]
We could be cognizant of the leading "a" in places like item registration where we'd have a chance to strip it, since what lands in DOR needs to be an actual catkey. I understand from Ben this ticket is the result of a direct copy/paste into identityMetadata, so it remains bad data. And since it's part of a new Metadata Dept workflow for serials, they really should know the difference!

We have a ticket for a "Manage catkey" widget which could make this better. It is proposed for the publish and release implications of adding/changing/removing links to Symphony, but would handle this data wrinkle nicely.

Fun facts from Darsi: the 001 in Symphony doesn’t really exist unless it holds identifiers from other sources … what we see as 001 is an artifact produced by Symphony on export, and the leading “a” is a default prefix used by multiple sites like ours that don’t care. For a while now they have been putting the actual catkey into a 918 tag but since that's new it's not pervasive, nor do we see it currently in our lookup view.

**Comment by andrewjbtw** [comment]
We do now get a "catkey not found" message. And we validate the data being entered, so it would catch a letter like "a".
