### ISSUE TITLE
Add a blue button to edit/add catkey for a single item

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#947]
Use dor-services method being generated here: https://github.com/sul-dlss/dor-services/issues/311

**Comment by LynnMcRae** [comment]
Perhaps the phrase "edit catkey" was misleading if you are only showing it when the object already has a catkey, or is adding a catkey coming? It should be more of a "Manage catkey" available to add a catkey as well as change/remove it.  Like with John's "Set APO" work, we'd like to to see screenshots of a work in progress in order to do a cosmetic/wording pass.

**Comment by peetucket** [comment]
The current implementation really is an "edit catkey" button, since the infrastructure document stated the function should be "update catkey".  It only shows for objects that currently have one.  Should I make it "manage catkey" and allow you to add one if it doesn't exist?  Should be easy if the UI is the same (i.e. just a popup modal with a textbox like the existing source ID one, shows the current catkey for an edit, shows nothing for an add).

**Comment by LynnMcRae** [comment]
Yes, same UI, just before or after can be blank. Sorry about the ambiguity of the term "update". It could have been more abstracted to "Update Metadata Source" if it was anything more than just the catkey, but it was sort of in that spirit.
