### ISSUE TITLE
Blue Buttons: Disable Create Collection and Edit APO when not on an APO object

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#963]
![screenshot 2017-03-24 10 51 45](https://cloud.githubusercontent.com/assets/796990/24307122/265f3ac6-1080-11e7-9e53-cab8397ede77.png)

Clicking either, on an item, throws a "we're sorry, something went wrong" error.

**Comment by LynnMcRae** [comment]
It should be disable button, not hide it?

**Comment by blalbrit** [comment]
Yes - disable button, agreed - editing title.

**Comment by jmartin-sul** [comment]
i would argue that we should hide the button in this case -- to me, disable implies that something about the object state could change, and allow the button to be re-enabled.  but it seems to me that "Edit APO" will never be an appropriate action for a non-APO object.

anyway, right now those buttons are shown if the object's datastreams include `roleMetadata`.  whether the right thing to do is to hide or to disable, i assume this ticket is saying that the check should be based on object type, and that hide/disable should only happen on objects of type `Dor::AdminPolicyObject`?

**Comment by mejackreed** [comment]
Part of the reason for the current state is:

 - legacy code (that crazy helper method)
 - this legacy code was creating `n` blocking requests for a page load (which the disable thing was part of the fix)

The disable thing could be moved to make the button appear, but a little ui change might be needed.

**Comment by jmartin-sul** [comment]
@mejackreed:  agreed, the way `check_url` and button disabling works totally makes sense in context, and is reasonable, and a huge improvement over the way it was with a bunch of sequentially executed network requests blocking the response (and didn't mean to imply otherwise in #968).  in this particular case, though, i think the information needed to determine whether the button is hidden is already available (object type), and just needs to be used instead of the current (sometimes inaccurate) proxy it's using for obj type (presence of roleMetadata DS).

@blalbrit:  i was able to convince @LynnMcRae of the argument in my prior comment, so that's how it's implemented in PR #973 ("Edit APO" and "Create Collection" are not rendered for non-APO objects) 😃
