### ISSUE TITLE
Alpha-sort collection drop-down on registration page

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#974]
Please alpha sort the collection drop-down in the Register Items interface. I have so many collections to sort through it's hard to find what I'm looking for.

Thanks,

Daniel Hartwig
University Archivist
dhartwig@stanford.edu
650-725-1161

**Comment by oceanofsound** [comment]
Seconded!!

**Comment by blalbrit** [comment]
When I go to register items in Argo, and have selected an APO, the collections under that APO are not listed alphabetically (as is helpfully the case elsewhere in Argo).

We have 217 collections under the Stanford University Libraries - University Archives APO, and I currently need to hunt down the related collection from this list each time I register items. 

It would be wonderful in registration to have the collections listed alphabetically as well.

Thanks!

Josh

**Comment by oceanofsound** [comment]
It's true. It has gotten to the point where it's easier to bulk add the collection post-registration, because in the bulk screen all the collections are listed alphabetically.

**Comment by LynnMcRae** [comment]
The collections are shown in their order of declaration in the APO. Alpha makes way more sense of course, but to alleviate the immediate pain point, I rearranged the collection declarations for the "Stanford University Libraries - University Archives" APO to be in alpha order. Do we have any other particularly long lists in APOs? It's not a sustainable solution since new collections will just be added at the end, but I hope it helps in the short term.
