### ISSUE TITLE
repo:load fails, now with better error reportage

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#99]
The last few fixture objects that the command rake argo:repo:load is attempting to load up consistently fail.

**Comment by drh-stanford** [comment]
This is what these errors look like for me -- File 41 succeeds but 42-47 fail:

![screen shot 2015-11-02 at 3 49 06 pm](https://cloud.githubusercontent.com/assets/1861171/10897794/4c00affe-8179-11e5-91dc-c3b8f6f5b57f.png)

**Comment by mejackreed** [comment]
Same thing seems to be causing CI build failure.

**Comment by jmartin-sul** [comment]
the laptop version of this is hopefully addressed by PR #102.  the CI version of the problem still cropped up in the travis report on that branch, but the `getaddrinfo` error seen there is likely different from the laptop problem described above (and seems specific to travis).

**Comment by drh-stanford** [comment]
this is working for me on my laptop

**Comment by jmartin-sul** [comment]
also, as pointed out by @atz, the `getaddrinfo` errors aren't fatal, and travis is loading its fixtures successfully.  though it still seems very possible that the travis errors are the result of argo trying to contact an unavailable external service.

**Comment by atz** [comment]
From my investigations in Travis-land, `getaddrinfo` errors were around resolving `localhost` in attempting to POST to fedora.  (That basically makes no sense at all.  For a while I had a `before_script` entry that cat'd out /etc/hosts confirming that, yeah, localhost is in there.)  These 404's are more interesting.  That says that the remote endpoint *is* being reached, and is responding, but just doesn't have what is requested.  Would be interested to see workflow_service.log or any other log output after those 404s to identify the request itself.

**Comment by atz** [comment]
Also, it fails once... but then succeeds loading the same file in the next attempt?  What is with that?  That mean the 404 resolves?  Is there some kind of race condition where one thing posted isn't fully retrievable when the next request begins?  All this basically doesn't matter since all the files get loaded by the end of the run.

**Comment by jmartin-sul** [comment]
my understanding is that it turns out that the 404s were resolved by PR #102 (on laptops, at least).

i'm doing some testing with the CI build on my laptop, and i noticed something i didn't expect when i ran it.  even when i switched back to the local stanford wi-fi, i still got exactly the same `getaddrinfo` errors and test failures as travis (in particular, the errors appear the same number of times on the same fixture loads, and the 5 test failures appear to be the same as what travis gets).  that seems to contradict the (my?) theory that this is an issue with travis not being able to reach internal stanford services, since my laptop should be able to resolve those things now that i'm not testing by tethering off my cell phone.

**Comment by jmartin-sul** [comment]
oh, weird, good observation about the 404 retry appearing to succeed.  in my experience, though, those fixture objects were not indexable at all.  they always got the same 404 when to_solr was invoked on them, no matter how many attempts were made.

**Comment by atz** [comment]
OK, I take it back.  The retries were **not** succeeding, they were being swallowed due to rake's understanding of idempotence.  I.E., the `repo:load` task was already run (and error was handled, so it "completed"), so the next `repo:load` is a no-op.  *Then* our task reenables it.  So the next `repo:load` is actually attempted.  Etc.  

Damn thing should have been written to take an argument.  The argo wrapper task is reworked on `develop` now so we should get concrete errors and the whole task/build will fail when a given file will not load.
